-- DRAFT_provider_claimable_migration.sql
-- ⚠️ DRAFT — review, then turn into a numbered migration (next free number is 0124).
--    Do NOT drop this file into supabase/migrations/ as-is; it lives in seed/directory/
--    so no migration runner picks it up before you've read it.
--
-- PURPOSE — turn the existing provider spine (0014) into a SEED + CLAIM directory,
-- the Google-Business / Yelp / LinkedIn model:
--   1. pre-populate real businesses as UNCLAIMED, publicly discoverable listings;
--   2. let the real owner later CLAIM their listing and take ownership.
--
-- KEY DESIGN DECISION — the owner invariant.
--   providers.owner_user_profile_id is NOT NULL and the whole 0024 RLS set reasons from
--   "owner = creator". Rather than make that column nullable (which forces re-auditing
--   every provider policy + the create-CTE), seeded listings are owned by ONE system
--   "PawPi Directory" account until claimed. Claiming = reassign ownership to the real
--   owner. The nullable-owner alternative is sketched at the very bottom.
--
-- Everything here is additive and idempotent. No existing row or policy is dropped.
-- Discovery needs NO RLS change: providers_select already public-reads status='published',
-- so seed rows go in published+unclaimed and the app shows a "¿Es tu negocio?" button
-- whenever claim_status = 'unclaimed'.

begin;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) SYSTEM directory account — owns every seeded, unclaimed listing.
--    auth_users(name,email) → user_profiles(auth_user_id, role, username). Idempotent.
--    ⚠️ VERIFY: confirm user_profiles has no other NOT NULL column beyond the ones set
--    here (0002 shows auth_user_id, role, onboarding_completed as NOT NULL; username is
--    UNIQUE — add display_name etc. here if your live schema requires them).
do $$
declare v_auth int; v_profile int;
begin
  select up.id into v_profile
    from user_profiles up join auth_users au on au.id = up.auth_user_id
    where au.email = 'directory@pawpi.system';
  if v_profile is null then
    insert into auth_users(name, email)
      values ('PawPi Directory', 'directory@pawpi.system')
      returning id into v_auth;
    insert into user_profiles(auth_user_id, role, username, onboarding_completed)
      values (v_auth, 'admin', 'pawpi_directory', true)
      returning id into v_profile;
  end if;
end $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) providers — claim + provenance columns.
--    source        : where the row came from (drives trust / refresh policy)
--    external_*    : dedup + re-sync key so a second import UPDATEs instead of duplicating
--    claim_status  : unclaimed → pending → claimed  (defaults 'claimed' so every EXISTING
--                    owner-created row is treated as already claimed — no behaviour change)
--    claimed_at    : when ownership transferred to the real owner
alter table providers
  add column if not exists source          text        not null default 'owner',
  add column if not exists external_source text,
  add column if not exists external_id     text,
  add column if not exists claim_status    text        not null default 'claimed',
  add column if not exists claimed_at      timestamptz;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'providers_source_check') then
    alter table providers add constraint providers_source_check
      check (source = any (array['owner','manual','osm','google','import']::text[]));
  end if;
  if not exists (select 1 from pg_constraint where conname = 'providers_claim_status_check') then
    alter table providers add constraint providers_claim_status_check
      check (claim_status = any (array['unclaimed','pending','claimed']::text[]));
  end if;
end $$;

-- One row per external place — lets a re-import upsert on (external_source, external_id).
create unique index if not exists providers_external_key
  on providers (external_source, external_id)
  where external_source is not null and external_id is not null;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) provider_claims — the pending-claim / verification ledger.
--    The moment a user taps "This is my business" we record a claim here; a human (or an
--    automated phone/email check) approves it, and the APPROVAL action (step 4, run as the
--    privileged server role) is what actually moves ownership.
create table if not exists provider_claims (
  id                       integer generated by default as identity primary key,
  provider_id              integer not null references providers(id) on delete cascade,
  claimant_user_profile_id integer not null references user_profiles(id) on delete cascade,
  status                   text not null default 'pending'
                             check (status = any (array['pending','approved','rejected','withdrawn']::text[])),
  method                   text check (method = any (array['phone','email','document','other']::text[])),
  evidence                 jsonb,          -- e.g. {"phone_verified_to":"+54...","doc_url":"..."}
  note                     text,
  created_at               timestamptz not null default now(),
  decided_at               timestamptz,
  decided_by               integer references user_profiles(id),
  -- at most one live claim per (business, claimant); re-claim after a reject is allowed by
  -- updating the existing row back to 'pending'.
  constraint provider_claims_provider_claimant_key unique (provider_id, claimant_user_profile_id)
);
create index if not exists idx_provider_claims_provider  on provider_claims (provider_id);
create index if not exists idx_provider_claims_claimant on provider_claims (claimant_user_profile_id);

-- RLS — mirrors the 0024 style (current_app_user_id() = the acting user).
alter table provider_claims enable row level security;
alter table provider_claims force row level security;

-- SELECT: my own claims (claim status page) OR platform admin (the review queue).
drop policy if exists provider_claims_select on provider_claims;
create policy provider_claims_select on provider_claims
  for select using (
    claimant_user_profile_id = current_app_user_id()
    or exists (select 1 from user_profiles up
               where up.id = current_app_user_id() and up.role = 'admin')
  );

-- INSERT: I can only open a claim as myself, and only against a listing that is currently
-- UNCLAIMED (the providers EXISTS runs under providers' own SELECT RLS — a published
-- unclaimed listing is visible, so no SECURITY DEFINER helper is needed).
drop policy if exists provider_claims_insert on provider_claims;
create policy provider_claims_insert on provider_claims
  for insert with check (
    claimant_user_profile_id = current_app_user_id()
    and exists (select 1 from providers p
                where p.id = provider_id and p.claim_status = 'unclaimed')
  );

-- UPDATE: claimant may withdraw their own claim; admin may decide (approve/reject).
drop policy if exists provider_claims_update on provider_claims;
create policy provider_claims_update on provider_claims
  for update using (
    claimant_user_profile_id = current_app_user_id()
    or exists (select 1 from user_profiles up
               where up.id = current_app_user_id() and up.role = 'admin')
  );

commit;

-- ─────────────────────────────────────────────────────────────────────────────
-- 4) CLAIM APPROVAL — reference logic, NOT a policy. Run from your API as the
--    privileged/service role (it edits an unclaimed listing the caller does not yet own,
--    so it must bypass RLS). Wrap in one transaction:
--
--    update providers
--       set owner_user_profile_id = :claimant, claim_status = 'claimed', claimed_at = now()
--     where id = :provider_id and claim_status in ('unclaimed','pending');
--
--    insert into provider_staff (provider_id, user_profile_id, role, status)
--    values (:provider_id, :claimant, 'owner', 'active')
--    on conflict (provider_id, user_profile_id)
--      do update set role = 'owner', status = 'active';
--
--    update provider_claims
--       set status = 'approved', decided_at = now(), decided_by = :admin
--     where id = :claim_id;
--
--    -- (optional) reject the other pending claims on this provider.

-- ─────────────────────────────────────────────────────────────────────────────
-- 5) SEEDING — how the 1,032 real CABA+AMBA rows load (also run as the service role):
--    for each place →
--      insert into providers
--        (owner_user_profile_id, provider_type, name, slug, status, source,
--         external_source, external_id, claim_status)
--      values (:directory_profile, :type, :name, :slug, 'published', 'osm',
--              'osm', :osm_id, 'unclaimed')
--      on conflict (external_source, external_id) do update
--        set name = excluded.name, updated_at = now();   -- idempotent re-sync
--    then insert the matching provider_locations (address, lat, lng, phone, hours_json).
--    type mapping: OSM veterinary→'vet', shop=pet→'shop', pet_grooming→'groomer'.

-- ─────────────────────────────────────────────────────────────────────────────
-- ALTERNATIVE design (nullable owner, no system account):
--   alter table providers alter column owner_user_profile_id drop not null;
--   -- then audit 0024: the `owner_user_profile_id = current_app_user_id()` branches are
--   -- already null-safe (NULL never equals a real id), and the create-CTE still sets an
--   -- owner, so unclaimed = owner IS NULL. Cleaner data model, larger review surface.
