-- 0001_auth.sql
-- Auth.js adapter tables — matches supabase_schema.sql (real Anything/Neon dump) exactly.
-- Keys are integer identity (the real DB used serial sequences; identity is the equivalent).
-- NOTE: the real schema has NO unique constraints on email / "sessionToken" /
-- (provider,"providerAccountId") and email is nullable — reproduced faithfully.

create table if not exists auth_users (
  id              integer generated by default as identity primary key,
  name            varchar(255),
  email           varchar(255),
  "emailVerified" timestamptz,
  image           text
);

create table if not exists auth_accounts (
  id                  integer generated by default as identity primary key,
  "userId"            integer not null references auth_users(id) on delete cascade,
  type                varchar(255) not null,
  provider            varchar(255) not null,
  "providerAccountId" varchar(255) not null,
  refresh_token       text,
  access_token        text,
  expires_at          bigint,
  id_token            text,
  scope               text,
  session_state       text,
  token_type          text,
  password            text
);

create table if not exists auth_sessions (
  id             integer generated by default as identity primary key,
  "userId"       integer not null references auth_users(id) on delete cascade,
  expires        timestamptz not null,
  "sessionToken" varchar(255) not null
);

create table if not exists auth_verification_token (
  identifier text not null,
  expires    timestamptz not null,
  token      text not null,
  primary key (identifier, token)
);
