-- 0002_user_profiles.sql
-- Identity hinge: auth_users.id --(auth_user_id, integer)--> user_profiles --(id)--> owner key.
-- Matches supabase_schema.sql exactly.

create table if not exists user_profiles (
  id                   integer generated by default as identity primary key,
  auth_user_id         integer not null references auth_users(id) on delete cascade,
  full_name            varchar(255),
  username             varchar(100),
  avatar_url           text,
  role                 varchar(50) not null default 'pet_owner',
  onboarding_completed boolean not null default false,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  constraint user_profiles_auth_user_id_key unique (auth_user_id),
  constraint user_profiles_username_key unique (username),
  constraint valid_role check (role::text = any (array['pet_owner','vet','business','shelter','admin']::text[]))
);

create index if not exists idx_user_profiles_auth_user on user_profiles (auth_user_id);
create index if not exists idx_user_profiles_auth_user_id on user_profiles (auth_user_id);
create index if not exists idx_user_profiles_username on user_profiles (username);
