-- 0003_pets.sql
-- pets.owner_user_id -> user_profiles.id. Matches supabase_schema.sql exactly.
-- Note: species and weight_unit have NO defaults in the real schema.

create table if not exists pets (
  id            integer generated by default as identity primary key,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  name          text not null,
  handle        text,
  avatar_url    text,
  species       text,
  breed         text,
  age_years     integer,
  age_months    integer,
  gender        text,
  weight        numeric(5,2),
  weight_unit   text,
  birthday      date,
  adoption_date date,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint pets_handle_key unique (handle)
);

create index if not exists idx_pets_created_at on pets (created_at desc);
create index if not exists idx_pets_handle on pets (handle);
create index if not exists idx_pets_owner on pets (owner_user_id);
create index if not exists idx_pets_owner_user_id on pets (owner_user_id);
