-- 0004_social.sql
-- Social feed: posts, post_paws, post_barks, pet_friendships. Matches supabase_schema.sql exactly.

create table if not exists posts (
  id              integer generated by default as identity primary key,
  user_id         integer not null references user_profiles(id) on delete cascade,
  pet_id          integer not null references pets(id) on delete cascade,
  image_url       text,
  caption         text,
  is_daily_update boolean not null default false,
  post_date       date not null default current_date,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_posts_created_at on posts (created_at desc);
create index if not exists idx_posts_daily_update on posts (is_daily_update, post_date desc);
create unique index if not exists idx_posts_one_daily_per_pet_per_day on posts (pet_id, post_date) where (is_daily_update = true);
create index if not exists idx_posts_pet on posts (pet_id);
create index if not exists idx_posts_pet_id on posts (pet_id);
create index if not exists idx_posts_user on posts (user_id);
create index if not exists idx_posts_user_id on posts (user_id);

create table if not exists post_paws (
  id         integer generated by default as identity primary key,
  post_id    integer not null references posts(id) on delete cascade,
  user_id    integer not null references user_profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint post_paws_post_id_user_id_key unique (post_id, user_id)
);

create index if not exists idx_post_paws_created_at on post_paws (created_at desc);
create index if not exists idx_post_paws_post on post_paws (post_id);
create index if not exists idx_post_paws_post_id on post_paws (post_id);
create index if not exists idx_post_paws_user on post_paws (user_id);
create index if not exists idx_post_paws_user_id on post_paws (user_id);

create table if not exists post_barks (
  id         integer generated by default as identity primary key,
  post_id    integer not null references posts(id) on delete cascade,
  user_id    integer not null references user_profiles(id) on delete cascade,
  text       text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_post_barks_created_at on post_barks (created_at desc);
create index if not exists idx_post_barks_post on post_barks (post_id);
create index if not exists idx_post_barks_post_id on post_barks (post_id);
create index if not exists idx_post_barks_user on post_barks (user_id);
create index if not exists idx_post_barks_user_id on post_barks (user_id);

create table if not exists pet_friendships (
  id                integer generated by default as identity primary key,
  requester_user_id integer not null references user_profiles(id) on delete cascade,
  receiver_user_id  integer not null references user_profiles(id) on delete cascade,
  requester_pet_id  integer not null references pets(id) on delete cascade,
  receiver_pet_id   integer not null references pets(id) on delete cascade,
  status            text not null default 'pending',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint pet_friendships_status_check check (status = any (array['pending','accepted','blocked']::text[]))
);

create index if not exists idx_pet_friendships_created_at on pet_friendships (created_at desc);
create index if not exists idx_pet_friendships_receiver_pet on pet_friendships (receiver_pet_id);
create index if not exists idx_pet_friendships_receiver_user_id on pet_friendships (receiver_user_id);
create index if not exists idx_pet_friendships_requester_pet on pet_friendships (requester_pet_id);
create index if not exists idx_pet_friendships_requester_user_id on pet_friendships (requester_user_id);
create index if not exists idx_pet_friendships_status on pet_friendships (status);
