-- 0005_vet_records.sql
-- Vet record domain. vet_appointments first (vet_notes.appointment_id references it).
-- Soft-delete (deleted_at) on vet_appointments and pet_medical_profiles only.
-- Matches supabase_schema.sql exactly.

create table if not exists vet_appointments (
  id               integer generated by default as identity primary key,
  pet_id           integer not null references pets(id) on delete cascade,
  owner_user_id    integer not null references user_profiles(id) on delete cascade,
  title            text not null,
  appointment_date date not null,
  appointment_time time without time zone not null,
  clinic           text,
  veterinarian     text,
  reason_for_visit text,
  notes            text,
  reminder_enabled boolean default true,
  time_sensitive   boolean default true,
  reminder_timing  text default 'at_time',
  add_to_calendar  boolean default false,
  calendar_event_id text,
  status           text default 'scheduled',
  created_at       timestamptz default now(),
  updated_at       timestamptz default now(),
  deleted_at       timestamptz,
  constraint vet_appointments_status_check check (status = any (array['scheduled','completed','cancelled','missed']::text[]))
);

create index if not exists idx_vet_appointments_appointment_date on vet_appointments (appointment_date);
create index if not exists idx_vet_appointments_deleted_at on vet_appointments (deleted_at);
create index if not exists idx_vet_appointments_owner_user_id on vet_appointments (owner_user_id);
create index if not exists idx_vet_appointments_pet_id on vet_appointments (pet_id);
create index if not exists idx_vet_appointments_status on vet_appointments (status);

create table if not exists pet_medical_profiles (
  id                       integer generated by default as identity primary key,
  pet_id                   integer not null references pets(id) on delete cascade,
  owner_user_id            integer not null references user_profiles(id) on delete cascade,
  microchip_id             text,
  spayed_neutered_status   text,
  spayed_neutered_date     date,
  primary_vet_name         text,
  primary_clinic_name      text,
  vet_phone                text,
  vet_email                text,
  emergency_contact_name   text,
  emergency_contact_phone  text,
  insurance_provider       text,
  insurance_policy_number  text,
  medical_notes            text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  deleted_at               timestamptz,
  constraint pet_medical_profiles_pet_id_key unique (pet_id)
);

create index if not exists idx_pet_medical_profiles_owner_user_id on pet_medical_profiles (owner_user_id);
create index if not exists idx_pet_medical_profiles_pet_id on pet_medical_profiles (pet_id);

create table if not exists pet_allergies (
  id             integer generated by default as identity primary key,
  pet_id         integer not null references pets(id) on delete cascade,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  allergen       text not null,
  severity       text,
  reaction       text,
  diagnosed_date date,
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists idx_pet_allergies_owner_user_id on pet_allergies (owner_user_id);
create index if not exists idx_pet_allergies_pet_id on pet_allergies (pet_id);

create table if not exists pet_conditions (
  id             integer generated by default as identity primary key,
  pet_id         integer not null references pets(id) on delete cascade,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  condition      text not null,
  status         text default 'active',
  diagnosed_date date,
  notes          text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists idx_pet_conditions_owner_user_id on pet_conditions (owner_user_id);
create index if not exists idx_pet_conditions_pet_id on pet_conditions (pet_id);

create table if not exists pet_lab_results (
  id            integer generated by default as identity primary key,
  pet_id        integer not null references pets(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  test_name     text not null,
  test_date     date not null,
  results       text,
  ordered_by    text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_pet_lab_results_date on pet_lab_results (test_date desc);
create index if not exists idx_pet_lab_results_owner_user_id on pet_lab_results (owner_user_id);
create index if not exists idx_pet_lab_results_pet_id on pet_lab_results (pet_id);

create table if not exists pet_surgeries (
  id            integer generated by default as identity primary key,
  pet_id        integer not null references pets(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  procedure     text not null,
  surgery_date  date not null,
  surgeon       text,
  clinic        text,
  complications text,
  recovery      text,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_pet_surgeries_date on pet_surgeries (surgery_date desc);
create index if not exists idx_pet_surgeries_owner_user_id on pet_surgeries (owner_user_id);
create index if not exists idx_pet_surgeries_pet_id on pet_surgeries (pet_id);

create table if not exists vet_documents (
  id            integer generated by default as identity primary key,
  pet_id        integer not null references pets(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  name          text not null,
  document_type text not null,
  file_url      text not null,
  document_date date,
  notes         text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index if not exists idx_vet_documents_date on vet_documents (document_date desc);
create index if not exists idx_vet_documents_owner_user_id on vet_documents (owner_user_id);
create index if not exists idx_vet_documents_pet_id on vet_documents (pet_id);

create table if not exists vet_notes (
  id             integer generated by default as identity primary key,
  pet_id         integer not null references pets(id) on delete cascade,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  vet_name       text,
  note_date      date not null,
  note           text not null,
  appointment_id integer references vet_appointments(id) on delete set null,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists idx_vet_notes_date on vet_notes (note_date desc);
create index if not exists idx_vet_notes_owner_user_id on vet_notes (owner_user_id);
create index if not exists idx_vet_notes_pet_id on vet_notes (pet_id);
