-- 0006_routines.sql
-- Care routines. Matches supabase_schema.sql exactly.
-- Real types confirmed: preferred_day integer, times text[], days integer[].
-- Real schema has BOTH medical_care_schedule AND medical_care_details (jsonb), plus
-- wellness_check_schedule and vet_appointment_schedule.

create table if not exists routines (
  id                       integer generated by default as identity primary key,
  pet_id                   integer not null references pets(id) on delete cascade,
  owner_user_id            integer not null references user_profiles(id) on delete cascade,
  routine_type             text not null,
  is_active                boolean not null default true,
  title                    text,
  description              text,
  feeding_schedule         jsonb,
  walk_schedule            jsonb,
  medication_details       jsonb,
  photo_check_details      jsonb,
  frequency                text,
  preferred_day            integer,
  times                    text[],
  days                     integer[],
  notification_enabled     boolean default true,
  time_sensitive           boolean default true,
  notes                    text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  deleted_at               timestamptz,
  medical_care_schedule    jsonb,
  medical_care_details     jsonb,
  wellness_check_schedule  jsonb,
  vet_appointment_schedule jsonb
);

create index if not exists idx_routines_is_active on routines (is_active);
create index if not exists idx_routines_owner_user_id on routines (owner_user_id);
create index if not exists idx_routines_pet_id on routines (pet_id);
create index if not exists idx_routines_routine_type on routines (routine_type);
