-- 0007_social_walks.sql
-- Scheduled group walks + join requests. Matches supabase_schema.sql exactly.
-- visibility defaults to 'private'; join-request uniqueness is a PARTIAL index (status='pending').

create table if not exists social_walks (
  id                       integer generated by default as identity primary key,
  routine_id               integer references routines(id) on delete set null,
  routine_walk_index       integer,
  pet_id                   integer not null references pets(id) on delete cascade,
  owner_user_id            integer not null references user_profiles(id) on delete cascade,
  walk_name                text not null,
  scheduled_at             timestamptz not null,
  duration_minutes         integer,
  pace                     text,
  visibility               text not null default 'private',
  meeting_area             text,
  meeting_location_details text,
  max_pets                 integer default 4,
  approval_required        boolean default true,
  status                   text not null default 'scheduled',
  notes_for_guests         text,
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  constraint social_walks_status_check check (status = any (array['scheduled','cancelled','completed']::text[])),
  constraint social_walks_visibility_check check (visibility = any (array['private','friends_only','nearby_pets']::text[]))
);

create index if not exists idx_social_walks_owner_user_id on social_walks (owner_user_id);
create index if not exists idx_social_walks_pet_id on social_walks (pet_id);
create index if not exists idx_social_walks_scheduled_at on social_walks (scheduled_at);
create index if not exists idx_social_walks_status on social_walks (status);
create index if not exists idx_social_walks_visibility on social_walks (visibility);

create table if not exists social_walk_join_requests (
  id                integer generated by default as identity primary key,
  social_walk_id    integer not null references social_walks(id) on delete cascade,
  requester_user_id integer not null references user_profiles(id) on delete cascade,
  requester_pet_id  integer not null references pets(id) on delete cascade,
  status            text not null default 'pending',
  message           text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint social_walk_join_requests_status_check check (status = any (array['pending','approved','declined','cancelled']::text[]))
);

create index if not exists idx_social_walk_join_requests_requester_user_id on social_walk_join_requests (requester_user_id);
create index if not exists idx_social_walk_join_requests_social_walk_id on social_walk_join_requests (social_walk_id);
create index if not exists idx_social_walk_join_requests_status on social_walk_join_requests (status);
create unique index if not exists idx_social_walk_join_requests_unique_pending on social_walk_join_requests (social_walk_id, requester_user_id, requester_pet_id) where (status = 'pending');
