-- 0008_health_logs.sql
-- 12 health tracking tables. Matches supabase_schema.sql exactly.
-- Note: health_medical_care_logs FKs are plain references (NO on-delete action), unlike the
-- other logs which cascade; medical_care_item_id is text; health_wellness_logs.routine_id is
-- ON DELETE SET NULL. CHECK constraints on body_area / event_type / check_type are preserved.

create table if not exists health_food_logs (
  id                   integer generated by default as identity primary key,
  pet_id               integer not null references pets(id) on delete cascade,
  owner_user_id        integer not null references user_profiles(id) on delete cascade,
  logged_at            timestamptz not null default now(),
  meal_type            text,
  food_name            text,
  amount               text,
  appetite             text,
  finished_meal        boolean,
  water_intake         text,
  vomiting_or_reaction boolean,
  notes                text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index if not exists idx_health_food_logs_logged_at on health_food_logs (logged_at desc);
create index if not exists idx_health_food_logs_owner_user_id on health_food_logs (owner_user_id);
create index if not exists idx_health_food_logs_pet_id on health_food_logs (pet_id);

create table if not exists health_general_checks (
  id              integer generated by default as identity primary key,
  pet_id          integer not null references pets(id) on delete cascade,
  owner_user_id   integer not null references user_profiles(id) on delete cascade,
  logged_at       timestamptz not null default now(),
  eyes_status     text,
  ears_status     text,
  teeth_status    text,
  skin_fur_status text,
  paws_status     text,
  face_status     text,
  mood            text,
  energy          text,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index if not exists idx_health_general_checks_logged_at on health_general_checks (logged_at desc);
create index if not exists idx_health_general_checks_owner_user_id on health_general_checks (owner_user_id);
create index if not exists idx_health_general_checks_pet_id on health_general_checks (pet_id);

create table if not exists health_medical_care_logs (
  id                   integer generated by default as identity primary key,
  pet_id               integer not null references pets(id),
  owner_user_id        integer not null references user_profiles(id),
  routine_id           integer references routines(id),
  medical_care_item_id text,
  care_type            text,
  name                 text,
  dose                 text,
  given_at             timestamptz not null default now(),
  status               text not null,
  notes                text,
  reaction_or_issue    jsonb,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index if not exists idx_mcl_owner on health_medical_care_logs (owner_user_id);
create index if not exists idx_mcl_pet_given on health_medical_care_logs (pet_id, given_at desc);

create table if not exists health_mobility_logs (
  id                           integer generated by default as identity primary key,
  pet_id                       integer not null references pets(id) on delete cascade,
  owner_user_id                integer not null references user_profiles(id) on delete cascade,
  logged_at                    timestamptz not null default now(),
  limping                      boolean default false,
  stiffness                    boolean default false,
  difficulty_standing          boolean default false,
  difficulty_stairs_or_jumping boolean default false,
  pain_signs                   boolean default false,
  notes                        text,
  created_at                   timestamptz not null default now(),
  updated_at                   timestamptz not null default now()
);
create index if not exists idx_health_mobility_logs_logged_at on health_mobility_logs (logged_at desc);
create index if not exists idx_health_mobility_logs_owner_user_id on health_mobility_logs (owner_user_id);
create index if not exists idx_health_mobility_logs_pet_id on health_mobility_logs (pet_id);

create table if not exists health_pee_logs (
  id                integer generated by default as identity primary key,
  pet_id            integer not null references pets(id) on delete cascade,
  owner_user_id     integer not null references user_profiles(id) on delete cascade,
  logged_at         timestamptz not null default now(),
  frequency         text,
  volume            text,
  color             text,
  accident_in_house boolean default false,
  difficulty_peeing boolean default false,
  pain_or_crying    boolean default false,
  blood_visible     boolean default false,
  increased_thirst  boolean default false,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists idx_health_pee_logs_logged_at on health_pee_logs (logged_at desc);
create index if not exists idx_health_pee_logs_owner_user_id on health_pee_logs (owner_user_id);
create index if not exists idx_health_pee_logs_pet_id on health_pee_logs (pet_id);

create table if not exists health_photo_checks (
  id                      integer generated by default as identity primary key,
  pet_id                  integer not null references pets(id) on delete cascade,
  owner_user_id           integer not null references user_profiles(id) on delete cascade,
  body_area               text not null,
  image_url               text not null,
  notes                   text,
  included_in_vet_summary boolean default false,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),
  constraint health_photo_checks_body_area_check check (body_area = any (array['paws','ears','eyes','teeth','skin_fur','face','full_body','other']::text[]))
);
create index if not exists idx_health_photo_checks_body_area on health_photo_checks (body_area);
create index if not exists idx_health_photo_checks_created_at on health_photo_checks (created_at desc);
create index if not exists idx_health_photo_checks_owner_user_id on health_photo_checks (owner_user_id);
create index if not exists idx_health_photo_checks_pet_id on health_photo_checks (pet_id);

create table if not exists health_poo_logs (
  id                integer generated by default as identity primary key,
  pet_id            integer not null references pets(id) on delete cascade,
  owner_user_id     integer not null references user_profiles(id) on delete cascade,
  logged_at         timestamptz not null default now(),
  amount            text,
  shape             text,
  color             text,
  blood             boolean default false,
  mucus             boolean default false,
  straining         boolean default false,
  accident_in_house boolean default false,
  photo_url         text,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists idx_health_poo_logs_logged_at on health_poo_logs (logged_at desc);
create index if not exists idx_health_poo_logs_owner_user_id on health_poo_logs (owner_user_id);
create index if not exists idx_health_poo_logs_pet_id on health_poo_logs (pet_id);

create table if not exists health_timeline_events (
  id                integer generated by default as identity primary key,
  pet_id            integer not null references pets(id) on delete cascade,
  owner_user_id     integer not null references user_profiles(id) on delete cascade,
  event_type        text not null,
  related_record_id integer not null,
  title             text not null,
  summary           text,
  event_time        timestamptz not null,
  created_at        timestamptz not null default now(),
  constraint health_timeline_events_event_type_check check (event_type = any (array['food','poo','pee','vomit','walk','mobility','general_check','photo_check','weight']::text[]))
);
create index if not exists idx_health_timeline_events_event_time on health_timeline_events (event_time desc);
create index if not exists idx_health_timeline_events_event_type on health_timeline_events (event_type);
create index if not exists idx_health_timeline_events_owner_user_id on health_timeline_events (owner_user_id);
create index if not exists idx_health_timeline_events_pet_id on health_timeline_events (pet_id);

create table if not exists health_vomit_logs (
  id                 integer generated by default as identity primary key,
  pet_id             integer not null references pets(id) on delete cascade,
  owner_user_id      integer not null references user_profiles(id) on delete cascade,
  logged_at          timestamptz not null default now(),
  number_of_episodes integer default 1,
  appearance         text,
  relation_to_food   text,
  appetite_after     text,
  energy             text,
  diarrhea_present   boolean default false,
  photo_url          text,
  notes              text,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index if not exists idx_health_vomit_logs_logged_at on health_vomit_logs (logged_at desc);
create index if not exists idx_health_vomit_logs_owner_user_id on health_vomit_logs (owner_user_id);
create index if not exists idx_health_vomit_logs_pet_id on health_vomit_logs (pet_id);

create table if not exists health_walk_logs (
  id                integer generated by default as identity primary key,
  pet_id            integer not null references pets(id) on delete cascade,
  owner_user_id     integer not null references user_profiles(id) on delete cascade,
  start_time        timestamptz not null default now(),
  duration_minutes  integer,
  distance          numeric(10,2),
  distance_unit     text default 'miles',
  pace              text,
  energy_after      text,
  potty_events      jsonb,
  route_or_location text,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  average_speed     numeric(5,2),
  steps             integer,
  source            text default 'manual',
  source_device     text
);
create index if not exists idx_health_walk_logs_owner_user_id on health_walk_logs (owner_user_id);
create index if not exists idx_health_walk_logs_pet_id on health_walk_logs (pet_id);
create index if not exists idx_health_walk_logs_start_time on health_walk_logs (start_time desc);

create table if not exists health_weight_logs (
  id                  integer generated by default as identity primary key,
  pet_id              integer not null references pets(id) on delete cascade,
  owner_user_id       integer not null references user_profiles(id) on delete cascade,
  logged_at           timestamptz not null default now(),
  weight              numeric(5,2) not null,
  weight_unit         text default 'lbs',
  body_shape_estimate text,
  photo_url           text,
  notes               text,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index if not exists idx_health_weight_logs_logged_at on health_weight_logs (logged_at desc);
create index if not exists idx_health_weight_logs_owner_user_id on health_weight_logs (owner_user_id);
create index if not exists idx_health_weight_logs_pet_id on health_weight_logs (pet_id);

create table if not exists health_wellness_logs (
  id                        integer generated by default as identity primary key,
  pet_id                    integer not null references pets(id) on delete cascade,
  owner_user_id             integer not null references user_profiles(id) on delete cascade,
  routine_id                integer references routines(id) on delete set null,
  wellness_check_item_index integer,
  check_type                text not null,
  logged_at                 timestamptz not null default now(),
  values_json               jsonb,
  notes                     text,
  image_url                 text,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  constraint health_wellness_logs_check_type_check check (check_type = any (array['body_condition','mobility','mood_energy','skin_coat','appetite_hydration','custom']::text[]))
);
create index if not exists idx_wellness_logs_check_type on health_wellness_logs (check_type);
create index if not exists idx_wellness_logs_logged_at on health_wellness_logs (logged_at desc);
create index if not exists idx_wellness_logs_owner_user_id on health_wellness_logs (owner_user_id);
create index if not exists idx_wellness_logs_pet_id on health_wellness_logs (pet_id);
