-- 0011_reminder_dismissals.sql
-- Durable "skip / dismiss" for overdue reminder instances.
--
-- Today's Overdue list (Ticket 8) surfaces past-due reminders for the persistent
-- types (wellness / medical care / photo check / vet appointment). "Acting on" an
-- item — completing/logging it — is already DB-derivable from the existing log
-- tables. The OTHER way to clear an item is to skip/dismiss it, and that signal had
-- no home: the reminders store is in-memory only, so a skip would reappear after an
-- app restart. This table records a dismissal per scheduled instance so it survives
-- restart and is reconciled on load alongside the log-derived "resolved" set.
--
-- instance_key is the reminder's deterministic id (e.g. reminder_<routine>_<item>_<date>
-- or vet_apt_<id>) — stable per scheduled instance, so the UNIQUE makes a repeat
-- dismissal idempotent. routine_id is nullable because vet-appointment reminders
-- come from vet_appointments, not a routine. Every row is scoped by
-- owner_user_id (= user_profiles.id) + pet_id like every other owned table.
--
-- Idempotent: create-if-not-exists throughout, safe to re-run. Apply to the live
-- Supabase database the app is pointed at (manual step, like 0010).

create table if not exists reminder_dismissals (
  id              integer generated by default as identity primary key,
  pet_id          integer not null references pets(id) on delete cascade,
  owner_user_id   integer not null references user_profiles(id) on delete cascade,
  routine_id      integer references routines(id) on delete set null,
  reminder_type   text not null,
  instance_key    text not null,
  scheduled_date  date,
  dismissed_at    timestamptz not null default now(),
  created_at      timestamptz not null default now()
);

create unique index if not exists idx_reminder_dismissals_unique
  on reminder_dismissals (owner_user_id, pet_id, instance_key);
create index if not exists idx_reminder_dismissals_pet_id
  on reminder_dismissals (pet_id);
create index if not exists idx_reminder_dismissals_owner_user_id
  on reminder_dismissals (owner_user_id);
