-- 0012_pet_follows.sql
-- One-directional pet follows (NOT pet_friendships; that table is untouched).
-- A pet follows another pet instantly; followers/following counts derive from
-- this table. Mirrors 0004_social.sql's id / created_at conventions.

create table if not exists pet_follows (
  id              integer generated by default as identity primary key,
  follower_pet_id integer not null references pets(id) on delete cascade,
  followed_pet_id integer not null references pets(id) on delete cascade,
  created_at      timestamptz not null default now(),
  constraint pet_follows_follower_followed_key unique (follower_pet_id, followed_pet_id),
  constraint pet_follows_no_self_follow check (follower_pet_id <> followed_pet_id)
);

create index if not exists idx_pet_follows_followed_pet_id on pet_follows (followed_pet_id);
create index if not exists idx_pet_follows_follower_pet_id on pet_follows (follower_pet_id);
