-- 0014_providers.sql
-- Shared provider spine (docs/provider-design.md §2): the entity-owned business side.
-- Schema only — no API, no UI. Does NOT touch consent tables (care_access_*) or
-- vet_appointments (tickets 0015 / 0016).
--
-- Identity convention: every user reference is user_profiles(id), NEVER auth_users.
-- providers.owner_user_profile_id is the account that owns the entity; staff link in via
-- provider_staff. Matches supabase_schema.sql (addendum block) exactly.

create table if not exists providers (
  id                    integer generated by default as identity primary key,
  owner_user_profile_id integer not null references user_profiles(id) on delete cascade,
  provider_type         text not null,
  name                  text not null,
  slug                  text not null,
  bio                   text,
  logo_url              text,
  status                text not null default 'draft',
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  constraint providers_slug_key unique (slug),
  constraint providers_status_check check (status = any (array['draft','published']::text[]))
);

create index if not exists idx_providers_owner_user_profile_id on providers (owner_user_profile_id);

create table if not exists provider_locations (
  id          integer generated by default as identity primary key,
  provider_id integer not null references providers(id) on delete cascade,
  name        text,
  address     text,
  lat         numeric(9,6),
  lng         numeric(9,6),
  hours_json  jsonb,
  phone       text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists idx_provider_locations_provider_id on provider_locations (provider_id);

create table if not exists provider_staff (
  id              integer generated by default as identity primary key,
  provider_id     integer not null references providers(id) on delete cascade,
  user_profile_id integer not null references user_profiles(id) on delete cascade,
  role            text not null,
  status          text not null default 'invited',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  constraint provider_staff_provider_user_key unique (provider_id, user_profile_id),
  constraint provider_staff_role_check check (role = any (array['owner','admin','staff','vet']::text[])),
  constraint provider_staff_status_check check (status = any (array['invited','active','removed']::text[]))
);

create index if not exists idx_provider_staff_provider_id on provider_staff (provider_id);
create index if not exists idx_provider_staff_user_profile_id on provider_staff (user_profile_id);

create table if not exists provider_services (
  id           integer generated by default as identity primary key,
  provider_id  integer not null references providers(id) on delete cascade,
  name         text not null,
  description  text,
  duration_min integer,
  price_cents  integer,
  deposit_cents integer,
  active       boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists idx_provider_services_provider_id on provider_services (provider_id);

create table if not exists provider_reviews (
  id            integer generated by default as identity primary key,
  provider_id   integer not null references providers(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  pet_id        integer not null references pets(id) on delete cascade,
  rating        integer not null,
  body          text,
  created_at    timestamptz not null default now(),
  constraint provider_reviews_rating_check check (rating >= 1 and rating <= 5)
);

create index if not exists idx_provider_reviews_provider_id on provider_reviews (provider_id);
create index if not exists idx_provider_reviews_owner_user_id on provider_reviews (owner_user_id);
create index if not exists idx_provider_reviews_pet_id on provider_reviews (pet_id);
