-- 0015_care_access.sql
-- Consent cornerstone (docs/provider-design.md §2 "Consent" + §3 enforcement):
-- the per-(pet ↔ provider) grant that authorizes a provider to touch a pet's data,
-- and the append-only audit trail every access writes. Schema only — the
-- assertCareAccess helper + tests live in app code (web src/app/api/utils/).
--
-- Identity convention: every user reference is user_profiles(id), NEVER auth_users.
--   owner_user_id  = the granting authority (the owner who can revoke)
--   staff_user_id  = the provider_staff member who performed the access
-- booking_id is a plain nullable integer (no FK): the booking record is
-- vet_appointments, extended in 0016 — and later generalized to provider_bookings —
-- so we deliberately do not bind it to a table yet.
-- Matches supabase_schema.sql (addendum block) exactly.

create table if not exists care_access_grants (
  id            integer generated by default as identity primary key,
  pet_id        integer not null references pets(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  provider_id   integer not null references providers(id) on delete cascade,
  scopes        text[] not null default '{}',
  status        text not null default 'pending',
  requested_by  text not null,
  booking_id    integer,
  granted_at    timestamptz,
  expires_at    timestamptz,
  revoked_at    timestamptz,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint care_access_grants_status_check check (status = any (array['pending','active','revoked','expired']::text[])),
  constraint care_access_grants_requested_by_check check (requested_by = any (array['owner','provider']::text[]))
);

create index if not exists idx_care_access_grants_provider_pet_status
  on care_access_grants (provider_id, pet_id, status);
create index if not exists idx_care_access_grants_owner_status
  on care_access_grants (owner_user_id, status);

-- Append-only access log — one row per assertCareAccess success. No updated_at:
-- audit rows are never mutated. grant_id cascades so audits track their grant's life.
create table if not exists care_access_audit (
  id            integer generated by default as identity primary key,
  grant_id      integer not null references care_access_grants(id) on delete cascade,
  staff_user_id integer not null references user_profiles(id) on delete cascade,
  action        text not null,
  resource      text,
  at            timestamptz not null default now(),
  constraint care_access_audit_action_check check (action = any (array['read','write']::text[]))
);

create index if not exists idx_care_access_audit_grant_id on care_access_audit (grant_id);
