-- 0016_vaccinations_and_booking.sql
-- Provider/Business side, docs/provider-design.md §2 "Vet-type reuse". Two changes:
--   1. NEW pet_vaccinations — owner-visible vaccination history. Closes the gap that
--      no vaccination table exists today. Soft-delete (deleted_at) matching vet_appointments.
--   2. Extend vet_appointments with nullable/defaulted booking columns so an owner
--      booking can be linked to a provider/location/service/staff. All additive:
--      existing owner-created rows and the reminder engine are untouched — the existing
--      status column and every other existing column are left exactly as-is.
-- Identity convention: every user reference is user_profiles(id), NEVER auth_users.
--   owner_user_id = the pet's owner (the WHERE owner_user_id = me scope on owner routes)
--   staff_user_id = the provider_staff member assigned to the booking
-- Schema only — pet_vaccinations is NOT wired into any route yet (that is ticket 8).
-- Matches supabase_schema.sql (addendum block) exactly.

create table if not exists pet_vaccinations (
  id                          integer generated by default as identity primary key,
  pet_id                      integer not null references pets(id) on delete cascade,
  owner_user_id               integer not null references user_profiles(id) on delete cascade,
  name                        text not null,
  date_given                  date,
  expires_on                  date,
  lot                         text,
  administered_by_provider_id integer references providers(id) on delete set null,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now(),
  deleted_at                  timestamptz
);

create index if not exists idx_pet_vaccinations_pet_id on pet_vaccinations (pet_id);
create index if not exists idx_pet_vaccinations_owner_user_id on pet_vaccinations (owner_user_id);

-- Extend vet_appointments with the vet-MVP booking link. All columns nullable
-- (source defaulted) so existing rows and the reminder engine see no change.
-- booking_status is DISTINCT from the existing status column (do not touch status).
-- Provider/location/service/staff are SET NULL on delete: a deleted provider must
-- not delete the owner's appointment, only unlink it.
alter table vet_appointments
  add column if not exists provider_id          integer references providers(id) on delete set null,
  add column if not exists provider_location_id integer references provider_locations(id) on delete set null,
  add column if not exists service_id           integer references provider_services(id) on delete set null,
  add column if not exists staff_user_id        integer references user_profiles(id) on delete set null,
  add column if not exists booking_status       text,
  add column if not exists source               text default 'owner';

-- Provider-side booking lookups filter by provider_id.
create index if not exists idx_vet_appointments_provider_id on vet_appointments (provider_id);
