-- 0027_provider_capabilities.sql
-- Phase 2 ticket 2.1 (docs/phase2-tickets/2.1-provider-capabilities.md,
-- docs/phase2-superapp-master-plan.md §1.5 CORE MODEL): a provider offers MANY
-- capabilities (a "vet shop" = consultation + vaccination + grooming + store). This
-- replaces providers.provider_type as the feature switch — from 2.1 on, EVERY service
-- module gates on a CAPABILITY, never on provider_type.
--
-- providers.provider_type is KEPT (do NOT drop) as an optional primary/display category;
-- it is no longer used to gate any feature.
--
-- Identity convention (unchanged): app.current_user_id carries user_profiles.id, NEVER
-- auth_users.id. Provider authorization is by provider_staff MEMBERSHIP, never by
-- user_profiles.role. Capability ≠ data access — consent (care_access_grants) and the
-- owner/medical RLS still gate pet data; a capability only unlocks a service MODULE.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as `pawpi_app` in the integration harness, NOT
-- applied to Supabase here. The migration is hand-applied to Supabase AFTER merge (see
-- the PR body's "MIGRATION TO APPLY TO SUPABASE" line). The pawpi_app DML/sequence
-- grants are already covered by 0019's ALTER DEFAULT PRIVILEGES (this table is created
-- by the owner role AFTER 0019, so future-table default privileges apply — exactly as
-- care_access_grants/0015 and the booking tables/0016 relied on); no per-table re-grant.

-- ─────────────────────────────────────────────────────────────────────────────
-- Table. One row per (provider, capability). The allowed set is enforced at the DB
-- with a CHECK constraint (documented choice): it mirrors the providers status/role
-- CHECK style already in 0014, makes the invariant self-documenting in the schema, and
-- guarantees the set holds even for hand-applied SQL / future routes — while the route
-- layer ALSO validates so a bad value returns a clean 400 instead of a 500. The set:
--   vet, groomer, walker, daycare, sitter, trainer, shop, adoption, transport, pharmacy
-- (matches the service catalog in master-plan §1; add a value here + in the route's
-- ALLOWED_CAPABILITIES when a new service type ships).
create table if not exists provider_capabilities (
  id          integer generated by default as identity primary key,
  provider_id integer not null references providers(id) on delete cascade,
  capability  text not null,
  created_at  timestamptz not null default now(),
  constraint provider_capabilities_provider_capability_key unique (provider_id, capability),
  constraint provider_capabilities_capability_check check (
    capability = any (array[
      'vet','groomer','walker','daycare','sitter','trainer',
      'shop','adoption','transport','pharmacy'
    ]::text[])
  )
);

create index if not exists idx_provider_capabilities_provider_id
  on provider_capabilities (provider_id);
-- Discovery filters by capability (WHERE capability = $type), so index it too.
create index if not exists idx_provider_capabilities_capability
  on provider_capabilities (capability);

-- ─────────────────────────────────────────────────────────────────────────────
-- BACKFILL: one capability row per existing provider, derived from its current
-- provider_type. Only backfills provider_type values that are in the allowed set (so a
-- legacy/free-text provider_type that isn't a known capability is skipped rather than
-- violating the CHECK). Idempotent via the UNIQUE(provider_id, capability) + ON CONFLICT.
insert into provider_capabilities (provider_id, capability)
select p.id, p.provider_type
from providers p
where p.provider_type = any (array[
  'vet','groomer','walker','daycare','sitter','trainer',
  'shop','adoption','transport','pharmacy'
]::text[])
on conflict (provider_id, capability) do nothing;

-- ─────────────────────────────────────────────────────────────────────────────
-- DB helper. providerHasCapability(provider_id, capability) — the module-gating
-- predicate (used by requireProviderCapability in the route layer + reusable in SQL).
-- SECURITY DEFINER + pinned search_path + STABLE, matching 0019/0024's provider helpers:
-- it reads provider_capabilities, which is FORCE-RLS'd below, so running it as the owner
-- (DEFINER) keeps it from being re-filtered by that table's own SELECT policy (a real
-- capability must be visible to the gate regardless of the caller's identity scope) and
-- avoids policy recursion. EXECUTE granted to pawpi_app explicitly so a future
-- REVOKE … FROM PUBLIC is safe.
create or replace function provider_has_capability(p_provider_id integer, p_capability text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from provider_capabilities pc
    where pc.provider_id = p_provider_id
      and pc.capability = p_capability
  )
$$;

grant execute on function provider_has_capability(integer, text) to pawpi_app;

-- ─────────────────────────────────────────────────────────────────────────────
-- RLS — mirrors the providers policy shape (0024): a published provider's capabilities
-- are PUBLIC (any authed user, for discovery), draft providers' caps are visible to
-- active staff only; writes are owner|admin (app_is_provider_admin).
alter table provider_capabilities enable row level security;
alter table provider_capabilities force row level security;

-- SELECT: a capability of a PUBLISHED provider (discovery — the providers EXISTS runs
-- under providers' own SELECT RLS, where a published provider is visible to any authed
-- user, so no DEFINER helper is needed) OR active staff of the provider (management read
-- incl. a still-draft provider). Two-tier, same as provider_services/_locations.
drop policy if exists provider_capabilities_read on provider_capabilities;
create policy provider_capabilities_read on provider_capabilities
  for select
  using (
    app_is_active_staff_of(provider_id)
    or exists (
      select 1 from providers p
      where p.id = provider_id and p.status = 'published'
    )
  );

-- Writes (INSERT/UPDATE/DELETE): owner|admin only — the onboarding multi-select + the
-- add/remove endpoint. FOR ALL with the same admin predicate as USING/WITH CHECK; a
-- capability is added/removed (no in-place edit) but DELETE + INSERT are both admin-gated.
drop policy if exists provider_capabilities_admin_all on provider_capabilities;
create policy provider_capabilities_admin_all on provider_capabilities
  for all
  using (app_is_provider_admin(provider_id))
  with check (app_is_provider_admin(provider_id));
