-- 0029_payments_foundation.sql
-- Phase 2 ticket 2.3 (docs/phase2-tickets/2.3-payments-foundation.md,
-- docs/phase2-superapp-master-plan.md §3): the marketplace PAYMENTS foundation — the
-- money layer every monetized service reuses. Model = SPLIT PAYMENTS: an owner pays,
-- the platform keeps a commission, the provider gets a payout. Two rails:
-- MercadoPago (fiat, OAuth-per-provider split payments + Checkout + webhooks) and
-- Binance Pay (crypto, merchant QR/deeplink + webhook + USDT payout).
--
-- Identity convention (unchanged): app.current_user_id carries user_profiles.id, NEVER
-- auth_users.id. Owner data keys on owner_user_id = user_profiles.id; provider access is
-- by provider_staff MEMBERSHIP (active staff / admin), NEVER by user_profiles.role.
--
-- MONEY = STRICTEST (00-README): every table here ships ENABLE + FORCE RLS with strict
-- scoping. The split:
--   provider_payment_accounts — provider ADMIN only. Holds OAuth/account tokens; tokens
--                                are NEVER exposed to owners (no owner read branch at all).
--   orders                    — owner reads/writes their own orders; provider active-staff
--                                read orders FOR their provider. No owner can read another
--                                owner's order; no provider can read another provider's.
--   order_items               — visible to whoever can see the parent order (owner OR
--                                provider active-staff), via an EXISTS on orders' own RLS.
--   payments                  — the attempt/result ledger. Same visibility as the parent
--                                order. INSERT/UPDATE happen server-side (checkout + webhook
--                                reconciliation), gated to the order's owner or provider staff.
--   payouts                   — provider settlements: active staff of the provider read;
--                                admin writes. No owner branch (owners never see payouts).
--   subscriptions             — owner reads/writes their own; provider active-staff read.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as `pawpi_app` in the integration harness, NOT
-- applied to Supabase here. Hand-applied to Supabase AFTER merge (see the PR body's
-- "MIGRATION TO APPLY TO SUPABASE" line). Enabling FORCE RLS on prod now (privileged
-- owner connection, only identity-wrapped routes set app.current_user_id) would make
-- non-identity reads return zero rows. R3 already cut the route layer over to identity;
-- this table set joins the same model.
--
-- DML + sequence grants are ALREADY provided by 0019's blanket
-- `GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES` + ALTER DEFAULT PRIVILEGES: these
-- tables are created by the owner role AFTER 0019, so future-table default privileges
-- apply — exactly as care_access_grants (0015), booking tables (0016), and
-- provider_capabilities (0027) relied on. No per-table re-grant; the as-pawpi_app test
-- is the proof the grants suffice.
--
-- ⚠️ RECURSION: the policies below reuse 0019/0024's SECURITY DEFINER helpers
-- (current_app_user_id, app_is_active_staff_of, app_is_provider_admin) which read
-- provider_staff under DEFINER rights, so they bypass that table's FORCE RLS and never
-- recurse. orders is read by order_items / payments via plain EXISTS sub-selects that run
-- under orders' OWN RLS (a permissive sub-select that resolves the same owner/staff scope)
-- — orders does not in turn read order_items/payments, so there is no cycle.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. provider_payment_accounts — one row per (provider, rail). The per-provider rail
--    connection. Holds the OAuth/account token (MercadoPago user access token) or the
--    merchant handle (Binance). PROVIDER ADMIN ONLY: tokens are NEVER exposed to owners,
--    so there is deliberately NO owner read branch — a single FOR ALL admin policy.
create table if not exists provider_payment_accounts (
  id            integer generated by default as identity primary key,
  provider_id   integer not null references providers(id) on delete cascade,
  rail          text not null,
  -- The provider-scoped token/secret material. Encrypted-at-rest is a prod follow-up
  -- (documented in the PR); RLS already keeps it provider-admin-only at the row level.
  access_token  text,
  refresh_token text,
  -- Rail-specific public identifiers (MercadoPago user_id, Binance merchant id/handle).
  account_ref   text,
  -- Free-form rail metadata (scopes, token expiry, public_key) — never owner-visible.
  meta          jsonb,
  status        text not null default 'connected',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint provider_payment_accounts_provider_rail_key unique (provider_id, rail),
  constraint provider_payment_accounts_rail_check
    check (rail = any (array['mercadopago','binance']::text[])),
  constraint provider_payment_accounts_status_check
    check (status = any (array['connected','disconnected','error']::text[]))
);

create index if not exists idx_provider_payment_accounts_provider_id
  on provider_payment_accounts (provider_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. orders — the buyer-side purchase record. owner_user_id = user_profiles.id (the
--    payer); provider_id = the business being paid. kind tells which service produced it;
--    source_ref ties back to the originating row (a booking/appointment id, a cart id, an
--    adoption listing id) as text so any service can reference its own key shape.
create table if not exists orders (
  id            integer generated by default as identity primary key,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  provider_id   integer not null references providers(id) on delete cascade,
  kind          text not null,
  source_ref    text,
  amount_cents  integer not null,
  currency      text not null default 'ARS',
  status        text not null default 'pending',
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint orders_kind_check check (
    kind = any (array['booking','product','adoption_fee','donation','subscription']::text[])
  ),
  constraint orders_status_check check (
    status = any (array['pending','paid','cancelled','refunded','failed']::text[])
  ),
  constraint orders_amount_check check (amount_cents >= 0)
);

create index if not exists idx_orders_owner_user_id on orders (owner_user_id);
create index if not exists idx_orders_provider_id on orders (provider_id);

create table if not exists order_items (
  id           integer generated by default as identity primary key,
  order_id     integer not null references orders(id) on delete cascade,
  name         text not null,
  quantity     integer not null default 1,
  unit_cents   integer not null,
  -- product_ref ties a line to its catalog row (shop SKU) — text for the same reason as
  -- orders.source_ref. Nullable: a booking/donation order may have no catalog line.
  product_ref  text,
  created_at   timestamptz not null default now(),
  constraint order_items_quantity_check check (quantity >= 1),
  constraint order_items_unit_check check (unit_cents >= 0)
);

create index if not exists idx_order_items_order_id on order_items (order_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. payments — the attempt/result LEDGER. One row per charge attempt against an order.
--    external_id = the rail's payment/order id (for reconciliation); idempotency_key makes
--    a retried checkout safe (UNIQUE); commission_cents records the platform's split;
--    raw_status keeps the rail's verbatim status for audit/debugging.
create table if not exists payments (
  id               integer generated by default as identity primary key,
  order_id         integer not null references orders(id) on delete cascade,
  rail             text not null,
  external_id      text,
  idempotency_key  text,
  status           text not null default 'pending',
  amount_cents     integer not null,
  commission_cents integer not null default 0,
  raw_status       text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint payments_rail_check check (rail = any (array['mercadopago','binance']::text[])),
  constraint payments_status_check check (
    status = any (array['pending','approved','refunded','failed']::text[])
  ),
  constraint payments_amount_check check (amount_cents >= 0),
  constraint payments_idempotency_key unique (idempotency_key)
);

create index if not exists idx_payments_order_id on payments (order_id);
create index if not exists idx_payments_external_id on payments (external_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. payouts — provider settlements (what the platform pays out to a provider, net of
--    commission). Provider-scoped only — owners never see payouts.
create table if not exists payouts (
  id           integer generated by default as identity primary key,
  provider_id  integer not null references providers(id) on delete cascade,
  rail         text not null,
  amount_cents integer not null,
  status       text not null default 'pending',
  external_id  text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint payouts_rail_check check (rail = any (array['mercadopago','binance']::text[])),
  constraint payouts_status_check check (
    status = any (array['pending','paid','failed']::text[])
  ),
  constraint payouts_amount_check check (amount_cents >= 0)
);

create index if not exists idx_payouts_provider_id on payouts (provider_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 5. subscriptions — recurring billing (shop auto-reorder). owner_user_id pays;
--    provider_id is billed to; next_charge_at drives the scheduler.
create table if not exists subscriptions (
  id             integer generated by default as identity primary key,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  provider_id    integer not null references providers(id) on delete cascade,
  plan           text not null,
  status         text not null default 'active',
  next_charge_at timestamptz,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  constraint subscriptions_status_check check (
    status = any (array['active','paused','cancelled']::text[])
  )
);

create index if not exists idx_subscriptions_owner_user_id on subscriptions (owner_user_id);
create index if not exists idx_subscriptions_provider_id on subscriptions (provider_id);

-- ═════════════════════════════════════════════════════════════════════════════
-- RLS — money = strictest. Every table ENABLE + FORCE; deny-by-default; mirrors the
-- routes exactly (no wider).
-- ═════════════════════════════════════════════════════════════════════════════

-- 1. provider_payment_accounts — provider ADMIN only, FOR ALL. NO owner branch at all:
--    tokens must never be readable by owners. app_is_provider_admin (0024) is a DEFINER
--    helper over provider_staff, so it bypasses that table's RLS and never recurses.
alter table provider_payment_accounts enable row level security;
alter table provider_payment_accounts force row level security;

drop policy if exists provider_payment_accounts_admin_all on provider_payment_accounts;
create policy provider_payment_accounts_admin_all on provider_payment_accounts
  for all
  using (app_is_provider_admin(provider_id))
  with check (app_is_provider_admin(provider_id));

-- 2. orders — owner sees/owns their own orders; provider active-staff read orders for
--    their provider. Per-command so writes stay owner-only while the read widens to
--    provider staff (a provider must see incoming orders, but never create one for an owner).
alter table orders enable row level security;
alter table orders force row level security;

-- SELECT: the paying owner OR active staff of the provider being paid. No cross-leak:
-- another owner fails owner_user_id; another provider's staff fails app_is_active_staff_of.
drop policy if exists orders_select on orders;
create policy orders_select on orders
  for select
  using (
    owner_user_id = current_app_user_id()
    or app_is_active_staff_of(provider_id)
  );

-- INSERT/UPDATE/DELETE: owner only (checkout creates the order as the payer; status
-- transitions on the order happen server-side under the owner's identity OR via the
-- payment ledger). A provider cannot fabricate or mutate an owner's order row.
drop policy if exists orders_owner_write on orders;
create policy orders_owner_write on orders
  for insert
  with check (owner_user_id = current_app_user_id());

drop policy if exists orders_owner_update on orders;
create policy orders_owner_update on orders
  for update
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

drop policy if exists orders_owner_delete on orders;
create policy orders_owner_delete on orders
  for delete
  using (owner_user_id = current_app_user_id());

-- 3. order_items — visible to whoever can see the parent order. The EXISTS runs under
--    orders' OWN SELECT RLS (so it resolves owner-or-provider-staff scope without
--    duplicating the predicate); writes require the order to be the caller's (owner).
alter table order_items enable row level security;
alter table order_items force row level security;

drop policy if exists order_items_select on order_items;
create policy order_items_select on order_items
  for select
  using (
    exists (select 1 from orders o where o.id = order_id)
  );

-- Writes: only on an order the caller OWNS (the EXISTS resolves under orders' RLS, then
-- we additionally require owner_user_id = me so provider-staff can't write items even on
-- an order they can read).
drop policy if exists order_items_owner_write on order_items;
create policy order_items_owner_write on order_items
  for all
  using (
    exists (
      select 1 from orders o
      where o.id = order_id and o.owner_user_id = current_app_user_id()
    )
  )
  with check (
    exists (
      select 1 from orders o
      where o.id = order_id and o.owner_user_id = current_app_user_id()
    )
  );

-- 4. payments — the ledger. Same VISIBILITY as the parent order (owner OR provider
--    staff). Writes (checkout insert + webhook/refund status flips) require the parent
--    order to be visible to a payment-managing party: the owner (their own order) OR
--    active provider staff (webhook reconciliation + refunds run server-side, and the
--    routes carry provider-admin identity for refunds). The EXISTS on orders runs under
--    orders' RLS so it inherits the no-cross-leak guarantee.
alter table payments enable row level security;
alter table payments force row level security;

drop policy if exists payments_select on payments;
create policy payments_select on payments
  for select
  using (
    exists (select 1 from orders o where o.id = order_id)
  );

-- INSERT/UPDATE: the payment must hang off an order the caller can act on. For owner-
-- initiated checkout that is their own order; for provider-side reconciliation/refunds
-- that is an order for their provider (active staff). DELETE: none (a ledger is append-
-- only; refund is a status UPDATE, not a row delete) → denied by default under FORCE.
drop policy if exists payments_write on payments;
create policy payments_write on payments
  for insert
  with check (
    exists (
      select 1 from orders o
      where o.id = order_id
        and (o.owner_user_id = current_app_user_id()
             or app_is_active_staff_of(o.provider_id))
    )
  );

drop policy if exists payments_update on payments;
create policy payments_update on payments
  for update
  using (
    exists (
      select 1 from orders o
      where o.id = order_id
        and (o.owner_user_id = current_app_user_id()
             or app_is_active_staff_of(o.provider_id))
    )
  )
  with check (
    exists (
      select 1 from orders o
      where o.id = order_id
        and (o.owner_user_id = current_app_user_id()
             or app_is_active_staff_of(o.provider_id))
    )
  );

-- 5. payouts — provider-scoped ONLY. Active staff read; admin writes. No owner branch
--    (owners never see settlements). Two policies: a staff read + an admin write.
alter table payouts enable row level security;
alter table payouts force row level security;

drop policy if exists payouts_staff_read on payouts;
create policy payouts_staff_read on payouts
  for select
  using (app_is_active_staff_of(provider_id));

drop policy if exists payouts_admin_write on payouts;
create policy payouts_admin_write on payouts
  for all
  using (app_is_provider_admin(provider_id))
  with check (app_is_provider_admin(provider_id));

-- 6. subscriptions — owner sees/owns their own; provider active-staff read theirs.
alter table subscriptions enable row level security;
alter table subscriptions force row level security;

drop policy if exists subscriptions_select on subscriptions;
create policy subscriptions_select on subscriptions
  for select
  using (
    owner_user_id = current_app_user_id()
    or app_is_active_staff_of(provider_id)
  );

drop policy if exists subscriptions_owner_write on subscriptions;
create policy subscriptions_owner_write on subscriptions
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());
