-- 0031_chat_messaging.sql
-- Phase 2 ticket 2.5 (docs/phase2-tickets/2.5-chat-messaging.md,
-- docs/phase2-superapp-master-plan.md §2 item 4): owner ↔ provider 1:1 messaging.
-- Needed by walker/sitter/adoption/etc. (2.6+) which lean on a chat channel.
--
-- ════════════════════════════════════════════════════════════════════════════════
-- MODEL — two tables, PARTICIPANT-SCOPED RLS (the CRUX of this ticket).
-- ════════════════════════════════════════════════════════════════════════════════
--   message_threads  — one 1:1 conversation between a pet OWNER and a PROVIDER (its
--                      staff), optionally tied to a booking. last_message_at is the
--                      sort key for the inbox; created_at the open time.
--   messages         — the individual messages on a thread. sender_user_id is the
--                      author's user_profiles.id; body is the text; attachment_url is
--                      a nullable Supabase Storage URL (reuses the existing upload path
--                      — no new media infra). read_at is the per-message read stamp the
--                      unread-count + mark-read routes drive.
--
-- A thread + its messages are visible AND writable to EXACTLY two parties:
--   (a) the OWNER            — owner_user_id = current_app_user_id()
--   (b) the PROVIDER's STAFF — app_is_active_staff_of(provider_id) (active staff only)
-- NO ONE ELSE. A message's SENDER must itself be a participant (WITH CHECK), so a
-- participant can never post AS another user, and a non-participant can never post at
-- all. Removed staff lose access the instant their provider_staff row flips to
-- 'removed' (app_is_active_staff_of returns false) — proven in the harness.
--
-- Identity convention (unchanged): app.current_user_id carries user_profiles.id, NEVER
-- auth_users.id. owner_user_id = user_profiles.id (the pet's owner); sender_user_id =
-- the author's user_profiles.id. Provider access is by provider_staff MEMBERSHIP
-- (app_is_active_staff_of, 0023), never user_profiles.role.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as `pawpi_app` in the integration harness, NOT
-- applied to Supabase here. Hand-applied to Supabase AFTER merge (see the PR body's
-- "MIGRATION TO APPLY TO SUPABASE" line). DML + sequence grants for the two new tables
-- are ALREADY provided by 0019's blanket grant + ALTER DEFAULT PRIVILEGES (created by
-- the owner role AFTER 0019) — exactly as care_access_grants (0015), the booking
-- columns (0016), provider_capabilities (0027), the payment tables (0029) and
-- provider_availability (0030) relied on. No per-table re-grant; the as-pawpi_app test
-- is the proof the grants suffice.

-- ════════════════════════════════════════════════════════════════════════════════
-- 1. message_threads — one 1:1 owner↔provider conversation, optionally booking-tied.
-- ════════════════════════════════════════════════════════════════════════════════
-- A thread is UNIQUE per (owner, provider, booking) — at most one general thread per
-- owner↔provider pair (booking_id NULL) and at most one per booking. The partial unique
-- index below enforces the general-thread uniqueness (NULLs are distinct in a plain
-- UNIQUE, so the general case needs the COALESCE-free partial form); a separate full
-- unique covers booking-tied threads.
create table if not exists message_threads (
  id              integer generated by default as identity primary key,
  -- The pet OWNER side of the conversation (user_profiles.id). RLS owner branch.
  owner_user_id   integer not null references user_profiles(id) on delete cascade,
  -- The PROVIDER side. Its ACTIVE staff are the other participants. RLS staff branch.
  provider_id     integer not null references providers(id) on delete cascade,
  -- Optional booking this thread is about (a thread is usually scoped to a provider
  -- relationship / a booking). SET NULL on delete so removing a booking only unlinks.
  booking_id      integer references vet_appointments(id) on delete set null,
  created_at      timestamptz not null default now(),
  -- Sort key for the inbox; bumped on every new message by the post-message route.
  last_message_at timestamptz not null default now()
);

create index if not exists idx_message_threads_owner_user_id on message_threads (owner_user_id);
create index if not exists idx_message_threads_provider_id on message_threads (provider_id);
create index if not exists idx_message_threads_booking_id on message_threads (booking_id);
create index if not exists idx_message_threads_last_message_at on message_threads (last_message_at);

-- At most one GENERAL (no-booking) thread per owner↔provider pair. Partial index over
-- booking_id IS NULL so the booking-tied threads are not constrained by it.
create unique index if not exists idx_message_threads_unique_general
  on message_threads (owner_user_id, provider_id)
  where booking_id is null;

-- At most one thread per booking (a booking has exactly one conversation).
create unique index if not exists idx_message_threads_unique_booking
  on message_threads (booking_id)
  where booking_id is not null;

-- ════════════════════════════════════════════════════════════════════════════════
-- 2. messages — individual messages on a thread.
-- ════════════════════════════════════════════════════════════════════════════════
create table if not exists messages (
  id             integer generated by default as identity primary key,
  thread_id      integer not null references message_threads(id) on delete cascade,
  -- The author's user_profiles.id. Constrained by RLS WITH CHECK to be the caller AND
  -- a participant of the thread, so no one can post AS another user.
  sender_user_id integer not null references user_profiles(id) on delete cascade,
  body           text,
  -- Nullable Supabase Storage URL for an image attachment (reuses the upload path).
  attachment_url text,
  created_at     timestamptz not null default now(),
  -- Per-message read stamp. NULL = unread; set by the mark-read route for messages the
  -- caller received (sent by the OTHER side). Drives the unread count.
  read_at        timestamptz,
  -- A message must carry SOMETHING — text or an attachment (or both). Forbids an empty
  -- message row.
  constraint messages_content_check check (
    (body is not null and length(btrim(body)) > 0) or attachment_url is not null
  )
);

create index if not exists idx_messages_thread_id on messages (thread_id);
create index if not exists idx_messages_sender_user_id on messages (sender_user_id);
create index if not exists idx_messages_created_at on messages (created_at);

-- ════════════════════════════════════════════════════════════════════════════════
-- 3. RLS — message_threads. PARTICIPANT-SCOPED (the crux).
-- ════════════════════════════════════════════════════════════════════════════════
-- Visible AND writable to (a) the owner OR (b) active staff of the provider. No one
-- else. app_is_active_staff_of (0023) is a SECURITY DEFINER helper over provider_staff,
-- so it bypasses provider_staff's own RLS and never recurses. A FOR ALL policy covers
-- SELECT/INSERT/UPDATE/DELETE with the same participant predicate; WITH CHECK is the
-- same predicate so a participant cannot create/move a thread they aren't part of.
alter table message_threads enable row level security;
alter table message_threads force row level security;

drop policy if exists message_threads_participant_all on message_threads;
create policy message_threads_participant_all on message_threads
  for all
  using (
    owner_user_id = current_app_user_id()
    or app_is_active_staff_of(provider_id)
  )
  with check (
    owner_user_id = current_app_user_id()
    or app_is_active_staff_of(provider_id)
  );

-- ════════════════════════════════════════════════════════════════════════════════
-- 4. RLS — messages. PARTICIPANT-SCOPED via the parent thread + sender = caller.
-- ════════════════════════════════════════════════════════════════════════════════
-- A message is reachable when the CALLER is a participant of its thread (owner of the
-- thread, or active staff of the thread's provider). Membership is read through a
-- SECURITY DEFINER helper (app_is_thread_participant) so the messages policy does not
-- itself re-run message_threads' RLS (avoids the messages-policy → threads-policy →
-- helper recursion class and an under-count). SELECT/UPDATE/DELETE gate on participation;
-- INSERT additionally requires sender_user_id = current_app_user_id() — you may only
-- post AS yourself, and only into a thread you participate in.
alter table messages enable row level security;
alter table messages force row level security;

-- SECURITY DEFINER membership helper: is the current app user a participant of thread t?
-- Reads message_threads (FORCE-RLS'd above) + provider_staff (via app_is_active_staff_of),
-- so it MUST run as the owner (DEFINER) to bypass those policies — same pattern + reason
-- as 0019/0023/0024's helpers. STABLE + pinned search_path (DEFINER hijack guard).
-- EXECUTE granted to pawpi_app explicitly so a future REVOKE … FROM PUBLIC is safe.
create or replace function app_is_thread_participant(p_thread_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from message_threads t
    where t.id = p_thread_id
      and (
        t.owner_user_id = current_app_user_id()
        or app_is_active_staff_of(t.provider_id)
      )
  )
$$;

grant execute on function app_is_thread_participant(integer) to pawpi_app;

-- SELECT/UPDATE/DELETE: any participant of the thread. (UPDATE is the mark-read path;
-- DELETE is not exposed by a route but the policy keeps it participant-bound.)
drop policy if exists messages_participant_read on messages;
create policy messages_participant_read on messages
  for select
  using (app_is_thread_participant(thread_id));

drop policy if exists messages_participant_update on messages;
create policy messages_participant_update on messages
  for update
  using (app_is_thread_participant(thread_id))
  with check (app_is_thread_participant(thread_id));

drop policy if exists messages_participant_delete on messages;
create policy messages_participant_delete on messages
  for delete
  using (app_is_thread_participant(thread_id));

-- INSERT: the sender must BE the caller (post AS yourself only) AND a participant of the
-- thread. A non-participant cannot post; a participant cannot post AS another user.
drop policy if exists messages_sender_insert on messages;
create policy messages_sender_insert on messages
  for insert
  with check (
    sender_user_id = current_app_user_id()
    and app_is_thread_participant(thread_id)
  );
