-- 0040_telehealth.sql
-- Phase 2 ticket 2.18 (docs/phase2-tickets/2.18-telehealth.md): TELEHEALTH — a vet VIDEO
-- CONSULT as a new capability. The consult IS a normal booking (vet_appointments,
-- capability='telehealth') that is PAID (orders/payments, 2.3), COORDINATED over the existing
-- chat (0031), and whose clinical note is written to vet_notes via the EXISTING medical_write
-- path (consent-gated). The ONLY new thing telehealth needs is the live video session record.
--
-- ════════════════════════════════════════════════════════════════════════════════
-- WHAT THIS MIGRATION ADDS
-- ════════════════════════════════════════════════════════════════════════════════
--   1. Widen TWO capability CHECKs to include 'telehealth' (idempotent drop+add):
--        - provider_capabilities_capability_check (0027)
--        - vet_appointments_capability_check       (0030)
--      (mirrors the app-side ALLOWED_CAPABILITIES in providerAuth.js.)
--   2. ONE new table telehealth_sessions — the live/operational video-consult record,
--      PARTICIPANT-SCOPED exactly like walk_sessions (0033): the OWNER (FOR ALL) + the
--      ASSIGNED active provider staff (per-command). No third party reads a join link.
--
-- Capability ≠ data access: this session is participant-scoped, but reading/writing the
-- pet's medical record (the consult note → vet_notes) still requires the consent grant
-- (assertCareAccess 'medical_write'). The video room link is participant-only.
--
-- Identity convention (unchanged): app.current_user_id carries user_profiles.id.
-- owner_user_id = pets.owner_user_id; provider_id is the telehealth-capable vet; staff_user_id
-- is the assigned vet's user_profiles.id. Provider access is by active-staff MEMBERSHIP +
-- assignment, never user_profiles.role. app_is_active_staff_of (0023) is SECURITY DEFINER over
-- provider_staff, so the staff check bypasses that table's RLS and never recurses.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as `pawpi_app` in the integration harness, NOT applied
-- to Supabase here. Hand-applied AFTER merge (see the PR body). DML + sequence grants for the
-- new table are ALREADY provided by 0019's blanket GRANT + ALTER DEFAULT PRIVILEGES (the table
-- is created by the owner role AFTER 0019) — same pattern as walk_sessions (0033) et al.

-- ════════════════════════════════════════════════════════════════════════════════
-- 1. Widen the two capability CHECKs to include 'telehealth'.
-- ════════════════════════════════════════════════════════════════════════════════
alter table provider_capabilities
  drop constraint if exists provider_capabilities_capability_check;
alter table provider_capabilities
  add constraint provider_capabilities_capability_check
  check (
    capability = any (array[
      'vet','groomer','walker','daycare','sitter','trainer',
      'shop','adoption','transport','pharmacy','telehealth'
    ]::text[])
  );

alter table vet_appointments
  drop constraint if exists vet_appointments_capability_check;
alter table vet_appointments
  add constraint vet_appointments_capability_check
  check (
    capability = any (array[
      'vet','groomer','walker','daycare','sitter','trainer',
      'shop','adoption','transport','pharmacy','telehealth'
    ]::text[])
  );

-- ════════════════════════════════════════════════════════════════════════════════
-- 2. telehealth_sessions — one row per booked video consult (the live/operational record).
-- ════════════════════════════════════════════════════════════════════════════════
--   booking_id    — the booking this consult fulfils (vet_appointments id, ticket 2.4).
--                   Nullable + ON DELETE SET NULL: a removed booking only unlinks the session.
--   pet_id/owner_user_id/provider_id — the standard scoping triple. owner_user_id =
--                   pets.owner_user_id (the owner key), set by the route from the pet.
--   staff_user_id — the ASSIGNED vet's user_profiles.id (the participant on the provider side).
--                   Nullable + ON DELETE SET NULL: an unassigned session is provider-invisible
--                   until assigned (the owner still sees it via the owner branch).
--   room_ref      — the video vendor's room id / join url material (opaque; never owner-secret).
--   status        — scheduled → in_progress (first join) → ended | cancelled. CHECK-constrained.
--   started_at/ended_at — first-join / end stamps.
--   summary       — a short, owner-visible recap (the clinical note itself lives in vet_notes).
create table if not exists telehealth_sessions (
  id              integer generated by default as identity primary key,
  booking_id      integer references vet_appointments(id) on delete set null,
  pet_id          integer not null references pets(id) on delete cascade,
  owner_user_id   integer not null references user_profiles(id) on delete cascade,
  provider_id     integer not null references providers(id) on delete cascade,
  staff_user_id   integer references user_profiles(id) on delete set null,
  room_ref        text,
  status          text not null default 'scheduled'
                    check (status in ('scheduled', 'in_progress', 'ended', 'cancelled')),
  started_at      timestamptz,
  ended_at        timestamptz,
  summary         text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create index if not exists idx_telehealth_sessions_pet_id on telehealth_sessions (pet_id);
create index if not exists idx_telehealth_sessions_owner_user_id on telehealth_sessions (owner_user_id);
create index if not exists idx_telehealth_sessions_provider_id on telehealth_sessions (provider_id);
create index if not exists idx_telehealth_sessions_staff_user_id on telehealth_sessions (staff_user_id);
create index if not exists idx_telehealth_sessions_booking_id on telehealth_sessions (booking_id);

-- ════════════════════════════════════════════════════════════════════════════════
-- 3. RLS — telehealth_sessions. PARTICIPANT-SCOPED (mirror walk_sessions 0033).
-- ════════════════════════════════════════════════════════════════════════════════
-- Visible/writable to EXACTLY: (a) the OWNER (FOR ALL) and (b) the ASSIGNED active staff of
-- the provider (per-command). An outsider, another owner, and even another staffer of the SAME
-- provider all read ZERO — so a consult's join link never leaks to a non-participant.
alter table telehealth_sessions enable row level security;
alter table telehealth_sessions force row level security;

-- Owner: full control over their own pets' consult sessions (book/cancel/correct, read).
drop policy if exists telehealth_sessions_owner_all on telehealth_sessions;
create policy telehealth_sessions_owner_all on telehealth_sessions
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- Provider SELECT — the ASSIGNED vet reads their own session. staff_user_id = caller AND the
-- caller is active staff of the provider. A non-assigned staffer reads zero.
drop policy if exists telehealth_sessions_staff_read on telehealth_sessions;
create policy telehealth_sessions_staff_read on telehealth_sessions
  for select
  using (
    staff_user_id = current_app_user_id()
    and app_is_active_staff_of(provider_id)
  );

-- Provider INSERT — a vet creates the session they are assigned to (cannot assign it to
-- someone else, nor for a provider they aren't active staff of).
drop policy if exists telehealth_sessions_staff_insert on telehealth_sessions;
create policy telehealth_sessions_staff_insert on telehealth_sessions
  for insert
  with check (
    staff_user_id = current_app_user_id()
    and app_is_active_staff_of(provider_id)
  );

-- Provider UPDATE — the assigned vet updates their session (start/end). USING gates the
-- existing row; WITH CHECK stops re-assigning it away while editing.
drop policy if exists telehealth_sessions_staff_update on telehealth_sessions;
create policy telehealth_sessions_staff_update on telehealth_sessions
  for update
  using (
    staff_user_id = current_app_user_id()
    and app_is_active_staff_of(provider_id)
  )
  with check (
    staff_user_id = current_app_user_id()
    and app_is_active_staff_of(provider_id)
  );
