-- 0042_provider_posts.sql
-- Phase 2 ticket 2.22: the provider STOREFRONT. Two additive pieces:
--   1. provider_posts — a provider's feed of announcements/photos shown on the public
--      storefront (newest first), composed by the provider's active staff from the web
--      dashboard.
--   2. providers.cover_image_url — the storefront banner above the logo (additive column,
--      rides providers' existing any-authed-read / owner|admin-write policy from 0024).
--
-- RLS (provider_posts): ENABLE + FORCE, mirroring the provider_services published-read +
-- staff-write shape (0024) but keyed to active STAFF (not admin-only) for writes:
--   • provider_posts_staff_all  — active staff of the provider INSERT/UPDATE/DELETE (the
--     soft-delete sets deleted_at via UPDATE; the real DELETE is policied too).
--   • provider_posts_read       — active staff read ALL (manage, incl. drafts/deleted) OR
--     any authed user reads a PUBLISHED provider's NON-deleted posts (the storefront window).
-- Reuses the existing SECURITY DEFINER helper app_is_active_staff_of(provider_id); the
-- providers EXISTS runs under providers' own SELECT RLS (a published provider is visible),
-- so no new helper is needed. The completeness guard auto-discovers the new table
-- (ENABLE+FORCE + ≥1 policy → classified, not a gap).
--
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied
-- to Supabase AFTER merge (see the PR body / test-backlog ACTION 1). Idempotent.

create table if not exists provider_posts (
  id             integer generated by default as identity primary key,
  provider_id    integer not null references providers(id) on delete cascade,
  author_user_id integer references user_profiles(id) on delete set null,
  body           text,
  image_urls     text[] not null default '{}',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz
);

create index if not exists idx_provider_posts_provider_created
  on provider_posts (provider_id, created_at desc);

alter table providers add column if not exists cover_image_url text;

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table provider_posts enable row level security;
alter table provider_posts force row level security;

-- Writes (INSERT/UPDATE/DELETE) + the staff management read: any ACTIVE staff member.
drop policy if exists provider_posts_staff_all on provider_posts;
create policy provider_posts_staff_all on provider_posts
  for all
  using (app_is_active_staff_of(provider_id))
  with check (app_is_active_staff_of(provider_id));

-- SELECT: active staff see ALL of their provider's posts (incl. drafts/soft-deleted),
-- OR any authed user sees a PUBLISHED provider's NON-deleted posts (the storefront).
drop policy if exists provider_posts_read on provider_posts;
create policy provider_posts_read on provider_posts
  for select
  using (
    app_is_active_staff_of(provider_id)
    or (
      deleted_at is null
      and exists (
        select 1 from providers p
        where p.id = provider_id and p.status = 'published'
      )
    )
  );
