-- 0044_notifications.sql
-- Phase 2 ticket 2.26: real in-app notifications about activity on a user's content
-- (someone pawed their post, barked/commented, or followed their pet). Replaces the
-- mobile mock notifications. Reminder notifications stay local (the bell merges both).
--
-- notifications is OWNER-SCOPED: the RECIPIENT reads + marks their own rows. The actor
-- (a different user) must be able to CREATE a row targeting the recipient — which no
-- recipient-keyed WITH CHECK can allow — so inserts go exclusively through the
-- SECURITY DEFINER helper app_notify() (mirrors the consent/booking DEFINER pattern:
-- pinned search_path + GRANT EXECUTE to pawpi_app). There is NO INSERT policy: under
-- FORCE RLS that denies a direct pawpi_app insert, leaving app_notify the only path.
--
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied
-- to Supabase AFTER merge (see the PR body / test-backlog ACTION 1). Idempotent.

create table if not exists notifications (
  id                integer generated by default as identity primary key,
  recipient_user_id integer not null references user_profiles(id) on delete cascade,
  actor_user_id     integer references user_profiles(id) on delete set null,
  type              text not null,
  subject_ref       text,        -- post id / pet id as text, for tap-through
  body              text,
  read_at           timestamptz,
  created_at        timestamptz not null default now(),
  constraint notifications_type_check check (
    type = any (array['paw','bark','follow']::text[])
  )
);

create index if not exists idx_notifications_recipient_created
  on notifications (recipient_user_id, created_at desc);

-- ── RLS (owner = recipient) ──────────────────────────────────────────────────
alter table notifications enable row level security;
alter table notifications force row level security;

-- SELECT: the recipient reads ONLY their own notifications.
drop policy if exists notifications_select on notifications;
create policy notifications_select on notifications
  for select
  using (recipient_user_id = current_app_user_id());

-- UPDATE: the recipient marks their own as read (read_at). Both USING + WITH CHECK so a
-- row can't be re-pointed to someone else.
drop policy if exists notifications_update on notifications;
create policy notifications_update on notifications
  for update
  using (recipient_user_id = current_app_user_id())
  with check (recipient_user_id = current_app_user_id());

-- No INSERT / DELETE policy on purpose: inserts go through app_notify() (DEFINER);
-- there is no row-delete path.

-- ── DEFINER insert helper ────────────────────────────────────────────────────
-- The actor creates a notification for a DIFFERENT user (the recipient). Runs as the
-- function owner (a superuser/table owner) so it bypasses the recipient-keyed RLS that
-- no policy could satisfy. Never notifies a user about their own action (recipient =
-- actor → no-op). Returns the new id, or null when skipped. VOLATILE (it writes).
create or replace function app_notify(
  p_recipient integer,
  p_actor integer,
  p_type text,
  p_subject_ref text,
  p_body text
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_id integer;
begin
  if p_recipient is null or p_recipient = p_actor then
    return null;  -- never notify yourself for your own action
  end if;
  insert into notifications (recipient_user_id, actor_user_id, type, subject_ref, body)
  values (p_recipient, p_actor, p_type, p_subject_ref, p_body)
  returning id into new_id;
  return new_id;
end;
$$;

grant execute on function app_notify(integer, integer, text, text, text) to pawpi_app;
