-- 0045_owner_messaging.sql
-- Phase 2 ticket 2.27: real owner↔owner 1:1 messaging (social DMs). SEPARATE from the
-- owner↔provider chat (0031 message_threads/messages) — both coexist. Mirrors 0031's
-- participant-scoped RLS, but between TWO pet owners (user_profiles), not owner↔provider.
--
-- A pair has exactly ONE thread: participants are stored NORMALIZED as
-- (user_a_id < user_b_id) with a unique index, so (A,B) and (B,A) collapse to one row.
-- A thread + its messages are visible AND writable to EXACTLY the two participants
-- (user_a OR user_b = current_app_user_id()). A message's SENDER must be the caller AND
-- a participant (WITH CHECK), so no posting as someone else / into a thread you're not in.
--
-- Identity convention (unchanged): app.current_user_id carries user_profiles.id.
--
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied
-- to Supabase AFTER merge (see the PR body / test-backlog ACTION 1). DML/sequence grants
-- ride 0019's blanket grant + ALTER DEFAULT PRIVILEGES. Idempotent.

-- ── 1. dm_threads — one 1:1 owner↔owner conversation (normalized pair) ─────────
create table if not exists dm_threads (
  id              integer generated by default as identity primary key,
  user_a_id       integer not null references user_profiles(id) on delete cascade,
  user_b_id       integer not null references user_profiles(id) on delete cascade,
  created_at      timestamptz not null default now(),
  last_message_at timestamptz not null default now(),
  -- Normalization: a pair is stored once, with the smaller id first.
  constraint dm_threads_distinct check (user_a_id <> user_b_id),
  constraint dm_threads_ordered check (user_a_id < user_b_id)
);

create unique index if not exists idx_dm_threads_pair
  on dm_threads (user_a_id, user_b_id);
create index if not exists idx_dm_threads_user_a on dm_threads (user_a_id);
create index if not exists idx_dm_threads_user_b on dm_threads (user_b_id);
create index if not exists idx_dm_threads_last_message_at on dm_threads (last_message_at);

-- ── 2. dm_messages — individual messages on a DM thread ───────────────────────
create table if not exists dm_messages (
  id             integer generated by default as identity primary key,
  thread_id      integer not null references dm_threads(id) on delete cascade,
  sender_user_id integer not null references user_profiles(id) on delete cascade,
  body           text,
  image_url      text,
  read_at        timestamptz,
  created_at     timestamptz not null default now(),
  constraint dm_messages_content_check check (
    (body is not null and length(btrim(body)) > 0) or image_url is not null
  )
);

create index if not exists idx_dm_messages_thread_id on dm_messages (thread_id);
create index if not exists idx_dm_messages_sender_user_id on dm_messages (sender_user_id);
create index if not exists idx_dm_messages_created_at on dm_messages (created_at);

-- ── 3. RLS — dm_threads. PARTICIPANT-SCOPED (either of the two owners) ─────────
alter table dm_threads enable row level security;
alter table dm_threads force row level security;

drop policy if exists dm_threads_participant_all on dm_threads;
create policy dm_threads_participant_all on dm_threads
  for all
  using (
    user_a_id = current_app_user_id()
    or user_b_id = current_app_user_id()
  )
  with check (
    user_a_id = current_app_user_id()
    or user_b_id = current_app_user_id()
  );

-- ── 4. RLS — dm_messages. PARTICIPANT-SCOPED via the parent thread + sender=caller ──
alter table dm_messages enable row level security;
alter table dm_messages force row level security;

-- SECURITY DEFINER membership helper: is the current app user a participant of DM thread t?
-- Reads dm_threads (FORCE-RLS'd above), so it MUST run as the owner (DEFINER) to bypass
-- that policy — same pattern as 0031's app_is_thread_participant. STABLE + pinned search_path.
create or replace function app_is_dm_participant(p_thread_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from dm_threads t
    where t.id = p_thread_id
      and (
        t.user_a_id = current_app_user_id()
        or t.user_b_id = current_app_user_id()
      )
  )
$$;

grant execute on function app_is_dm_participant(integer) to pawpi_app;

drop policy if exists dm_messages_participant_read on dm_messages;
create policy dm_messages_participant_read on dm_messages
  for select
  using (app_is_dm_participant(thread_id));

drop policy if exists dm_messages_participant_update on dm_messages;
create policy dm_messages_participant_update on dm_messages
  for update
  using (app_is_dm_participant(thread_id))
  with check (app_is_dm_participant(thread_id));

drop policy if exists dm_messages_participant_delete on dm_messages;
create policy dm_messages_participant_delete on dm_messages
  for delete
  using (app_is_dm_participant(thread_id));

-- INSERT: the sender must BE the caller AND a participant of the thread.
drop policy if exists dm_messages_sender_insert on dm_messages;
create policy dm_messages_sender_insert on dm_messages
  for insert
  with check (
    sender_user_id = current_app_user_id()
    and app_is_dm_participant(thread_id)
  );
