-- 0046_walks_with_buddies.sql
-- Phase 2 ticket 2.43: schedule social WALK EVENTS on a map — PUBLIC (area-discoverable)
-- or PRIVATE (invite-only). EXTENDS social_walks (0007) — does NOT rebuild it.
--
-- Model (reuses the existing visibility CHECK — no widen):
--   • PUBLIC  → visibility = 'nearby_pets'  (area-discoverable; the existing discovery route
--               already selects this value). Now additionally filtered by a lat/lng bounding
--               box at the route layer (no PostGIS — a plain numeric range).
--   • PRIVATE → visibility = 'private'      (invite-only; visible ONLY to its owner + the
--               users explicitly invited via the new social_walk_invites table).
-- friends_only is unchanged.
--
-- New columns on social_walks: lat / lng / location_name (the dropped map pin + a place label).
-- New table social_walk_invites: owner-issued invitations to a PRIVATE walk (owner-initiated,
-- distinct from social_walk_join_requests which is requester-initiated / RSVP).
--
-- RLS (R-walks): a PRIVATE walk is visible only to its owner + invited users; a PUBLIC /
-- friends_only walk stays readable to any authed user (the route does the visibility/area
-- filtering, RLS only stops a non-invitee from ever reading a private walk). Writes stay
-- owner-scoped (the existing social_walks_owner_all FOR ALL policy is untouched). Invites are
-- readable by the invitee + the walk owner; writable (insert/delete) by the walk owner only.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied
-- to Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket
-- grant + ALTER DEFAULT PRIVILEGES; only the new helper functions need explicit EXECUTE grants.
-- Idempotent (IF NOT EXISTS / CREATE OR REPLACE / DROP POLICY IF EXISTS).

-- ── 1. social_walks — add the map pin (lat / lng) + a human place label ───────────
alter table social_walks add column if not exists lat           numeric;
alter table social_walks add column if not exists lng           numeric;
alter table social_walks add column if not exists location_name text;

-- Bounding-box discovery support (lat/lng range scan over discoverable walks).
create index if not exists idx_social_walks_lat_lng on social_walks (lat, lng);

-- ── 2. social_walk_invites — owner-issued invitations to a PRIVATE walk ───────────
create table if not exists social_walk_invites (
  id                  integer generated by default as identity primary key,
  social_walk_id      integer not null references social_walks(id) on delete cascade,
  invited_user_id     integer not null references user_profiles(id) on delete cascade,
  invited_by_user_id  integer not null references user_profiles(id) on delete cascade,
  status              text not null default 'invited',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint social_walk_invites_status_check
    check (status = any (array['invited','accepted','declined']::text[]))
);

create unique index if not exists idx_social_walk_invites_unique
  on social_walk_invites (social_walk_id, invited_user_id);
create index if not exists idx_social_walk_invites_walk    on social_walk_invites (social_walk_id);
create index if not exists idx_social_walk_invites_invitee on social_walk_invites (invited_user_id);

-- ── 3. SECURITY DEFINER helpers (break cross-table RLS recursion) ─────────────────
-- Both read a FORCE-RLS'd table, so they MUST run as the table owner (DEFINER) to bypass
-- that table's policy — same pattern as 0019's app_provider_has_grant / 0045's
-- app_is_dm_participant. STABLE + pinned search_path (closes the DEFINER hijack hole).

-- Does the current app user OWN walk w? Reads social_walks.owner_user_id directly. Used by
-- the invites policies (an invite is managed by the walk owner) WITHOUT re-entering the
-- social_walks SELECT policy (which itself calls app_is_walk_invitee → would recurse).
create or replace function app_user_owns_walk(p_walk_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from social_walks sw
    where sw.id = p_walk_id
      and sw.owner_user_id = current_app_user_id()
  )
$$;

-- Is the current app user INVITED to walk w? Reads social_walk_invites. Used by the
-- social_walks SELECT policy to reveal a private walk to its invitees WITHOUT re-entering
-- the invites SELECT policy (which calls app_user_owns_walk → would recurse).
create or replace function app_is_walk_invitee(p_walk_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from social_walk_invites i
    where i.social_walk_id = p_walk_id
      and i.invited_user_id = current_app_user_id()
  )
$$;

grant execute on function app_user_owns_walk(integer)  to pawpi_app;
grant execute on function app_is_walk_invitee(integer) to pawpi_app;

-- ── 4. social_walks — TIGHTEN the read policy to hide PRIVATE walks ────────────────
-- Previously (0026) any authed user could SELECT any walk. Tighten so a PRIVATE walk is
-- visible only to its owner or an invitee; PUBLIC ('nearby_pets') / friends_only stay
-- any-authed-readable (the route filters area/friendship). The owner FOR ALL write policy
-- (social_walks_owner_all, 0026) is UNTOUCHED — it already OR-grants the owner full access.
drop policy if exists social_walks_authed_read on social_walks;
create policy social_walks_authed_read on social_walks
  for select
  using (
    current_app_user_id() is not null
    and (
      visibility <> 'private'
      or owner_user_id = current_app_user_id()
      or app_is_walk_invitee(id)
    )
  );

-- ── 5. RLS — social_walk_invites. invitee-read + walk-owner manage ────────────────
alter table social_walk_invites enable row level security;
alter table social_walk_invites force row level security;

-- SELECT: the invited user reads their own invites; the walk owner reads all invites for
-- their walk (to render the invitee list).
drop policy if exists social_walk_invites_select on social_walk_invites;
create policy social_walk_invites_select on social_walk_invites
  for select
  using (
    invited_user_id = current_app_user_id()
    or app_user_owns_walk(social_walk_id)
  );

-- INSERT: the walk OWNER issues invites (invited_by = caller AND caller owns the walk).
drop policy if exists social_walk_invites_insert on social_walk_invites;
create policy social_walk_invites_insert on social_walk_invites
  for insert
  with check (
    invited_by_user_id = current_app_user_id()
    and app_user_owns_walk(social_walk_id)
  );

-- UPDATE: the INVITED user accepts/declines their own invite (status flip only). The walk
-- owner can also update (e.g. revoke status) — both branches pinned in USING + WITH CHECK.
drop policy if exists social_walk_invites_update on social_walk_invites;
create policy social_walk_invites_update on social_walk_invites
  for update
  using (
    invited_user_id = current_app_user_id()
    or app_user_owns_walk(social_walk_id)
  )
  with check (
    invited_user_id = current_app_user_id()
    or app_user_owns_walk(social_walk_id)
  );

-- DELETE: the walk OWNER revokes an invite.
drop policy if exists social_walk_invites_delete on social_walk_invites;
create policy social_walk_invites_delete on social_walk_invites
  for delete
  using (app_user_owns_walk(social_walk_id));
