-- 0047_community_forum.sql
-- Phase 2 ticket 2.44: a real Reddit-style community forum — categories → threads →
-- comments (flat with one level of reply) → votes. Replaces the mobile COMMUNITY_POSTS mock.
--
-- Tables:
--   forum_threads   — a post (author, category, title, body, image_urls[], score, soft-delete)
--   forum_comments  — a comment/reply on a thread (parent_comment_id nullable for replies)
--   forum_votes     — one (-1/+1) vote per user per target ('thread'|'comment'); UNIQUE per pair
--
-- RLS:
--   threads/comments — READ by any authed user (public community); INSERT by the author
--   (author = current_app_user_id()); UPDATE/DELETE by the AUTHOR only (edits + soft-delete).
--   votes — the voter reads ONLY their own vote rows. There is NO direct write policy: votes
--   are cast EXCLUSIVELY through the SECURITY DEFINER helper forum_vote(), which pins
--   user_id = current_app_user_id(), upserts/clears the vote, and recomputes the target's
--   denormalized score. The helper runs as the table owner so it bypasses the AUTHOR-only
--   thread/comment UPDATE policy (a non-author voter must be able to move a score) — the same
--   DEFINER-bypasses-FORCE-RLS pattern as 0044 app_notify / 0045 app_is_dm_participant.
--   comment_count is NOT denormalized — it is COUNTed on read (avoids a cross-author write).
--
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied to
-- Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant;
-- only the helper needs an explicit EXECUTE grant. Idempotent.

-- ── 1. forum_threads ──────────────────────────────────────────────────────────
create table if not exists forum_threads (
  id              integer generated by default as identity primary key,
  author_user_id  integer not null references user_profiles(id) on delete cascade,
  category        text not null default 'General',
  title           text not null,
  body            text,
  image_urls      text[] not null default '{}',
  score           integer not null default 0,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz,
  constraint forum_threads_title_check check (length(btrim(title)) > 0)
);

create index if not exists idx_forum_threads_category on forum_threads (category);
create index if not exists idx_forum_threads_created_at on forum_threads (created_at desc);
create index if not exists idx_forum_threads_score on forum_threads (score desc);
create index if not exists idx_forum_threads_author on forum_threads (author_user_id);

-- ── 2. forum_comments ─────────────────────────────────────────────────────────
create table if not exists forum_comments (
  id                integer generated by default as identity primary key,
  thread_id         integer not null references forum_threads(id) on delete cascade,
  author_user_id    integer not null references user_profiles(id) on delete cascade,
  parent_comment_id integer references forum_comments(id) on delete cascade,
  body              text not null,
  score             integer not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  deleted_at        timestamptz,
  constraint forum_comments_body_check check (length(btrim(body)) > 0)
);

create index if not exists idx_forum_comments_thread on forum_comments (thread_id, created_at);
create index if not exists idx_forum_comments_parent on forum_comments (parent_comment_id);
create index if not exists idx_forum_comments_author on forum_comments (author_user_id);

-- ── 3. forum_votes ────────────────────────────────────────────────────────────
create table if not exists forum_votes (
  id           integer generated by default as identity primary key,
  user_id      integer not null references user_profiles(id) on delete cascade,
  target_type  text not null,
  target_id    integer not null,
  value        smallint not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint forum_votes_target_type_check check (target_type = any (array['thread','comment']::text[])),
  constraint forum_votes_value_check check (value = any (array[-1, 1]::smallint[]))
);

create unique index if not exists idx_forum_votes_unique
  on forum_votes (user_id, target_type, target_id);
create index if not exists idx_forum_votes_target on forum_votes (target_type, target_id);

-- ── 4. RLS — forum_threads (any-authed read; author write) ─────────────────────
alter table forum_threads enable row level security;
alter table forum_threads force row level security;

drop policy if exists forum_threads_read on forum_threads;
create policy forum_threads_read on forum_threads
  for select
  using (current_app_user_id() is not null);

drop policy if exists forum_threads_insert on forum_threads;
create policy forum_threads_insert on forum_threads
  for insert
  with check (author_user_id = current_app_user_id());

drop policy if exists forum_threads_update on forum_threads;
create policy forum_threads_update on forum_threads
  for update
  using (author_user_id = current_app_user_id())
  with check (author_user_id = current_app_user_id());

drop policy if exists forum_threads_delete on forum_threads;
create policy forum_threads_delete on forum_threads
  for delete
  using (author_user_id = current_app_user_id());

-- ── 5. RLS — forum_comments (any-authed read; author write) ────────────────────
alter table forum_comments enable row level security;
alter table forum_comments force row level security;

drop policy if exists forum_comments_read on forum_comments;
create policy forum_comments_read on forum_comments
  for select
  using (current_app_user_id() is not null);

drop policy if exists forum_comments_insert on forum_comments;
create policy forum_comments_insert on forum_comments
  for insert
  with check (author_user_id = current_app_user_id());

drop policy if exists forum_comments_update on forum_comments;
create policy forum_comments_update on forum_comments
  for update
  using (author_user_id = current_app_user_id())
  with check (author_user_id = current_app_user_id());

drop policy if exists forum_comments_delete on forum_comments;
create policy forum_comments_delete on forum_comments
  for delete
  using (author_user_id = current_app_user_id());

-- ── 6. RLS — forum_votes (voter reads own; writes only via forum_vote DEFINER) ─
alter table forum_votes enable row level security;
alter table forum_votes force row level security;

-- SELECT: the voter reads ONLY their own votes (to render "did I upvote this?").
drop policy if exists forum_votes_select on forum_votes;
create policy forum_votes_select on forum_votes
  for select
  using (user_id = current_app_user_id());

-- No INSERT/UPDATE/DELETE policy on purpose: under FORCE RLS that denies direct pawpi_app
-- writes, leaving forum_vote() (DEFINER) the ONLY path — so a vote is always pinned to the
-- caller and the target's score stays consistent.

-- ── 7. forum_vote() — idempotent vote + score recompute (SECURITY DEFINER) ─────
-- p_value: 1 (up), -1 (down), 0 (clear my vote). Upserts the caller's single vote row for
-- the target, then sets the target's score = SUM(value) over its votes. Runs as the table
-- owner so it bypasses the author-only thread/comment UPDATE policy. Returns the new score.
create or replace function forum_vote(
  p_target_type text,
  p_target_id integer,
  p_value integer
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid integer := current_app_user_id();
  v_score integer;
begin
  if v_uid is null then
    raise exception 'no identity';
  end if;
  if p_target_type not in ('thread', 'comment') then
    raise exception 'invalid target_type';
  end if;
  if p_value not in (-1, 0, 1) then
    raise exception 'invalid value';
  end if;

  if p_value = 0 then
    delete from forum_votes
    where user_id = v_uid and target_type = p_target_type and target_id = p_target_id;
  else
    insert into forum_votes (user_id, target_type, target_id, value)
    values (v_uid, p_target_type, p_target_id, p_value::smallint)
    on conflict (user_id, target_type, target_id)
    do update set value = excluded.value, updated_at = now();
  end if;

  select coalesce(sum(value), 0)::int into v_score
  from forum_votes
  where target_type = p_target_type and target_id = p_target_id;

  if p_target_type = 'thread' then
    update forum_threads set score = v_score, updated_at = now() where id = p_target_id;
  else
    update forum_comments set score = v_score, updated_at = now() where id = p_target_id;
  end if;

  return v_score;
end;
$$;

grant execute on function forum_vote(text, integer, integer) to pawpi_app;
