-- 0048_training_progress_self.sql
-- Phase 2 ticket 2.45: the DIY self-training curriculum's per-pet PROGRESS. The curriculum
-- content (programs + sessions) ships as a static app content module — it is curated
-- material, NOT user data — so the only thing persisted here is which sessions an owner has
-- marked complete for a given pet.
--
-- DISTINCT from 2.10's provider training_programs/training_sessions/training_progress (those
-- are provider-side paid enrollments). This table is named training_progress_self so it can
-- never collide. program_key / session_key are the content module's stable string keys.
--
-- OWNER-SCOPED RLS: the owner reads + writes ONLY their own rows (owner_user_id =
-- current_app_user_id()); everyone else sees zero. UNIQUE(owner,pet,program,session) makes a
-- "mark complete" idempotent (upsert).
--
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied to
-- Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant.
-- Idempotent.

create table if not exists training_progress_self (
  id             integer generated by default as identity primary key,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  pet_id         integer not null references pets(id) on delete cascade,
  program_key    text not null,
  session_key    text not null,
  completed_at   timestamptz not null default now(),
  constraint training_progress_self_unique
    unique (owner_user_id, pet_id, program_key, session_key)
);

create index if not exists idx_training_progress_self_owner_pet
  on training_progress_self (owner_user_id, pet_id);

-- ── RLS — owner-scoped (FOR ALL) ──────────────────────────────────────────────
alter table training_progress_self enable row level security;
alter table training_progress_self force row level security;

drop policy if exists training_progress_self_owner_all on training_progress_self;
create policy training_progress_self_owner_all on training_progress_self
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());
