-- 0049_family_caregiver_sharing.sql
-- Phase 2 ticket 2.47 (EPIC E2): scoped, revocable pet access between PEOPLE — mirrors the
-- provider consent engine (care_access_grants, 0015/0023) but person↔person.
--
-- An owner shares a pet with another user as:
--   • FAMILY    — co-manage: READ + WRITE the pet's profile, routines, health logs, medical.
--   • CAREGIVER — temporary, scoped, auto-expiring READ of feeding/med instructions (routines)
--                 + emergency/medical info (pet_medical_profiles) + the pet profile. No writes.
-- The grantee accepts; access is scoped, audited, instantly revocable, and expiry-gated. The
-- OWNER remains the only one who can delete the pet or remove others (owner-only DELETE on
-- pets is never widened here).
--
-- Two read/write gates (both SECURITY DEFINER so they bypass the FORCE-RLS'd tables they read
-- — same pattern as 0019 app_provider_has_grant; no recursion):
--   app_user_has_pet_access(pet_id) — ANY active, unexpired grantee (family OR caregiver).
--   app_user_has_pet_family(pet_id) — an active, unexpired FAMILY grantee only.
-- Tables consult these ADDITIVELY (permissive policies OR with the existing owner FOR ALL), so
-- owner access is byte-for-byte unchanged and provider access (0020/0023) is untouched.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied
-- to Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket
-- grant; only the new functions need EXECUTE grants. Idempotent.

-- ── 1. pet_caregivers — the person↔person grant ────────────────────────────────
create table if not exists pet_caregivers (
  id               integer generated by default as identity primary key,
  pet_id           integer not null references pets(id) on delete cascade,
  owner_user_id    integer not null references user_profiles(id) on delete cascade,
  grantee_user_id  integer not null references user_profiles(id) on delete cascade,
  role             text not null,
  scopes           text[] not null default '{}',
  status           text not null default 'pending',
  expires_at       timestamptz,
  accepted_at      timestamptz,
  revoked_at       timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint pet_caregivers_role_check check (role = any (array['family','caregiver']::text[])),
  constraint pet_caregivers_status_check
    check (status = any (array['pending','active','revoked','declined','expired']::text[])),
  constraint pet_caregivers_not_self check (owner_user_id <> grantee_user_id)
);

-- One LIVE (pending/active) grant per (pet, grantee); a revoked/declined one can be re-issued.
create unique index if not exists idx_pet_caregivers_live_unique
  on pet_caregivers (pet_id, grantee_user_id)
  where status in ('pending', 'active');
create index if not exists idx_pet_caregivers_grantee_status on pet_caregivers (grantee_user_id, status);
create index if not exists idx_pet_caregivers_owner_status on pet_caregivers (owner_user_id, status);
create index if not exists idx_pet_caregivers_pet on pet_caregivers (pet_id);

-- ── 2. pet_caregiver_audit — append-only access/lifecycle trail ────────────────
-- owner_user_id is denormalized so the SELECT policy needs no cross-table join.
create table if not exists pet_caregiver_audit (
  id             integer generated by default as identity primary key,
  grant_id       integer not null references pet_caregivers(id) on delete cascade,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  actor_user_id  integer not null references user_profiles(id) on delete cascade,
  action         text not null,
  resource       text,
  at             timestamptz not null default now(),
  constraint pet_caregiver_audit_action_check
    check (action = any (array['grant','accept','decline','revoke','read','write']::text[]))
);

create index if not exists idx_pet_caregiver_audit_grant on pet_caregiver_audit (grant_id);
create index if not exists idx_pet_caregiver_audit_owner on pet_caregiver_audit (owner_user_id);

-- ── 3. SECURITY DEFINER helpers ────────────────────────────────────────────────
-- Does the caller OWN this pet? Reads pets.owner_user_id directly (bypassing pets RLS) so the
-- pet_caregivers INSERT check can verify ownership without recursing into pets' policies.
create or replace function app_owns_pet(p_pet_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from pets p
    where p.id = p_pet_id and p.owner_user_id = current_app_user_id()
  )
$$;

-- Does the caller hold an ACTIVE, UNEXPIRED grant (family OR caregiver) for this pet? The READ
-- gate for the shared set (pet profile, routines, medical profile). Reads pet_caregivers as the
-- owner (DEFINER) → bypasses its RLS, no recursion.
create or replace function app_user_has_pet_access(p_pet_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from pet_caregivers g
    where g.pet_id = p_pet_id
      and g.grantee_user_id = current_app_user_id()
      and g.status = 'active'
      and (g.expires_at is null or g.expires_at > now())
  )
$$;

-- Does the caller hold an ACTIVE, UNEXPIRED FAMILY grant for this pet? The WRITE gate (and the
-- read+write gate for the full health record).
create or replace function app_user_has_pet_family(p_pet_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from pet_caregivers g
    where g.pet_id = p_pet_id
      and g.grantee_user_id = current_app_user_id()
      and g.role = 'family'
      and g.status = 'active'
      and (g.expires_at is null or g.expires_at > now())
  )
$$;

-- Grantee accept/decline — pins grantee = caller, only flips a PENDING grant. DEFINER so the
-- grantee can update a row the owner-managed UPDATE policy reserves for the owner, WITHOUT
-- letting them touch role/scopes/owner. Writes an audit row. Returns the new status.
create or replace function respond_pet_caregiver(p_grant_id integer, p_accept boolean)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_uid integer := current_app_user_id();
  g pet_caregivers;
  v_status text;
begin
  if v_uid is null then
    raise exception 'no identity';
  end if;
  select * into g from pet_caregivers
    where id = p_grant_id and grantee_user_id = v_uid and status = 'pending';
  if not found then
    raise exception 'no pending grant for caller';
  end if;

  v_status := case when p_accept then 'active' else 'declined' end;
  update pet_caregivers
    set status = v_status,
        accepted_at = case when p_accept then now() else accepted_at end,
        updated_at = now()
    where id = p_grant_id;

  insert into pet_caregiver_audit (grant_id, owner_user_id, actor_user_id, action)
    values (p_grant_id, g.owner_user_id, v_uid, case when p_accept then 'accept' else 'decline' end);

  return v_status;
end;
$$;

grant execute on function app_owns_pet(integer) to pawpi_app;
grant execute on function app_user_has_pet_access(integer) to pawpi_app;
grant execute on function app_user_has_pet_family(integer) to pawpi_app;
grant execute on function respond_pet_caregiver(integer, boolean) to pawpi_app;

-- ── 4. RLS — pet_caregivers (owner manages; grantee sees grants naming them) ────
alter table pet_caregivers enable row level security;
alter table pet_caregivers force row level security;

-- SELECT: the owner (manages) OR the grantee (sees pets shared with them).
drop policy if exists pet_caregivers_select on pet_caregivers;
create policy pet_caregivers_select on pet_caregivers
  for select
  using (
    owner_user_id = current_app_user_id()
    or grantee_user_id = current_app_user_id()
  );

-- INSERT: the OWNER issues a grant for a pet they actually own.
drop policy if exists pet_caregivers_insert on pet_caregivers;
create policy pet_caregivers_insert on pet_caregivers
  for insert
  with check (
    owner_user_id = current_app_user_id()
    and app_owns_pet(pet_id)
  );

-- UPDATE: the OWNER manages their grants (revoke/expiry). Grantee accept/decline goes through
-- respond_pet_caregiver() (DEFINER), NOT this policy — so a grantee can't change role/scopes.
drop policy if exists pet_caregivers_update on pet_caregivers;
create policy pet_caregivers_update on pet_caregivers
  for update
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- DELETE: the OWNER only.
drop policy if exists pet_caregivers_delete on pet_caregivers;
create policy pet_caregivers_delete on pet_caregivers
  for delete
  using (owner_user_id = current_app_user_id());

-- ── 5. RLS — pet_caregiver_audit (append-only; owner or actor reads) ───────────
alter table pet_caregiver_audit enable row level security;
alter table pet_caregiver_audit force row level security;

drop policy if exists pet_caregiver_audit_select on pet_caregiver_audit;
create policy pet_caregiver_audit_select on pet_caregiver_audit
  for select
  using (
    owner_user_id = current_app_user_id()
    or actor_user_id = current_app_user_id()
  );

-- INSERT: the actor logs their OWN access. No UPDATE/DELETE policy → append-only under FORCE.
drop policy if exists pet_caregiver_audit_insert on pet_caregiver_audit;
create policy pet_caregiver_audit_insert on pet_caregiver_audit
  for insert
  with check (actor_user_id = current_app_user_id());

-- ── 6. EXTEND the pet data tables' RLS — ADDITIVE person-access policies ────────
-- Permissive policies OR with the existing owner FOR ALL (and provider policies), so owner +
-- provider access is unchanged; we only WIDEN the named command for the grantee.

-- 6a. pets — any grantee READS the profile; FAMILY UPDATEs it. (Owner-only DELETE preserved:
--     no grantee DELETE policy.) The family UPDATE WITH CHECK forbids re-pointing owner_user_id
--     to the editor (no self-steal of the pet).
drop policy if exists pets_grantee_read on pets;
create policy pets_grantee_read on pets
  for select using (app_user_has_pet_access(id));

drop policy if exists pets_family_update on pets;
create policy pets_family_update on pets
  for update
  using (app_user_has_pet_family(id))
  with check (app_user_has_pet_family(id));

-- Ownership-transfer guard. RLS permissive policies OR their WITH CHECKs, so pets_owner_all's
-- WITH CHECK (owner_user_id = me) would otherwise ACCEPT a family editor re-pointing
-- owner_user_id to THEMSELVES (a takeover). A BEFORE UPDATE trigger sees OLD vs NEW and is not
-- subject to the policy OR: only the CURRENT owner may change owner_user_id. Owner edits that
-- don't touch the column, and family edits to profile fields, pass untouched.
create or replace function pets_guard_owner_transfer()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.owner_user_id is distinct from old.owner_user_id
     and old.owner_user_id is distinct from current_app_user_id() then
    raise exception 'only the pet owner can transfer ownership';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_pets_guard_owner_transfer on pets;
create trigger trg_pets_guard_owner_transfer
  before update on pets
  for each row execute function pets_guard_owner_transfer();

-- 6b. routines — feeding/med instructions: any grantee READS; FAMILY co-manages (write).
drop policy if exists routines_grantee_read on routines;
create policy routines_grantee_read on routines
  for select using (app_user_has_pet_access(pet_id));

drop policy if exists routines_family_write on routines;
create policy routines_family_write on routines
  for all
  using (app_user_has_pet_family(pet_id))
  with check (app_user_has_pet_family(pet_id));

-- 6c. pet_medical_profiles — emergency/med info: any grantee READS; FAMILY writes.
drop policy if exists pet_medical_profiles_grantee_read on pet_medical_profiles;
create policy pet_medical_profiles_grantee_read on pet_medical_profiles
  for select using (app_user_has_pet_access(pet_id));

drop policy if exists pet_medical_profiles_family_update on pet_medical_profiles;
create policy pet_medical_profiles_family_update on pet_medical_profiles
  for update
  using (app_user_has_pet_family(pet_id))
  with check (app_user_has_pet_family(pet_id));

-- 6d. The full HEALTH record (health logs + vet-record extras + reminder dismissals) —
--     FAMILY-only read+write (caregivers get NONE of these; their scope is feeding + emergency
--     above). One additive FOR ALL family policy per table, applied in a loop (mirrors 0022).
--     routines is handled in 6b (any-grantee read), so it is excluded here.
do $$
declare
  t text;
  family_tables text[] := array[
    'health_food_logs',
    'health_general_checks',
    'health_medical_care_logs',
    'health_mobility_logs',
    'health_pee_logs',
    'health_photo_checks',
    'health_poo_logs',
    'health_vomit_logs',
    'health_walk_logs',
    'health_weight_logs',
    'health_wellness_logs',
    'health_timeline_events',
    'pet_allergies',
    'pet_conditions',
    'pet_lab_results',
    'pet_surgeries',
    'vet_documents',
    'reminder_dismissals'
  ];
begin
  foreach t in array family_tables loop
    execute format('drop policy if exists %I on %I', t || '_family_all', t);
    execute format(
      'create policy %I on %I for all '
      || 'using (app_user_has_pet_family(pet_id)) '
      || 'with check (app_user_has_pet_family(pet_id))',
      t || '_family_all', t
    );
  end loop;
end
$$;
