-- 0050_lost_and_found.sql
-- Phase 2 ticket 2.48 (EPIC E3): a Lost & Found network. An owner flips a pet to LOST with a
-- last-seen map pin; the alert is visible to any authed user (a public alert); anyone can
-- report a SIGHTING that routes back to the owner; the owner RESOLVES (found), clearing it.
--
-- Reuses the 2.43 lat/lng + bounding-box approach (no PostGIS) and the 0044 notifications +
-- app_notify DEFINER helper (type set widened additively for 'lost_alert').
--
-- RLS:
--   lost_reports  — owner FOR ALL (activate/edit/resolve); any authed user READS an ACTIVE
--                   report (the public alert). A resolved report is visible only to its owner.
--   lost_sightings— a reporter INSERTs a sighting on an ACTIVE report (reporter = caller);
--                   SELECT by the report OWNER (all sightings on their report) OR the reporter
--                   (their own). Append-only (no update/delete). Cross-table checks go through
--                   SECURITY DEFINER helpers (bypass RLS → no recursion).
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied
-- to Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket
-- grant; only the new helpers need EXECUTE grants. Idempotent.

-- ── 1. lost_reports — one active "lost mode" record per pet ────────────────────
create table if not exists lost_reports (
  id              integer generated by default as identity primary key,
  pet_id          integer not null references pets(id) on delete cascade,
  owner_user_id   integer not null references user_profiles(id) on delete cascade,
  status          text not null default 'active',
  last_seen_lat   numeric,
  last_seen_lng   numeric,
  last_seen_area  text,
  notes           text,
  reward          text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  resolved_at     timestamptz,
  constraint lost_reports_status_check check (status = any (array['active','resolved']::text[]))
);

create index if not exists idx_lost_reports_status on lost_reports (status);
create index if not exists idx_lost_reports_owner on lost_reports (owner_user_id);
create index if not exists idx_lost_reports_pet on lost_reports (pet_id);
create index if not exists idx_lost_reports_lat_lng on lost_reports (last_seen_lat, last_seen_lng);
-- At most ONE active report per pet.
create unique index if not exists idx_lost_reports_one_active
  on lost_reports (pet_id) where status = 'active';

-- ── 2. lost_sightings — community sighting reports on a lost pet ────────────────
create table if not exists lost_sightings (
  id               integer generated by default as identity primary key,
  lost_report_id   integer not null references lost_reports(id) on delete cascade,
  reporter_user_id integer references user_profiles(id) on delete set null,
  lat              numeric,
  lng              numeric,
  note             text,
  photo_url        text,
  created_at       timestamptz not null default now()
);

create index if not exists idx_lost_sightings_report on lost_sightings (lost_report_id);
create index if not exists idx_lost_sightings_reporter on lost_sightings (reporter_user_id);

-- ── 3. SECURITY DEFINER helpers (cross-table reads, bypass RLS → no recursion) ──
create or replace function app_owns_lost_report(p_report_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from lost_reports r
    where r.id = p_report_id and r.owner_user_id = current_app_user_id()
  )
$$;

create or replace function app_lost_report_active(p_report_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from lost_reports r
    where r.id = p_report_id and r.status = 'active'
  )
$$;

grant execute on function app_owns_lost_report(integer) to pawpi_app;
grant execute on function app_lost_report_active(integer) to pawpi_app;

-- ── 4. RLS — lost_reports ──────────────────────────────────────────────────────
alter table lost_reports enable row level security;
alter table lost_reports force row level security;

-- Owner: full read/write (activate, edit, resolve).
drop policy if exists lost_reports_owner_all on lost_reports;
create policy lost_reports_owner_all on lost_reports
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- Any authed user READS an ACTIVE report (the public alert). Resolved reports stay owner-only
-- (the owner FOR ALL policy ORs in for them). SELECT-only → writes remain owner-scoped.
drop policy if exists lost_reports_active_read on lost_reports;
create policy lost_reports_active_read on lost_reports
  for select
  using (current_app_user_id() is not null and status = 'active');

-- ── 5. RLS — lost_sightings ────────────────────────────────────────────────────
alter table lost_sightings enable row level security;
alter table lost_sightings force row level security;

-- SELECT: the report owner sees ALL sightings on their report; a reporter sees their own.
drop policy if exists lost_sightings_select on lost_sightings;
create policy lost_sightings_select on lost_sightings
  for select
  using (
    reporter_user_id = current_app_user_id()
    or app_owns_lost_report(lost_report_id)
  );

-- INSERT: any authed user reports a sighting on an ACTIVE report; reporter = caller.
drop policy if exists lost_sightings_insert on lost_sightings;
create policy lost_sightings_insert on lost_sightings
  for insert
  with check (
    reporter_user_id = current_app_user_id()
    and app_lost_report_active(lost_report_id)
  );

-- No UPDATE/DELETE policy → sightings are append-only under FORCE RLS.

-- ── 6. Widen the notifications type CHECK additively for 'lost_alert' (0044) ────
-- Drop-if-exists then re-add (the established CHECK-widen pattern); existing values kept.
alter table notifications drop constraint if exists notifications_type_check;
alter table notifications add constraint notifications_type_check
  check (type = any (array['paw','bark','follow','lost_alert']::text[]));
