-- 0051_emergency_medical_card.sql
-- Phase 2 ticket 2.51 (Wave 6 HEADLINE): an Emergency Card + two PUBLIC surfaces for a pet's
-- life-saving info. Mostly an ASSEMBLY of existing owner-scoped sources (pet_medical_profiles,
-- pet_allergies, pet_conditions, pets) + the 0050 lost_reports + the 0044 notifications/app_notify
-- helper. The only genuinely new capability is letting a NON-APP person (an ER vet, or a stranger
-- who finds the dog) read the card with NO login — done through SECURITY DEFINER functions ONLY,
-- never a broad public SELECT policy.
--
-- Two public surfaces, deliberately different in what they expose:
--   • TAG (permanent token, printed on the collar): BASIC always-safe info only — photo, name,
--     species/breed, "this dog has a home", microchip #, lost status + reward, and a contact
--     CHANNEL. Medical is shown ONLY when the owner opts in (show_medical_on_tag, default OFF).
--   • MEDICAL LINK (revocable/expiring): the FULL card incl. allergies/conditions/notes — for a
--     vet. Owner sets scope (full|basic) + expiry, can revoke instantly.
--
-- RLS:
--   pet_emergency_cards / pet_emergency_share_links — ENABLE+FORCE, OWNER FOR ALL only. Everyone
--   else gets ZERO direct access. The public read is NOT an RLS hole: it goes through the DEFINER
--   functions below (pinned search_path, GRANT EXECUTE to pawpi_app), which whitelist columns and
--   enforce active/scope/expiry/revoke. Medical = strictest — leak NOTHING beyond the whitelist.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied to
-- Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant;
-- only the new public-read helpers need EXECUTE grants. Idempotent.

-- ── 1. pet_emergency_cards — one row per pet, lazily created on first open ──────
create table if not exists pet_emergency_cards (
  id                  integer generated by default as identity primary key,
  pet_id              integer not null references pets(id) on delete cascade,
  owner_user_id       integer not null references user_profiles(id) on delete cascade,
  tag_token           text not null,            -- permanent printed-QR token (stable forever)
  show_medical_on_tag boolean not null default false,
  contact_mode        text not null default 'relay',
  contact_value       text,
  blood_type          text,
  extra_notes         text,
  active              boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  constraint pet_emergency_cards_pet_id_key unique (pet_id),
  constraint pet_emergency_cards_tag_token_key unique (tag_token),
  constraint pet_emergency_cards_contact_mode_check
    check (contact_mode = any (array['relay','phone','email','none']::text[]))
);

create index if not exists idx_pet_emergency_cards_owner on pet_emergency_cards (owner_user_id);
create index if not exists idx_pet_emergency_cards_tag on pet_emergency_cards (tag_token);

-- ── 2. pet_emergency_share_links — revocable/expiring vet links ─────────────────
create table if not exists pet_emergency_share_links (
  id            integer generated by default as identity primary key,
  pet_id        integer not null references pets(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  token         text not null,
  scope         text not null default 'full',
  expires_at    timestamptz,
  revoked_at    timestamptz,
  created_at    timestamptz not null default now(),
  constraint pet_emergency_share_links_token_key unique (token),
  constraint pet_emergency_share_links_scope_check
    check (scope = any (array['full','basic']::text[]))
);

create index if not exists idx_pet_emergency_links_owner on pet_emergency_share_links (owner_user_id);
create index if not exists idx_pet_emergency_links_pet on pet_emergency_share_links (pet_id);
create index if not exists idx_pet_emergency_links_token on pet_emergency_share_links (token);

-- ── 3. SECURITY DEFINER assembly + public readers (the SOLE public path) ────────
-- Internal: assemble a single card's whitelisted JSON from the LIVE owner-scoped sources.
-- DEFINER (runs as the function owner) so it reads the owner-RLS'd medical tables without a
-- public policy. NOT granted to pawpi_app — only the two public readers below call it. The card
-- ORGANIZES existing fields for a real vet; it never derives a diagnosis (non_diagnostic=true).
create or replace function app_emergency_card_json(p_card_id integer, p_include_medical boolean)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select jsonb_build_object(
    'pet', jsonb_build_object(
      'name', p.name,
      'species', p.species,
      'breed', p.breed,
      'age_years', p.age_years,
      'age_months', p.age_months,
      'gender', p.gender,
      'avatar_url', p.avatar_url,
      'has_home', true
    ),
    'microchip_id', mp.microchip_id,
    'contact', jsonb_build_object(
      'mode', c.contact_mode,
      -- raw owner contact is exposed ONLY for the direct phone/email modes; relay/none hide it.
      'value', case when c.contact_mode in ('phone','email') then c.contact_value else null end
    ),
    'lost', (
      select case when lr.id is null then null else jsonb_build_object(
        'active', true,
        'reward', lr.reward,
        'last_seen_area', lr.last_seen_area,
        'report_id', lr.id
      ) end
      from lost_reports lr
      where lr.pet_id = c.pet_id and lr.status = 'active'
      order by lr.created_at desc
      limit 1
    ),
    'non_diagnostic', true,
    'medical', case when p_include_medical then jsonb_build_object(
      'blood_type', c.blood_type,
      'spayed_neutered_status', mp.spayed_neutered_status,
      'medical_notes', mp.medical_notes,
      'extra_notes', c.extra_notes,
      'primary_vet_name', mp.primary_vet_name,
      'primary_clinic_name', mp.primary_clinic_name,
      'vet_phone', mp.vet_phone,
      'emergency_contact_name', mp.emergency_contact_name,
      'emergency_contact_phone', mp.emergency_contact_phone,
      'allergies', coalesce((
        select jsonb_agg(jsonb_build_object(
          'allergen', a.allergen, 'severity', a.severity, 'reaction', a.reaction
        ) order by a.id)
        from pet_allergies a where a.pet_id = c.pet_id
      ), '[]'::jsonb),
      'conditions', coalesce((
        select jsonb_agg(jsonb_build_object(
          'condition', cd.condition, 'status', cd.status
        ) order by cd.id)
        from pet_conditions cd where cd.pet_id = c.pet_id
      ), '[]'::jsonb)
    ) else null end
  )
  from pet_emergency_cards c
  join pets p on p.id = c.pet_id
  left join pet_medical_profiles mp on mp.pet_id = c.pet_id and mp.deleted_at is null
  where c.id = p_card_id;
$$;

-- Public TAG reader: BASIC fields for an ACTIVE card (+ medical IFF show_medical_on_tag). Zero
-- rows (→ NULL scalar) when the tag is unknown or the card is inactive.
create or replace function app_emergency_card_by_tag(p_tag_token text)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select app_emergency_card_json(c.id, c.show_medical_on_tag)
  from pet_emergency_cards c
  where c.tag_token = p_tag_token and c.active = true;
$$;

-- Public LINK reader: the scoped card (full|basic) for a link that is non-revoked AND non-expired
-- on an ACTIVE card. A revoked/expired/unknown link → zero rows → NULL.
create or replace function app_emergency_card_by_link(p_token text)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select app_emergency_card_json(c.id, (l.scope = 'full'))
  from pet_emergency_share_links l
  join pet_emergency_cards c on c.pet_id = l.pet_id
  where l.token = p_token
    and l.revoked_at is null
    and (l.expires_at is null or l.expires_at > now())
    and c.active = true;
$$;

-- Public RELAY contact: a stranger on the tag page messages the owner WITHOUT seeing any owner
-- data. Only for an ACTIVE card whose contact_mode is 'relay'. Best-effort via app_notify (0044);
-- a notify failure is contained by the caller. Returns true iff a relay target was found.
create or replace function app_emergency_relay_contact(p_tag_token text, p_message text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_owner integer;
  v_pet   integer;
begin
  select owner_user_id, pet_id into v_owner, v_pet
  from pet_emergency_cards
  where tag_token = p_tag_token and active = true and contact_mode = 'relay';
  if not found then
    return false;
  end if;
  -- actor = null (anonymous finder); app_notify still inserts (recipient <> actor).
  perform app_notify(v_owner, null, 'emergency_contact', v_pet::text,
                     left(coalesce(p_message, ''), 500));
  return true;
end;
$$;

grant execute on function app_emergency_card_by_tag(text) to pawpi_app;
grant execute on function app_emergency_card_by_link(text) to pawpi_app;
grant execute on function app_emergency_relay_contact(text, text) to pawpi_app;

-- ── 4. RLS — both tables OWNER-only (deny-by-default for everyone else) ──────────
alter table pet_emergency_cards enable row level security;
alter table pet_emergency_cards force row level security;
drop policy if exists pet_emergency_cards_owner_all on pet_emergency_cards;
create policy pet_emergency_cards_owner_all on pet_emergency_cards
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

alter table pet_emergency_share_links enable row level security;
alter table pet_emergency_share_links force row level security;
drop policy if exists pet_emergency_links_owner_all on pet_emergency_share_links;
create policy pet_emergency_links_owner_all on pet_emergency_share_links
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- ── 5. Widen the notifications type CHECK additively for 'emergency_contact' (0044/0050) ──
alter table notifications drop constraint if exists notifications_type_check;
alter table notifications add constraint notifications_type_check
  check (type = any (array['paw','bark','follow','lost_alert','emergency_contact']::text[]));
