-- 0052_transport_trips.sql
-- Phase 2 ticket 2.52: transport / pet-taxi on the existing provider spine. A pure SPINE play —
-- `transport` is already in ALLOWED_CAPABILITIES + the provider_capabilities / vet_appointments
-- capability CHECKs (0027/0030). A transport request IS a generalized booking (2.4); this table
-- is the transport-specific TRIP detail hanging off that booking, exactly like walk_sessions /
-- groom_sessions / sitting_visits. Payments (2.3) + chat (2.5) are reused unchanged.
--
-- RLS (modeled on walk_sessions, owner+staff):
--   OWNER  — reads/creates/edits/cancels OWN trips. A new trip is always 'requested'; the owner
--            may edit details or cancel, but CANNOT advance to a provider-only status
--            (confirmed/en_route/completed) — the WITH CHECK pins the owner to requested|cancelled.
--   STAFF  — active staff of provider_id read ALL the provider's trips (the inbox / the assigned
--            driver) and UPDATE them (confirm, assign a driver, advance status, set the fare).
--   Other-provider staff + outsiders + no-identity → ZERO (deny-by-default).
-- Reuses the existing SECURITY DEFINER helper app_is_active_staff_of(provider_id) — no new helper.
--
-- Live GPS for an in-progress trip is OUT OF SCOPE here (the walker-GPS 2.7 pattern) — a follow-up.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied to
-- Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant.
-- Idempotent.

create table if not exists transport_trips (
  id                integer generated by default as identity primary key,
  booking_id        integer references vet_appointments(id) on delete set null,
  provider_id       integer not null references providers(id) on delete cascade,
  pet_id            integer not null references pets(id) on delete cascade,
  owner_user_id     integer not null references user_profiles(id) on delete cascade,
  pickup_lat        numeric,
  pickup_lng        numeric,
  pickup_address    text,
  dropoff_lat       numeric,
  dropoff_lng       numeric,
  dropoff_address   text,
  scheduled_at      timestamptz,
  trip_type         text not null default 'one_way',
  pet_size          text,
  carrier_needed    boolean not null default false,
  assigned_staff_id integer references provider_staff(id) on delete set null,
  status            text not null default 'requested',
  fare_amount       numeric,
  notes             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint transport_trips_trip_type_check
    check (trip_type = any (array['one_way','round_trip']::text[])),
  constraint transport_trips_status_check
    check (status = any (array['requested','confirmed','en_route','completed','cancelled']::text[]))
);

create index if not exists idx_transport_trips_provider on transport_trips (provider_id);
create index if not exists idx_transport_trips_owner on transport_trips (owner_user_id);
create index if not exists idx_transport_trips_pet on transport_trips (pet_id);
create index if not exists idx_transport_trips_booking on transport_trips (booking_id);
create index if not exists idx_transport_trips_assigned on transport_trips (assigned_staff_id);
create index if not exists idx_transport_trips_status on transport_trips (status);

-- ── RLS ────────────────────────────────────────────────────────────────────────
alter table transport_trips enable row level security;
alter table transport_trips force row level security;

-- Owner SELECT — their own trips (the bookings hub / trip detail).
drop policy if exists transport_trips_owner_select on transport_trips;
create policy transport_trips_owner_select on transport_trips
  for select
  using (owner_user_id = current_app_user_id());

-- Owner INSERT — book a trip. A new trip is ALWAYS 'requested' (the owner cannot self-confirm).
drop policy if exists transport_trips_owner_insert on transport_trips;
create policy transport_trips_owner_insert on transport_trips
  for insert
  with check (owner_user_id = current_app_user_id() and status = 'requested');

-- Owner UPDATE — edit details or cancel ONLY. The WITH CHECK pins the owner to requested|cancelled
-- so they cannot flip a provider-only status (confirmed/en_route/completed).
drop policy if exists transport_trips_owner_update on transport_trips;
create policy transport_trips_owner_update on transport_trips
  for update
  using (owner_user_id = current_app_user_id())
  with check (
    owner_user_id = current_app_user_id()
    and status = any (array['requested','cancelled']::text[])
  );

-- Provider STAFF SELECT — active staff of the provider read ALL the provider's trips (inbox +
-- the assigned driver's own trips). app_is_active_staff_of (0023) is SECURITY DEFINER → no recursion.
drop policy if exists transport_trips_staff_select on transport_trips;
create policy transport_trips_staff_select on transport_trips
  for select
  using (app_is_active_staff_of(provider_id));

-- Provider STAFF UPDATE — confirm / assign a driver / advance status / set fare. Both USING and
-- WITH CHECK gate on active staff of THIS provider; a trip cannot be moved to another provider.
drop policy if exists transport_trips_staff_update on transport_trips;
create policy transport_trips_staff_update on transport_trips
  for update
  using (app_is_active_staff_of(provider_id))
  with check (app_is_active_staff_of(provider_id));
