-- 0053_vet_prescriptions.sql
-- Phase 2 ticket 2.53: prescriptions / Rx as a section INSIDE Veterinary + the Vet Record (NOT a
-- standalone pharmacy capability). A licensed vet (provider staff with the vet capability + access
-- to the pet via a consent grant OR a booking) ISSUES a prescription; the OWNER READS it and may
-- REQUEST A REFILL; the issuing vet approves (decrements refills) or declines. Clinical integrity =
-- STRICTEST, modeled on vet_notes (0023): the owner can NEVER write/forge a prescription, the
-- provider cannot edit another provider's Rx, and there is no hard delete (cancel via status).
--
-- DESIGN: prescriptions is APPEND-ONLY at the policy layer — owner SELECT only, provider SELECT +
-- INSERT only, NO direct UPDATE/DELETE policy. The two controlled mutations (refill decrement on
-- approve; cancel) flow through SECURITY DEFINER helpers so a row's clinical fields are never
-- rewritten via a broad provider UPDATE and the owner never writes prescription fields. The app
-- does NOT diagnose or prescribe — it RECORDS what a licensed vet issued.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied to
-- Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant;
-- only the new helpers need EXECUTE grants. Idempotent.

-- ── 1. Tables ───────────────────────────────────────────────────────────────────
create table if not exists prescriptions (
  id                  integer generated by default as identity primary key,
  pet_id              integer not null references pets(id) on delete cascade,
  owner_user_id       integer not null references user_profiles(id) on delete cascade,
  provider_id         integer not null references providers(id) on delete cascade,
  issued_by_staff_id  integer references provider_staff(id) on delete set null,
  source              text,
  drug_name           text not null,
  strength            text,
  dose                text,
  route               text,
  frequency           text,
  duration            text,
  quantity            text,
  refills_authorized  integer not null default 0,
  refills_remaining   integer not null default 0,
  instructions        text,
  status              text not null default 'active',
  issued_at           timestamptz not null default now(),
  created_at          timestamptz not null default now(),
  constraint prescriptions_source_check
    check (source is null or source = any (array['in_person','telehealth']::text[])),
  constraint prescriptions_status_check
    check (status = any (array['active','completed','cancelled']::text[]))
);

create index if not exists idx_prescriptions_pet on prescriptions (pet_id);
create index if not exists idx_prescriptions_owner on prescriptions (owner_user_id);
create index if not exists idx_prescriptions_provider on prescriptions (provider_id);

create table if not exists rx_refill_requests (
  id                  integer generated by default as identity primary key,
  prescription_id     integer not null references prescriptions(id) on delete cascade,
  pet_id              integer not null references pets(id) on delete cascade,
  owner_user_id       integer not null references user_profiles(id) on delete cascade,
  status              text not null default 'requested',
  requested_at        timestamptz not null default now(),
  decided_at          timestamptz,
  decided_by_staff_id integer references provider_staff(id) on delete set null,
  note                text,
  constraint rx_refill_requests_status_check
    check (status = any (array['requested','approved','declined']::text[]))
);

create index if not exists idx_rx_refill_requests_rx on rx_refill_requests (prescription_id);
create index if not exists idx_rx_refill_requests_owner on rx_refill_requests (owner_user_id);

-- ── 2. SECURITY DEFINER helpers (cross-table reads + controlled mutations) ───────
-- INSERT gate: the caller is active staff of THIS provider AND that provider has an active
-- medical_write grant OR a (non-deleted) booking on the pet. Binds the row's provider_id to the
-- caller's provider so a vet can't issue an Rx attributed to a clinic they aren't staff of.
create or replace function app_provider_can_rx(p_provider_id integer, p_pet_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from provider_staff ps
    where ps.provider_id = p_provider_id
      and ps.user_profile_id = current_app_user_id()
      and ps.status = 'active'
  )
  and (
    exists (
      select 1 from care_access_grants g
      where g.provider_id = p_provider_id and g.pet_id = p_pet_id
        and g.status = 'active' and (g.expires_at is null or g.expires_at > now())
        and 'medical_write' = any (g.scopes)
    )
    or exists (
      select 1 from vet_appointments va
      where va.provider_id = p_provider_id and va.pet_id = p_pet_id and va.deleted_at is null
    )
  )
$$;

-- Refill-request INSERT gate: the caller OWNS the prescription, it is ACTIVE and has refills left.
create or replace function app_owns_active_rx(p_prescription_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from prescriptions p
    where p.id = p_prescription_id
      and p.owner_user_id = current_app_user_id()
      and p.status = 'active'
      and p.refills_remaining > 0
  )
$$;

-- Refill-request provider SELECT: the caller is active staff of the prescribing provider.
create or replace function app_staff_of_rx_provider(p_prescription_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from prescriptions p
    join provider_staff ps on ps.provider_id = p.provider_id
    where p.id = p_prescription_id
      and ps.user_profile_id = current_app_user_id()
      and ps.status = 'active'
  )
$$;

-- The vet decides a refill request. Definer so the prescription decrement happens server-side
-- (prescriptions has NO provider UPDATE policy → its clinical fields are never rewritten). Only
-- active staff of the prescribing provider may decide; approve decrements refills_remaining.
create or replace function decide_rx_refill(p_request_id integer, p_approve boolean, p_note text default null)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_req   rx_refill_requests%rowtype;
  v_prov  integer;
  v_staff integer;
begin
  select * into v_req from rx_refill_requests where id = p_request_id;
  if not found then return 'not_found'; end if;
  if v_req.status <> 'requested' then return 'already_decided'; end if;

  select provider_id into v_prov from prescriptions where id = v_req.prescription_id;
  select id into v_staff from provider_staff
   where provider_id = v_prov and user_profile_id = current_app_user_id() and status = 'active'
   limit 1;
  if v_staff is null then return 'forbidden'; end if;

  if p_approve then
    update rx_refill_requests
      set status = 'approved', decided_at = now(), decided_by_staff_id = v_staff,
          note = coalesce(p_note, note)
      where id = p_request_id;
    update prescriptions
      set refills_remaining = greatest(refills_remaining - 1, 0)
      where id = v_req.prescription_id;
    return 'approved';
  else
    update rx_refill_requests
      set status = 'declined', decided_at = now(), decided_by_staff_id = v_staff,
          note = coalesce(p_note, note)
      where id = p_request_id;
    return 'declined';
  end if;
end;
$$;

-- The issuing provider cancels an Rx (status transition; no hard delete). Definer + staff-gated.
create or replace function cancel_rx(p_prescription_id integer)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_prov integer;
begin
  select provider_id into v_prov from prescriptions where id = p_prescription_id;
  if v_prov is null then return false; end if;
  if not exists (
    select 1 from provider_staff ps
    where ps.provider_id = v_prov and ps.user_profile_id = current_app_user_id() and ps.status = 'active'
  ) then
    return false;
  end if;
  update prescriptions set status = 'cancelled' where id = p_prescription_id and status <> 'cancelled';
  return true;
end;
$$;

grant execute on function app_provider_can_rx(integer, integer) to pawpi_app;
grant execute on function app_owns_active_rx(integer) to pawpi_app;
grant execute on function app_staff_of_rx_provider(integer) to pawpi_app;
grant execute on function decide_rx_refill(integer, boolean, text) to pawpi_app;
grant execute on function cancel_rx(integer) to pawpi_app;

-- ── 3. RLS — prescriptions (STRICTEST, append-only) ─────────────────────────────
alter table prescriptions enable row level security;
alter table prescriptions force row level security;

-- Owner: READ-ONLY. No insert/update/delete — the owner can never write/forge an Rx.
drop policy if exists prescriptions_owner_read on prescriptions;
create policy prescriptions_owner_read on prescriptions
  for select
  using (owner_user_id = current_app_user_id());

-- Provider: active staff of the issuing provider READ their own Rx (cross-provider → zero).
drop policy if exists prescriptions_provider_read on prescriptions;
create policy prescriptions_provider_read on prescriptions
  for select
  using (app_is_active_staff_of(provider_id));

-- Provider: INSERT a new Rx only for a pet they have access to (grant or booking) at THIS provider.
drop policy if exists prescriptions_provider_insert on prescriptions;
create policy prescriptions_provider_insert on prescriptions
  for insert
  with check (app_provider_can_rx(provider_id, pet_id));

-- NO provider UPDATE/DELETE policy: refill decrement + cancel flow through the DEFINER helpers
-- above, so a prescription's clinical fields can never be silently rewritten (append-only).

-- ── 4. RLS — rx_refill_requests ─────────────────────────────────────────────────
alter table rx_refill_requests enable row level security;
alter table rx_refill_requests force row level security;

-- Owner: read own requests; INSERT a request only on their OWN active Rx with refills remaining.
drop policy if exists rx_refill_requests_owner_select on rx_refill_requests;
create policy rx_refill_requests_owner_select on rx_refill_requests
  for select
  using (owner_user_id = current_app_user_id());

drop policy if exists rx_refill_requests_owner_insert on rx_refill_requests;
create policy rx_refill_requests_owner_insert on rx_refill_requests
  for insert
  with check (
    owner_user_id = current_app_user_id()
    and app_owns_active_rx(prescription_id)
  );

-- Provider: active staff of the prescribing provider READ requests for their prescriptions. The
-- DECISION is made via decide_rx_refill (DEFINER) — no direct provider UPDATE policy.
drop policy if exists rx_refill_requests_provider_select on rx_refill_requests;
create policy rx_refill_requests_provider_select on rx_refill_requests
  for select
  using (app_staff_of_rx_provider(prescription_id));
