-- 0054_insurance_marketplace.sql
-- Phase 2 ticket 2.54: a pet-insurance MARKETPLACE as a new `insurance` capability on the spine.
-- v1 is lead-gen — an insurer/broker publishes plans; an owner browses/compares and requests a
-- quote (a LEAD). NO underwriting, NO in-app binding/payment (a follow-up via 2.3). No medical data
-- flows to insurers beyond what the owner types into a quote (species/breed/age + note).
--
-- ADDS: (1) widen the two capability CHECKs to include 'insurance' (drop+add, like 0040 added
-- 'telehealth'); (2) insurance_plans (the catalog — published-public read, staff-managed, modeled
-- on provider_services 0024); (3) insurance_leads (owner-or-provider scoped, like a booking).
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied to
-- Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant.
-- Idempotent.

-- ── 1. Widen the capability CHECKs additively for 'insurance' ───────────────────
alter table provider_capabilities
  drop constraint if exists provider_capabilities_capability_check;
alter table provider_capabilities
  add constraint provider_capabilities_capability_check
  check (
    capability = any (array[
      'vet','groomer','walker','daycare','sitter','trainer',
      'shop','adoption','transport','pharmacy','telehealth','insurance'
    ]::text[])
  );

alter table vet_appointments
  drop constraint if exists vet_appointments_capability_check;
alter table vet_appointments
  add constraint vet_appointments_capability_check
  check (
    capability = any (array[
      'vet','groomer','walker','daycare','sitter','trainer',
      'shop','adoption','transport','pharmacy','telehealth','insurance'
    ]::text[])
  );

-- ── 2. insurance_plans — the insurer's catalog ──────────────────────────────────
create table if not exists insurance_plans (
  id                 integer generated by default as identity primary key,
  provider_id        integer not null references providers(id) on delete cascade,
  name               text not null,
  tier               text,
  species            text,
  monthly_price_min  numeric,
  monthly_price_max  numeric,
  deductible         text,
  reimbursement      text,
  coverage_highlights text[] not null default '{}',
  exclusions         text,
  terms_url          text,
  published          boolean not null default false,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);

create index if not exists idx_insurance_plans_provider on insurance_plans (provider_id);
create index if not exists idx_insurance_plans_published on insurance_plans (provider_id, published);

-- ── 3. insurance_leads — an owner's quote/interest request to an insurer ─────────
create table if not exists insurance_leads (
  id             integer generated by default as identity primary key,
  plan_id        integer references insurance_plans(id) on delete set null,
  provider_id    integer not null references providers(id) on delete cascade,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  pet_id         integer references pets(id) on delete set null,
  pet_species    text,
  pet_breed      text,
  pet_age        text,
  contact_email  text,
  contact_phone  text,
  note           text,
  status         text not null default 'new',
  created_at     timestamptz not null default now(),
  constraint insurance_leads_status_check
    check (status = any (array['new','contacted','closed']::text[]))
);

create index if not exists idx_insurance_leads_provider on insurance_leads (provider_id);
create index if not exists idx_insurance_leads_owner on insurance_leads (owner_user_id);

-- ── 4. RLS — insurance_plans (published-public read + staff-managed write) ───────
alter table insurance_plans enable row level security;
alter table insurance_plans force row level security;

-- Write: provider admins manage the catalog (mirrors provider_services_admin_all, 0024).
drop policy if exists insurance_plans_admin_all on insurance_plans;
create policy insurance_plans_admin_all on insurance_plans
  for all
  using (app_is_provider_admin(provider_id))
  with check (app_is_provider_admin(provider_id));

-- Read: active staff see ALL plans (incl. unpublished); anyone authed sees a PUBLISHED plan of a
-- PUBLISHED provider (the public marketplace) — same two-tier shape as provider_services.
drop policy if exists insurance_plans_read on insurance_plans;
create policy insurance_plans_read on insurance_plans
  for select
  using (
    app_is_active_staff_of(provider_id)
    or (
      published = true
      and exists (select 1 from providers p where p.id = provider_id and p.status = 'published')
    )
  );

-- ── 5. RLS — insurance_leads (owner-or-provider scoped, like a booking) ──────────
alter table insurance_leads enable row level security;
alter table insurance_leads force row level security;

-- Owner: read + create their OWN leads.
drop policy if exists insurance_leads_owner_select on insurance_leads;
create policy insurance_leads_owner_select on insurance_leads
  for select
  using (owner_user_id = current_app_user_id());

drop policy if exists insurance_leads_owner_insert on insurance_leads;
create policy insurance_leads_owner_insert on insurance_leads
  for insert
  with check (owner_user_id = current_app_user_id());

-- Provider: active staff of the targeted provider READ + UPDATE the status of their leads.
drop policy if exists insurance_leads_staff_select on insurance_leads;
create policy insurance_leads_staff_select on insurance_leads
  for select
  using (app_is_active_staff_of(provider_id));

drop policy if exists insurance_leads_staff_update on insurance_leads;
create policy insurance_leads_staff_update on insurance_leads
  for update
  using (app_is_active_staff_of(provider_id))
  with check (app_is_active_staff_of(provider_id));
