-- 0056_transport_trip_locations.sql
-- Wave 7 ticket 2.70: live-GPS tracking for an in-progress pet-taxi trip — the planned 2.52
-- follow-up (2.52 explicitly logged live GPS as out of scope). Mirrors the walker-GPS pattern (2.7):
-- the assigned driver posts {lat,lng,t} pings while the trip is en_route; the owner live-polls and
-- watches the track grow on a real Apple map (2.68 MapLocationView).
--
-- A ping row hangs off transport_trips (0052). RLS:
--   INSERT — ONLY the trip's assigned driver (the active provider_staff whose id = the trip's
--            assigned_staff_id) and ONLY while status = 'en_route'. Enforced by the SECURITY DEFINER
--            helper app_can_post_trip_location(trip_id), which reads transport_trips directly (definer
--            bypasses RLS → no recursion back into this table).
--   SELECT — the trip OWNER, the assigned driver, and active staff of the trip's provider; everyone
--            else ZERO. app_can_read_trip_location(trip_id) reuses app_is_active_staff_of (0023).
--   No UPDATE/DELETE policy — pings are append-only (the track can't be rewritten).
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness; hand-applied to
-- Supabase AFTER merge (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant.
-- Idempotent (CREATE ... IF NOT EXISTS / CREATE OR REPLACE / drop-then-create policies).

create table if not exists transport_trip_locations (
  id                 integer generated by default as identity primary key,
  trip_id            integer not null references transport_trips(id) on delete cascade,
  lat                numeric not null,
  lng                numeric not null,
  recorded_at        timestamptz not null default now(),
  posted_by_staff_id integer references provider_staff(id) on delete set null
);

create index if not exists idx_transport_trip_locations_trip
  on transport_trip_locations (trip_id, recorded_at);

-- ── SECURITY DEFINER helpers ─────────────────────────────────────────────────────
-- Both read transport_trips directly; SECURITY DEFINER + a pinned search_path means they run with
-- the function-owner's rights (bypassing transport_trip_locations' / transport_trips' RLS), so the
-- policies below never recurse. The access logic is implemented IN the function body.

-- Can the caller POST a ping for this trip? Only the assigned active driver, only while en_route.
create or replace function app_can_post_trip_location(p_trip_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from transport_trips t
    join provider_staff ps on ps.id = t.assigned_staff_id
    where t.id = p_trip_id
      and t.status = 'en_route'
      and ps.user_profile_id = current_app_user_id()
      and ps.status = 'active'
  )
$$;

-- Can the caller READ this trip's pings? The owner, the assigned driver, or any active staff of the
-- trip's provider (the driver is active staff, so app_is_active_staff_of covers them too).
create or replace function app_can_read_trip_location(p_trip_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from transport_trips t
    where t.id = p_trip_id
      and (
        t.owner_user_id = current_app_user_id()
        or app_is_active_staff_of(t.provider_id)
      )
  )
$$;

grant execute on function app_can_post_trip_location(integer) to pawpi_app;
grant execute on function app_can_read_trip_location(integer) to pawpi_app;

-- ── RLS ────────────────────────────────────────────────────────────────────────
alter table transport_trip_locations enable row level security;
alter table transport_trip_locations force row level security;

-- INSERT — assigned active driver, trip en_route, via the DEFINER helper.
drop policy if exists transport_trip_locations_driver_insert on transport_trip_locations;
create policy transport_trip_locations_driver_insert on transport_trip_locations
  for insert
  with check (app_can_post_trip_location(trip_id));

-- SELECT — owner, assigned driver, active provider staff. Outsiders + no-identity → zero.
drop policy if exists transport_trip_locations_read on transport_trip_locations;
create policy transport_trip_locations_read on transport_trip_locations
  for select
  using (app_can_read_trip_location(trip_id));
