-- 0057_rx_fulfillment.sql
-- Wave 7 ticket 2.71: Rx fulfillment (delivery/pickup + charging). Bridges the vet Rx (2.53) →
-- shop orders (2.11) → payments (2.3): a vet-issued prescription becomes a fulfillable order a
-- `pharmacy`-capable provider dispenses and the owner pays for. The clinical Rx stays owner-read-
-- only / append-only (2.53) — fulfillment NEVER lets the owner forge or edit an Rx, and a refill is
-- consumed ONLY via a SECURITY DEFINER safe path (fulfill_rx_order), never a raw prescriptions write.
--
-- NOTE: the `pharmacy` capability is ALREADY in the provider_capabilities / vet_appointments CHECK
-- (widened by 0040) and in app-side ALLOWED_CAPABILITIES — no capability widen is needed here.
--
-- RLS (modeled on transport_trips + the 2.53 Rx helpers):
--   OWNER  — reads/creates OWN fulfillment orders, but ONLY for a prescription they own that is
--            active WITH refills remaining (app_owns_fulfillable_rx, mirrors app_owns_active_rx).
--            The owner may edit/cancel while still 'requested' but CANNOT set provider-only statuses
--            or price (WITH CHECK pins owner updates to requested|cancelled).
--   STAFF  — active staff of the dispensing provider_id read + update (accept/price/advance/cancel)
--            their orders, but CANNOT jump straight to 'fulfilled' (WITH CHECK excludes it) — the
--            'fulfilled' transition runs ONLY through fulfill_rx_order, which consumes a refill on
--            the safe path. Other-provider staff + outsiders → ZERO.
--   prescriptions is NEVER written here (no new policy on it); the refill decrement is the 2.53
--   greatest(refills_remaining-1,0) pattern, inside fulfill_rx_order.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app; hand-applied to Supabase AFTER merge
-- (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant. Idempotent.

create table if not exists rx_fulfillment_orders (
  id                   integer generated by default as identity primary key,
  prescription_id      integer not null references prescriptions(id) on delete cascade,
  owner_user_id        integer not null references user_profiles(id) on delete cascade,
  pet_id               integer not null references pets(id) on delete cascade,
  provider_id          integer not null references providers(id) on delete cascade,
  order_id             integer references orders(id) on delete set null,
  method               text not null default 'delivery',
  delivery_lat         numeric,
  delivery_lng         numeric,
  delivery_address     text,
  provider_location_id integer references provider_locations(id) on delete set null,
  price_cents          integer,
  status               text not null default 'requested',
  is_refill            boolean not null default false,
  notes                text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  constraint rx_fulfillment_orders_method_check
    check (method = any (array['delivery','pickup']::text[])),
  constraint rx_fulfillment_orders_status_check
    check (status = any (array['requested','accepted','preparing','ready','out_for_delivery','fulfilled','cancelled']::text[])),
  constraint rx_fulfillment_orders_price_check
    check (price_cents is null or price_cents >= 0)
);

create index if not exists idx_rx_fulfillment_orders_rx on rx_fulfillment_orders (prescription_id);
create index if not exists idx_rx_fulfillment_orders_owner on rx_fulfillment_orders (owner_user_id);
create index if not exists idx_rx_fulfillment_orders_provider on rx_fulfillment_orders (provider_id);
create index if not exists idx_rx_fulfillment_orders_status on rx_fulfillment_orders (status);

-- ── SECURITY DEFINER helpers ─────────────────────────────────────────────────────

-- Owner-side INSERT gate: the caller owns an ACTIVE prescription that still has refills remaining
-- (mirrors 2.53's app_owns_active_rx). SECURITY DEFINER reads prescriptions → no recursion.
create or replace function app_owns_fulfillable_rx(p_prescription_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from prescriptions p
    where p.id = p_prescription_id
      and p.owner_user_id = current_app_user_id()
      and p.status = 'active'
      and p.refills_remaining > 0
  )
$$;
grant execute on function app_owns_fulfillable_rx(integer) to pawpi_app;

-- The ONLY path to 'fulfilled'. Active staff of the DISPENSING provider mark an order fulfilled; if
-- it is a refill, the prescription's refills_remaining is decremented on the 2.53 safe pattern
-- (greatest(-1,0)) — the append-only Rx is never written by the owner/provider directly.
create or replace function fulfill_rx_order(p_fulfillment_id integer)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order rx_fulfillment_orders%rowtype;
begin
  select * into v_order from rx_fulfillment_orders where id = p_fulfillment_id;
  if not found then return 'not_found'; end if;

  if not exists (
    select 1 from provider_staff ps
    where ps.provider_id = v_order.provider_id
      and ps.user_profile_id = current_app_user_id()
      and ps.status = 'active'
  ) then
    return 'forbidden';
  end if;

  if v_order.status in ('fulfilled', 'cancelled') then
    return 'already_done';
  end if;

  if v_order.is_refill then
    if (select refills_remaining from prescriptions where id = v_order.prescription_id) <= 0 then
      return 'no_refills';
    end if;
    update prescriptions
      set refills_remaining = greatest(refills_remaining - 1, 0)
      where id = v_order.prescription_id;
  end if;

  update rx_fulfillment_orders
    set status = 'fulfilled', updated_at = now()
    where id = p_fulfillment_id;
  return 'fulfilled';
end;
$$;
grant execute on function fulfill_rx_order(integer) to pawpi_app;

-- ── RLS ────────────────────────────────────────────────────────────────────────
alter table rx_fulfillment_orders enable row level security;
alter table rx_fulfillment_orders force row level security;

-- OWNER SELECT — own orders.
drop policy if exists rx_fulfillment_owner_select on rx_fulfillment_orders;
create policy rx_fulfillment_owner_select on rx_fulfillment_orders
  for select
  using (owner_user_id = current_app_user_id());

-- OWNER INSERT — own order, only on an owned fulfillable Rx, always 'requested'.
drop policy if exists rx_fulfillment_owner_insert on rx_fulfillment_orders;
create policy rx_fulfillment_owner_insert on rx_fulfillment_orders
  for insert
  with check (
    owner_user_id = current_app_user_id()
    and app_owns_fulfillable_rx(prescription_id)
    and status = 'requested'
  );

-- OWNER UPDATE — edit details or cancel ONLY. The WITH CHECK pins the owner to requested|cancelled
-- so they cannot set a provider-only status or move it to 'fulfilled'.
drop policy if exists rx_fulfillment_owner_update on rx_fulfillment_orders;
create policy rx_fulfillment_owner_update on rx_fulfillment_orders
  for update
  using (owner_user_id = current_app_user_id())
  with check (
    owner_user_id = current_app_user_id()
    and status = any (array['requested','cancelled']::text[])
  );

-- STAFF SELECT — active staff of the dispensing provider read their orders.
drop policy if exists rx_fulfillment_staff_select on rx_fulfillment_orders;
create policy rx_fulfillment_staff_select on rx_fulfillment_orders
  for select
  using (app_is_active_staff_of(provider_id));

-- STAFF UPDATE — accept/price/advance/cancel, but NOT 'fulfilled' (reserved for fulfill_rx_order so
-- a refill is always consumed on the safe path).
drop policy if exists rx_fulfillment_staff_update on rx_fulfillment_orders;
create policy rx_fulfillment_staff_update on rx_fulfillment_orders
  for update
  using (app_is_active_staff_of(provider_id))
  with check (
    app_is_active_staff_of(provider_id)
    and status <> 'fulfilled'
  );
