-- 0058_insurance_policies.sql
-- Wave 7 ticket 2.72: in-app insurance BINDING + PAYMENT, extending the 2.54 marketplace (lead-gen).
-- An owner applies for a plan → the insurer issues a policy_number + premium → the owner pays the
-- premium via 2.3 → the policy goes active. The INSURER is the party-of-record (PawPi facilitates,
-- does NOT underwrite — the app surfaces disclaimers + the insurer's terms link). Money/contract =
-- strictest RLS. No medical data flows to the insurer (only owner-entered details; the 2.54 rule).
--
-- NOTE: the `insurance` capability is already in the CHECK (0054) — no widen needed.
--
-- RLS (modeled on rx_fulfillment_orders 2.71 + transport_trips):
--   OWNER  — creates/reads OWN applications and can cancel. The owner can never inject a
--            policy_number/premium (WITH CHECK forces them NULL while the row stays 'application')
--            and can never set 'active' (only the safe path activates). Owner records terms
--            acceptance at the application stage.
--   STAFF  — active staff of the INSURER read + manage their policies (issue policy_number, set
--            premium/billing/effective, advance status), but CANNOT set 'active' (WITH CHECK excludes
--            it) — activation runs ONLY through activate_insurance_policy after a real approved
--            payment (app_is_active_staff_of). Other-provider staff + outsiders → ZERO.
--   ACTIVATION — activate_insurance_policy(policy_id, payment_id) is the ONLY path to 'active': it
--            verifies an APPROVED 2.3 payment tied to the policy's owner+provider, callable by the
--            owner or insurer staff. SECURITY DEFINER (reads payments) → no recursion.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app; hand-applied to Supabase AFTER merge
-- (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant. Idempotent.

create table if not exists insurance_policies (
  id                integer generated by default as identity primary key,
  plan_id           integer references insurance_plans(id) on delete set null,
  lead_id           integer references insurance_leads(id) on delete set null,
  provider_id       integer not null references providers(id) on delete cascade,
  owner_user_id     integer not null references user_profiles(id) on delete cascade,
  pet_id            integer references pets(id) on delete set null,
  policy_number     text,
  status            text not null default 'application',
  premium_cents     integer,
  billing_period    text,
  subscription_id   integer references subscriptions(id) on delete set null,
  payment_id        integer references payments(id) on delete set null,
  terms_accepted_at timestamptz,
  terms_url         text,
  effective_at      timestamptz,
  documents         jsonb not null default '[]',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  constraint insurance_policies_status_check
    check (status = any (array['application','active','payment_pending','lapsed','cancelled']::text[])),
  constraint insurance_policies_billing_check
    check (billing_period is null or billing_period = any (array['monthly','annual']::text[])),
  constraint insurance_policies_premium_check
    check (premium_cents is null or premium_cents >= 0)
);

create index if not exists idx_insurance_policies_provider on insurance_policies (provider_id);
create index if not exists idx_insurance_policies_owner on insurance_policies (owner_user_id);
create index if not exists idx_insurance_policies_plan on insurance_policies (plan_id);
create index if not exists idx_insurance_policies_status on insurance_policies (status);

-- ── SECURITY DEFINER: the ONLY path to 'active' ──────────────────────────────────
-- Activates a policy after a real APPROVED 2.3 payment tied to the policy's owner+provider. Callable
-- by the policy owner (after their own payment) or active insurer staff. Reads payments/orders →
-- SECURITY DEFINER so neither the activation nor the payment read recurses into policy RLS.
create or replace function activate_insurance_policy(p_policy_id integer, p_payment_id integer)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_pol insurance_policies%rowtype;
  v_ok  boolean;
begin
  select * into v_pol from insurance_policies where id = p_policy_id;
  if not found then return 'not_found'; end if;

  -- caller must be the policy owner OR active staff of the insurer
  if not (
    v_pol.owner_user_id = current_app_user_id()
    or exists (
      select 1 from provider_staff ps
      where ps.provider_id = v_pol.provider_id
        and ps.user_profile_id = current_app_user_id()
        and ps.status = 'active'
    )
  ) then
    return 'forbidden';
  end if;

  if v_pol.status not in ('application', 'payment_pending') then
    return 'not_bindable';
  end if;

  -- the payment must be APPROVED and belong to this policy's owner + insurer (via its order)
  select exists (
    select 1
    from payments pay
    join orders o on o.id = pay.order_id
    where pay.id = p_payment_id
      and pay.status = 'approved'
      and o.owner_user_id = v_pol.owner_user_id
      and o.provider_id = v_pol.provider_id
  ) into v_ok;
  if not v_ok then return 'payment_not_approved'; end if;

  update insurance_policies
    set status = 'active',
        payment_id = p_payment_id,
        effective_at = coalesce(effective_at, now()),
        updated_at = now()
    where id = p_policy_id;
  return 'active';
end;
$$;
grant execute on function activate_insurance_policy(integer, integer) to pawpi_app;

-- ── RLS ────────────────────────────────────────────────────────────────────────
alter table insurance_policies enable row level security;
alter table insurance_policies force row level security;

-- OWNER SELECT — own policies.
drop policy if exists insurance_policies_owner_select on insurance_policies;
create policy insurance_policies_owner_select on insurance_policies
  for select
  using (owner_user_id = current_app_user_id());

-- OWNER INSERT — own application, no self-issued number/premium, always 'application'.
drop policy if exists insurance_policies_owner_insert on insurance_policies;
create policy insurance_policies_owner_insert on insurance_policies
  for insert
  with check (
    owner_user_id = current_app_user_id()
    and status = 'application'
    and policy_number is null
    and premium_cents is null
  );

-- OWNER UPDATE — edit details / accept terms while 'application', or cancel from any state. When the
-- row stays 'application' the owner still cannot inject a number/premium; 'active' is never reachable.
drop policy if exists insurance_policies_owner_update on insurance_policies;
create policy insurance_policies_owner_update on insurance_policies
  for update
  using (owner_user_id = current_app_user_id())
  with check (
    owner_user_id = current_app_user_id()
    and status = any (array['application','cancelled']::text[])
    and (
      status = 'cancelled'
      or (policy_number is null and premium_cents is null)
    )
  );

-- STAFF SELECT — active staff of the insurer read their policies.
drop policy if exists insurance_policies_staff_select on insurance_policies;
create policy insurance_policies_staff_select on insurance_policies
  for select
  using (app_is_active_staff_of(provider_id));

-- STAFF UPDATE — issue/price/advance, but NOT 'active' (reserved for activate_insurance_policy).
drop policy if exists insurance_policies_staff_update on insurance_policies;
create policy insurance_policies_staff_update on insurance_policies
  for update
  using (app_is_active_staff_of(provider_id))
  with check (
    app_is_active_staff_of(provider_id)
    and status <> 'active'
  );
