-- 0059_pet_friendly_places.sql
-- Wave 7 ticket 2.73: pet-friendly PLACES directory. The place DATA comes live from the Google
-- Places API via a key-gated PawPi WEB route (the key never reaches the client; the feature degrades
-- cleanly when unset). Places are NOT providers — the only thing we persist is an owner's personal
-- FAVORITES. So this migration adds ONE owner-scoped table; there is no cache table (the proxy fetches
-- live), which keeps the RLS surface minimal and avoids storing third-party POI data.
--
-- RLS — owner-scoped FOR ALL, exactly like training_progress_self (0048): the owner reads/writes
-- their own saved places; everyone else sees ZERO.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app; hand-applied to Supabase AFTER merge
-- (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant. Idempotent.

create table if not exists saved_places (
  id             integer generated by default as identity primary key,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  place_id       text not null,
  name           text not null,
  category       text,
  lat            numeric,
  lng            numeric,
  address        text,
  raw            jsonb not null default '{}',
  created_at     timestamptz not null default now(),
  constraint saved_places_unique unique (owner_user_id, place_id)
);

create index if not exists idx_saved_places_owner on saved_places (owner_user_id);

-- ── RLS — owner-scoped (FOR ALL) ──────────────────────────────────────────────
alter table saved_places enable row level security;
alter table saved_places force row level security;

drop policy if exists saved_places_owner_all on saved_places;
create policy saved_places_owner_all on saved_places
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());
