-- 0060_events_meetups.sql
-- Wave 7 ticket 2.74: community EVENTS / meetups (puppy socials, adoption days, park meetups). A
-- social/community feature (NOT a provider service) — modeled on the forum (0047: public read,
-- author-only write/soft-delete) + social walks (0046: lat/lng/location_name). An event has a
-- location set via the 2.68 map picker and shown via MapLocationView. RSVPs are one-per-user (toggle
-- going/not_going); the attendee count is a COUNT on read, never denormalized (forum pattern).
--
-- RLS:
--   events       — any authed user READS a published, non-deleted event (the public listing); the
--                  HOST also sees their own (any status) to edit/cancel. INSERT as host; UPDATE/DELETE
--                  HOST-ONLY (host_user_id = caller). Soft-delete via deleted_at.
--   event_rsvps  — a user reads RSVPs of an event they can SEE (to count attendees) + always their own;
--                  INSERT/UPDATE their OWN rsvp only, and only on a published, non-deleted event (no
--                  RSVP to a cancelled/deleted event). UNIQUE(event_id, user_profile_id) + an upsert in
--                  the route toggles going/not_going. The policies read `events` with a plain EXISTS
--                  subquery — NOT recursive (events policies never reference event_rsvps), so no DEFINER
--                  is needed.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app; hand-applied to Supabase AFTER merge
-- (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant. Idempotent.

create table if not exists events (
  id               integer generated by default as identity primary key,
  host_user_id     integer not null references user_profiles(id) on delete cascade,
  title            text not null,
  description      text,
  starts_at        timestamptz not null,
  ends_at          timestamptz,
  lat              numeric,
  lng              numeric,
  location_name    text,
  address          text,
  cover_image_url  text,
  capacity         integer,
  status           text not null default 'published',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  deleted_at       timestamptz,
  constraint events_title_check check (length(btrim(title)) > 0),
  constraint events_status_check check (status = any (array['published','cancelled']::text[]))
);

create index if not exists idx_events_starts_at on events (starts_at);
create index if not exists idx_events_host on events (host_user_id);
create index if not exists idx_events_lat_lng on events (lat, lng);

create table if not exists event_rsvps (
  id               integer generated by default as identity primary key,
  event_id         integer not null references events(id) on delete cascade,
  user_profile_id  integer not null references user_profiles(id) on delete cascade,
  pet_id           integer references pets(id) on delete set null,
  status           text not null default 'going',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint event_rsvps_status_check check (status = any (array['going','not_going']::text[])),
  constraint event_rsvps_unique unique (event_id, user_profile_id)
);

create index if not exists idx_event_rsvps_event on event_rsvps (event_id);
create index if not exists idx_event_rsvps_user on event_rsvps (user_profile_id);

-- ── RLS — events ──────────────────────────────────────────────────────────────
alter table events enable row level security;
alter table events force row level security;

-- READ: any authed user sees a published, non-deleted event; the host also sees their own (any status).
drop policy if exists events_read on events;
create policy events_read on events
  for select
  using (
    current_app_user_id() is not null
    and (
      (status = 'published' and deleted_at is null)
      or host_user_id = current_app_user_id()
    )
  );

-- INSERT: the caller is the host.
drop policy if exists events_insert on events;
create policy events_insert on events
  for insert
  with check (host_user_id = current_app_user_id());

-- UPDATE: host only (edit / cancel / soft-delete). Both clauses pin the host so it can't be re-pointed.
drop policy if exists events_update on events;
create policy events_update on events
  for update
  using (host_user_id = current_app_user_id())
  with check (host_user_id = current_app_user_id());

-- DELETE: host only (hard delete; the app prefers soft-delete via deleted_at).
drop policy if exists events_delete on events;
create policy events_delete on events
  for delete
  using (host_user_id = current_app_user_id());

-- ── RLS — event_rsvps ─────────────────────────────────────────────────────────
alter table event_rsvps enable row level security;
alter table event_rsvps force row level security;

-- READ: RSVPs of an event the caller can see (count attendees), plus always the caller's own rsvp.
drop policy if exists event_rsvps_read on event_rsvps;
create policy event_rsvps_read on event_rsvps
  for select
  using (
    user_profile_id = current_app_user_id()
    or exists (
      select 1 from events e
      where e.id = event_id
        and (
          (e.status = 'published' and e.deleted_at is null)
          or e.host_user_id = current_app_user_id()
        )
    )
  );

-- INSERT: own rsvp only, only on a published, non-deleted event.
drop policy if exists event_rsvps_insert on event_rsvps;
create policy event_rsvps_insert on event_rsvps
  for insert
  with check (
    user_profile_id = current_app_user_id()
    and exists (
      select 1 from events e
      where e.id = event_id and e.status = 'published' and e.deleted_at is null
    )
  );

-- UPDATE: own rsvp only (toggle going/not_going), only while the event is published + non-deleted.
drop policy if exists event_rsvps_update on event_rsvps;
create policy event_rsvps_update on event_rsvps
  for update
  using (user_profile_id = current_app_user_id())
  with check (
    user_profile_id = current_app_user_id()
    and exists (
      select 1 from events e
      where e.id = event_id and e.status = 'published' and e.deleted_at is null
    )
  );
