-- 0061_nutrition_food_recalls.sql
-- Wave 7 ticket 2.75: two linked owner-facing HEALTH features — a per-pet nutrition plan + food-recall
-- alerts. PawPi helps owners TRACK + prepare vet conversations; it does NOT diagnose or prescribe a
-- diet (non-diagnostic copy lives in the app). Recall data is EXTERNAL (FDA/AAFCO-style feeds),
-- ingested server-side behind a cron secret; when unconfigured the feature degrades cleanly.
--
-- Tables + RLS:
--   nutrition_plans          — OWNER-scoped FOR ALL (owner reads/writes own; others zero), like
--                              saved_places/training_progress_self. Family visibility is a documented
--                              follow-up (kept owner-only for v1 — the on-brand simplest-correct choice).
--   food_recalls             — public REFERENCE data (recall notices, no PII): RLS-on, any-authed READ,
--                              and NO write policy — rows are written ONLY through the SECURITY DEFINER
--                              ingest path (so the completeness guard sees RLS-on + a policy; no EXEMPT).
--   pet_food_recall_matches  — OWNER-scoped FOR ALL: a per-pet alert row (shown/dismissed) so a match
--                              isn't re-derived. Matches are created by the DEFINER matcher (cross-owner
--                              read of nutrition_plans), never by the owner directly.
--
-- Also widens the notifications type CHECK additively for 'food_recall' (drop+re-add, like 0050/0051).
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app; hand-applied to Supabase AFTER merge
-- (test-backlog ACTION 1). DML/sequence grants ride 0019's blanket grant. Idempotent.

-- ── 1. nutrition_plans (owner-scoped) ──────────────────────────────────────────
create table if not exists nutrition_plans (
  id              integer generated by default as identity primary key,
  pet_id          integer not null references pets(id) on delete cascade,
  owner_user_id   integer not null references user_profiles(id) on delete cascade,
  food_brand      text,
  food_product    text,
  food_form       text,
  daily_portion   text,
  target_calories integer,
  notes           text,
  active          boolean not null default true,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  deleted_at      timestamptz,
  constraint nutrition_plans_form_check
    check (food_form is null or food_form = any (array['dry','wet','raw','mixed']::text[]))
);

create index if not exists idx_nutrition_plans_owner_pet on nutrition_plans (owner_user_id, pet_id);
create index if not exists idx_nutrition_plans_brand on nutrition_plans (lower(food_brand));

alter table nutrition_plans enable row level security;
alter table nutrition_plans force row level security;

drop policy if exists nutrition_plans_owner_all on nutrition_plans;
create policy nutrition_plans_owner_all on nutrition_plans
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- ── 2. food_recalls (public reference data; DEFINER-only writes) ────────────────
create table if not exists food_recalls (
  id           integer generated by default as identity primary key,
  source       text not null,
  external_ref text not null,
  brand        text,
  product      text,
  reason       text,
  recall_date  date,
  url          text,
  raw          jsonb not null default '{}',
  created_at   timestamptz not null default now(),
  constraint food_recalls_unique unique (source, external_ref)
);

create index if not exists idx_food_recalls_brand on food_recalls (lower(brand));

alter table food_recalls enable row level security;
alter table food_recalls force row level security;

-- READ: any authed user may read recall notices (public, non-PII reference data).
drop policy if exists food_recalls_read on food_recalls;
create policy food_recalls_read on food_recalls
  for select
  using (current_app_user_id() is not null);
-- NO write policy — ingest is DEFINER-only (ingest_food_recall below).

-- ── 3. pet_food_recall_matches (owner-scoped alerts) ───────────────────────────
create table if not exists pet_food_recall_matches (
  id             integer generated by default as identity primary key,
  pet_id         integer not null references pets(id) on delete cascade,
  recall_id      integer not null references food_recalls(id) on delete cascade,
  owner_user_id  integer not null references user_profiles(id) on delete cascade,
  notified_at    timestamptz not null default now(),
  dismissed_at   timestamptz,
  constraint pet_food_recall_matches_unique unique (pet_id, recall_id)
);

create index if not exists idx_pet_food_recall_matches_owner on pet_food_recall_matches (owner_user_id);

alter table pet_food_recall_matches enable row level security;
alter table pet_food_recall_matches force row level security;

-- Owner reads/dismisses their own match rows; writes (creation) come from the DEFINER matcher.
drop policy if exists pet_food_recall_matches_owner_all on pet_food_recall_matches;
create policy pet_food_recall_matches_owner_all on pet_food_recall_matches
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- ── 4. SECURITY DEFINER: ingest + match ────────────────────────────────────────

-- Idempotent ingest of one recall (UNIQUE(source, external_ref) prevents dupes). DEFINER so the
-- key/cron-gated server path can write food_recalls (which has no write policy). Returns the row id.
create or replace function ingest_food_recall(
  p_source text, p_external_ref text, p_brand text, p_product text,
  p_reason text, p_recall_date date, p_url text, p_raw jsonb
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_id integer;
begin
  insert into food_recalls (source, external_ref, brand, product, reason, recall_date, url, raw)
  values (p_source, p_external_ref, p_brand, p_product, p_reason, p_recall_date, p_url, coalesce(p_raw, '{}'::jsonb))
  on conflict (source, external_ref)
  do update set brand = excluded.brand, product = excluded.product, reason = excluded.reason,
    recall_date = excluded.recall_date, url = excluded.url, raw = excluded.raw
  returning id into v_id;
  return v_id;
end;
$$;
grant execute on function ingest_food_recall(text, text, text, text, text, date, text, jsonb) to pawpi_app;

-- Match a recall to active nutrition plans (brand matches case-insensitively; product, if given,
-- must be contained). Creates one alert per (pet, recall) and fires a best-effort 'food_recall'
-- notification to the owner. DEFINER so it can read nutrition_plans across owners + write matches.
-- Returns the number of new matches.
create or replace function match_food_recall(p_recall_id integer)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_rec  food_recalls%rowtype;
  v_plan record;
  v_count integer := 0;
  v_match integer;
begin
  select * into v_rec from food_recalls where id = p_recall_id;
  if not found or v_rec.brand is null then return 0; end if;

  for v_plan in
    select np.pet_id, np.owner_user_id
    from nutrition_plans np
    where np.active = true
      and np.deleted_at is null
      and np.food_brand is not null
      and lower(btrim(np.food_brand)) = lower(btrim(v_rec.brand))
      and (
        v_rec.product is null or btrim(v_rec.product) = ''
        or lower(coalesce(np.food_product, '')) like '%' || lower(btrim(v_rec.product)) || '%'
      )
  loop
    insert into pet_food_recall_matches (pet_id, recall_id, owner_user_id)
    values (v_plan.pet_id, p_recall_id, v_plan.owner_user_id)
    on conflict (pet_id, recall_id) do nothing
    returning id into v_match;

    if v_match is not null then
      v_count := v_count + 1;
      perform app_notify(
        v_plan.owner_user_id, null, 'food_recall', p_recall_id::text,
        left('A product matching your pet''s food was recalled: ' || coalesce(v_rec.reason, v_rec.brand), 500)
      );
    end if;
  end loop;
  return v_count;
end;
$$;
grant execute on function match_food_recall(integer) to pawpi_app;

-- ── 5. Widen the notifications type CHECK additively for 'food_recall' ──────────
alter table notifications drop constraint if exists notifications_type_check;
alter table notifications add constraint notifications_type_check
  check (type = any (array['paw','bark','follow','lost_alert','emergency_contact','food_recall']::text[]));
