-- 0064_provider_calendar_import.sql
-- Wave 9 ticket 2.84 — business calendar IMPORT (external Google/Outlook/Apple ICS feed → PawPi
-- "busy" blocks). A provider pastes a private iCal/ICS feed URL; PawPi periodically fetches it,
-- parses VEVENTs, and stores them as READ-ONLY busy blocks that the generalized-booking
-- availability logic (2.4) subtracts — so the provider is never double-booked. This is the
-- one-way, CI-testable feed-import half; device EventKit two-way sync stays in the native track.
--
-- Identity: provider_id scoping via the existing SECURITY DEFINER helpers app_is_provider_admin /
-- app_is_active_staff_of (0023/0025) — no new membership helper. Busy rows are written ONLY by the
-- SECURITY DEFINER sync fn (no owner write policy), so they stay read-only in PawPi (edited only via
-- re-sync / feed removal). Re-runnable (IF NOT EXISTS / CREATE OR REPLACE / drop-if-exists policies).

create table if not exists provider_calendar_feeds (
  id             integer generated by default as identity primary key,
  provider_id    integer not null references providers(id) on delete cascade,
  ics_url        text not null,
  last_synced_at timestamptz,
  active         boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz
);
create index if not exists idx_provider_calendar_feeds_provider on provider_calendar_feeds (provider_id);

create table if not exists provider_calendar_busy (
  id          integer generated by default as identity primary key,
  provider_id integer not null references providers(id) on delete cascade,
  feed_id     integer not null references provider_calendar_feeds(id) on delete cascade,
  starts_at   timestamptz not null,
  ends_at     timestamptz not null,
  source_uid  text,
  created_at  timestamptz not null default now()
);
create index if not exists idx_provider_calendar_busy_provider on provider_calendar_busy (provider_id);
create index if not exists idx_provider_calendar_busy_lookup on provider_calendar_busy (provider_id, starts_at, ends_at);

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table provider_calendar_feeds enable row level security;
alter table provider_calendar_feeds force row level security;

-- Owner/admin manage their provider's feeds (add / read / update / soft-delete).
drop policy if exists provider_calendar_feeds_admin_all on provider_calendar_feeds;
create policy provider_calendar_feeds_admin_all on provider_calendar_feeds
  for all
  using (app_is_provider_admin(provider_id))
  with check (app_is_provider_admin(provider_id));

-- Any active staff can READ the feed list (e.g. front-desk staff see what's synced).
drop policy if exists provider_calendar_feeds_staff_read on provider_calendar_feeds;
create policy provider_calendar_feeds_staff_read on provider_calendar_feeds
  for select
  using (app_is_active_staff_of(provider_id));

alter table provider_calendar_busy enable row level security;
alter table provider_calendar_busy force row level security;

-- Busy blocks are READ-ONLY in PawPi: active staff (incl. owner/admin) SELECT their provider's
-- busy windows; there is INTENTIONALLY no insert/update/delete policy, so under FORCE RLS the only
-- writer is the SECURITY DEFINER sync fn below (re-sync / feed removal). A direct write is denied
-- even for the owner.
drop policy if exists provider_calendar_busy_staff_read on provider_calendar_busy;
create policy provider_calendar_busy_staff_read on provider_calendar_busy
  for select
  using (app_is_active_staff_of(provider_id));

-- ── SECURITY DEFINER functions ────────────────────────────────────────────────
-- Cross-owner enumeration for the sync cron (mirrors app_due_subscriptions, 0039). Returns active,
-- non-deleted feeds the scheduler must re-fetch. Pinned search_path; GRANT to pawpi_app.
create or replace function app_active_calendar_feeds()
returns table (id integer, provider_id integer, ics_url text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select f.id, f.provider_id, f.ics_url
  from provider_calendar_feeds f
  where f.active = true and f.deleted_at is null
$$;
grant execute on function app_active_calendar_feeds() to pawpi_app;

-- The ONLY writer of busy blocks. Replaces the feed's busy rows with the freshly-parsed events and
-- stamps last_synced_at. SECURITY DEFINER so it bypasses the (deliberately absent) busy write
-- policy; it derives provider_id FROM the feed row, so it can't be aimed at another provider.
-- p_events is a jsonb array of { starts_at, ends_at, source_uid? }. Returns rows written.
create or replace function app_sync_calendar_feed(p_feed_id integer, p_events jsonb)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_provider_id integer;
  v_count integer;
begin
  select provider_id into v_provider_id
  from provider_calendar_feeds
  where id = p_feed_id and deleted_at is null;
  if v_provider_id is null then
    return 0;
  end if;

  delete from provider_calendar_busy where feed_id = p_feed_id;

  insert into provider_calendar_busy (provider_id, feed_id, starts_at, ends_at, source_uid)
  select v_provider_id, p_feed_id,
         (e->>'starts_at')::timestamptz,
         (e->>'ends_at')::timestamptz,
         e->>'source_uid'
  from jsonb_array_elements(coalesce(p_events, '[]'::jsonb)) e
  where (e->>'starts_at') is not null and (e->>'ends_at') is not null;
  get diagnostics v_count = row_count;

  update provider_calendar_feeds
  set last_synced_at = now(), updated_at = now()
  where id = p_feed_id;

  return v_count;
end;
$$;
grant execute on function app_sync_calendar_feed(integer, jsonb) to pawpi_app;

-- Soft-delete a feed (history preserved) AND clear its busy blocks so a removed feed no longer
-- blocks availability. SECURITY DEFINER for the busy delete.
create or replace function app_remove_calendar_feed(p_feed_id integer)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from provider_calendar_busy where feed_id = p_feed_id;
  update provider_calendar_feeds
  set active = false, deleted_at = now(), updated_at = now()
  where id = p_feed_id;
end;
$$;
grant execute on function app_remove_calendar_feed(integer) to pawpi_app;

-- The availability subtract source. The generalized-booking availability read is PUBLIC (any authed
-- user), but busy rows are owner/staff RLS-scoped, so this DEFINER fn exposes ONLY free/busy time
-- ranges (no event title/detail is ever stored) for active, non-deleted feeds of the provider being
-- viewed, in range. GRANT to pawpi_app. Direct table reads stay isolated per provider (RLS).
create or replace function app_provider_busy_windows(
  p_provider_id integer,
  p_from timestamptz,
  p_to timestamptz
)
returns table (starts_at timestamptz, ends_at timestamptz)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select b.starts_at, b.ends_at
  from provider_calendar_busy b
  join provider_calendar_feeds f on f.id = b.feed_id
  where b.provider_id = p_provider_id
    and f.active = true and f.deleted_at is null
    and b.ends_at > p_from
    and b.starts_at < p_to
$$;
grant execute on function app_provider_busy_windows(integer, timestamptz, timestamptz) to pawpi_app;
