-- 0065_ugc_moderation.sql
-- Phase "UGC Moderation" T1 — App Store Guideline 1.2 moderation primitives. The single
-- schema change for the whole 1.2 phase (report/block/hide/ban + content filter). DB ONLY:
-- no routes, no UI — provable end-to-end in the integration harness AS pawpi_app.
--
-- Adds:
--   content_reports  — polymorphic report ledger (reporter reads/writes only their own;
--                      status flips ONLY via the admin DEFINER helper).
--   user_blocks      — real user→user block (distinct from pet_friendships.status='blocked');
--                      blocker reads/writes/soft-deletes only their own rows.
--   hidden_at        — additive nullable column on every peer-UGC content table = "removed by
--                      us" (distinct from the author's deleted_at). Written ONLY by the admin
--                      DEFINER helpers under FORCE RLS (no owner write touches it).
--   banned_at        — additive nullable column on user_profiles = "account ejected" (admin
--                      DEFINER helper; sign-in block enforced in the auth layer, T5).
--   DEFINER helpers  — app_is_admin / app_moderate_hide / app_moderate_unhide / app_ban_user /
--                      app_user_is_blocked (pinned search_path, EXECUTE granted to pawpi_app —
--                      the 0044 app_notify / 0047 forum_vote pattern).
--
-- House rules: new tables ENABLE+FORCE RLS, owner/actor = user_profiles.id, integer identity
-- PKs, soft-delete via deleted_at, controlled/cross-author writes via SECURITY DEFINER helpers.
-- Auto-classified by the completeness guard (rls-gap-closure.integration.test.ts): both new
-- tables are FORCE-RLS with policies, so they need no allowlist entry.
--
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in ugc-moderation.integration.test.ts;
-- hand-applied to Supabase AFTER merge via supabase/verify_0065.sql (test-backlog ACTION 1).
-- Idempotent (IF NOT EXISTS / CREATE OR REPLACE / drop-if-exists policies; additive widen).

-- ── 1. content_reports — polymorphic report ledger ─────────────────────────────
create table if not exists content_reports (
  id               integer generated by default as identity primary key,
  reporter_user_id integer not null references user_profiles(id) on delete cascade,
  target_type      text not null,
  target_id        integer not null,
  reason           text,
  details          text,
  status           text not null default 'open',
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  deleted_at       timestamptz,
  constraint content_reports_target_type_check check (
    target_type = any (array[
      'post','bark','forum_thread','forum_comment','dm_message','provider_message',
      'review','pet_profile','user_profile','adoption_listing','event','social_walk',
      'lost_report'
    ]::text[])
  ),
  constraint content_reports_reason_check check (
    reason is null or reason = any (array[
      'spam','harassment','hate','sexual','violence','other'
    ]::text[])
  ),
  constraint content_reports_status_check check (
    status = any (array['open','actioned','dismissed']::text[])
  )
);

create index if not exists idx_content_reports_target on content_reports (target_type, target_id);
create index if not exists idx_content_reports_status_created on content_reports (status, created_at desc);
create index if not exists idx_content_reports_reporter on content_reports (reporter_user_id);

-- ── 2. user_blocks — real user→user block ──────────────────────────────────────
create table if not exists user_blocks (
  id              integer generated by default as identity primary key,
  blocker_user_id integer not null references user_profiles(id) on delete cascade,
  blocked_user_id integer not null references user_profiles(id) on delete cascade,
  created_at      timestamptz not null default now(),
  deleted_at      timestamptz,
  constraint user_blocks_not_self check (blocker_user_id <> blocked_user_id)
);

-- One live block per ordered pair (re-block after unblock is allowed: the prior row is
-- soft-deleted so its deleted_at is non-null and excluded from the partial unique).
create unique index if not exists idx_user_blocks_live_pair
  on user_blocks (blocker_user_id, blocked_user_id) where deleted_at is null;
create index if not exists idx_user_blocks_blocker on user_blocks (blocker_user_id) where deleted_at is null;
create index if not exists idx_user_blocks_blocked on user_blocks (blocked_user_id) where deleted_at is null;

-- ── 3. hidden_at on the peer-UGC content tables ("removed by us") ───────────────
alter table posts               add column if not exists hidden_at timestamptz;
alter table post_barks          add column if not exists hidden_at timestamptz;
alter table forum_threads       add column if not exists hidden_at timestamptz;
alter table forum_comments      add column if not exists hidden_at timestamptz;
alter table messages            add column if not exists hidden_at timestamptz;
alter table dm_messages         add column if not exists hidden_at timestamptz;
alter table provider_reviews    add column if not exists hidden_at timestamptz;
alter table adoptable_listings  add column if not exists hidden_at timestamptz;
alter table events              add column if not exists hidden_at timestamptz;
alter table social_walks        add column if not exists hidden_at timestamptz;
alter table lost_reports        add column if not exists hidden_at timestamptz;

-- ── 4. banned_at on user_profiles (eject an abusive account) ───────────────────
alter table user_profiles add column if not exists banned_at timestamptz;

-- ── 5. RLS — content_reports (reporter reads/writes own; status via helper only) ─
alter table content_reports enable row level security;
alter table content_reports force row level security;

drop policy if exists content_reports_select on content_reports;
create policy content_reports_select on content_reports
  for select
  using (reporter_user_id = current_app_user_id());

drop policy if exists content_reports_insert on content_reports;
create policy content_reports_insert on content_reports
  for insert
  with check (reporter_user_id = current_app_user_id());

-- No UPDATE / DELETE policy on purpose: under FORCE RLS a direct pawpi_app status change is
-- denied, leaving app_moderate_hide / app_moderate_unhide (DEFINER) the only writers of status.

-- ── 6. RLS — user_blocks (blocker reads/writes/soft-deletes own) ───────────────
alter table user_blocks enable row level security;
alter table user_blocks force row level security;

drop policy if exists user_blocks_select on user_blocks;
create policy user_blocks_select on user_blocks
  for select
  using (blocker_user_id = current_app_user_id());

drop policy if exists user_blocks_insert on user_blocks;
create policy user_blocks_insert on user_blocks
  for insert
  with check (blocker_user_id = current_app_user_id());

-- UPDATE: the blocker soft-deletes (unblock) or re-points nothing else; both USING + WITH CHECK
-- keep the row pinned to the caller.
drop policy if exists user_blocks_update on user_blocks;
create policy user_blocks_update on user_blocks
  for update
  using (blocker_user_id = current_app_user_id())
  with check (blocker_user_id = current_app_user_id());

drop policy if exists user_blocks_delete on user_blocks;
create policy user_blocks_delete on user_blocks
  for delete
  using (blocker_user_id = current_app_user_id());

-- ── 7. notifications_type_check — additive widen for 'report_received' admin ping ─
alter table notifications drop constraint if exists notifications_type_check;
alter table notifications add constraint notifications_type_check
  check (type = any (array[
    'paw','bark','follow','lost_alert','emergency_contact','food_recall','report_received'
  ]::text[]));

-- ── 8. DEFINER helpers ─────────────────────────────────────────────────────────
-- Is the current app user a platform admin? Reads user_profiles.role (the valid_role CHECK
-- already permits 'admin'). DEFINER + STABLE + pinned search_path.
create or replace function app_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from user_profiles
    where id = current_app_user_id() and role = 'admin'
  )
$$;
grant execute on function app_is_admin() to pawpi_app;

-- Either-direction LIVE block between two users (read helper for T3 enforcement). DEFINER so
-- it sees user_blocks regardless of which side the caller is on.
create or replace function app_user_is_blocked(p_a integer, p_b integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from user_blocks
    where deleted_at is null
      and ((blocker_user_id = p_a and blocked_user_id = p_b)
        or (blocker_user_id = p_b and blocked_user_id = p_a))
  )
$$;
grant execute on function app_user_is_blocked(integer, integer) to pawpi_app;

-- Hide a piece of content ("removed by us"): set hidden_at on the right table and flip the
-- matching open reports to 'actioned'. Admin-only. DEFINER so it bypasses the (deliberately
-- absent) hidden_at owner-write path and the content tables' author-only UPDATE policies.
-- target_type is whitelisted → mapped to a fixed table name, so the dynamic UPDATE is safe.
create or replace function app_moderate_hide(p_target_type text, p_target_id integer)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_table text;
  v_count integer;
begin
  if not app_is_admin() then
    raise exception 'not authorized';
  end if;

  v_table := case p_target_type
    when 'post'             then 'posts'
    when 'bark'             then 'post_barks'
    when 'forum_thread'     then 'forum_threads'
    when 'forum_comment'    then 'forum_comments'
    when 'provider_message' then 'messages'
    when 'dm_message'       then 'dm_messages'
    when 'review'           then 'provider_reviews'
    when 'adoption_listing' then 'adoptable_listings'
    when 'event'            then 'events'
    when 'social_walk'      then 'social_walks'
    when 'lost_report'      then 'lost_reports'
    else null
  end;
  if v_table is null then
    raise exception 'unsupported target_type for hide: %', p_target_type;
  end if;

  execute format('update %I set hidden_at = now() where id = $1 and hidden_at is null', v_table)
    using p_target_id;
  get diagnostics v_count = row_count;

  update content_reports
  set status = 'actioned', updated_at = now()
  where target_type = p_target_type and target_id = p_target_id and status = 'open';

  return v_count;
end;
$$;
grant execute on function app_moderate_hide(text, integer) to pawpi_app;

-- Reverse a hide (clear hidden_at). Admin-only. Leaves report history as-is.
create or replace function app_moderate_unhide(p_target_type text, p_target_id integer)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_table text;
  v_count integer;
begin
  if not app_is_admin() then
    raise exception 'not authorized';
  end if;

  v_table := case p_target_type
    when 'post'             then 'posts'
    when 'bark'             then 'post_barks'
    when 'forum_thread'     then 'forum_threads'
    when 'forum_comment'    then 'forum_comments'
    when 'provider_message' then 'messages'
    when 'dm_message'       then 'dm_messages'
    when 'review'           then 'provider_reviews'
    when 'adoption_listing' then 'adoptable_listings'
    when 'event'            then 'events'
    when 'social_walk'      then 'social_walks'
    when 'lost_report'      then 'lost_reports'
    else null
  end;
  if v_table is null then
    raise exception 'unsupported target_type for unhide: %', p_target_type;
  end if;

  execute format('update %I set hidden_at = null where id = $1 and hidden_at is not null', v_table)
    using p_target_id;
  get diagnostics v_count = row_count;
  return v_count;
end;
$$;
grant execute on function app_moderate_unhide(text, integer) to pawpi_app;

-- Eject an abusive user (set banned_at). Admin-only. The actual sign-in block is enforced in
-- the auth layer (T5); this just stamps the flag. DEFINER so it can write another user's row.
create or replace function app_ban_user(p_user_id integer)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if not app_is_admin() then
    raise exception 'not authorized';
  end if;
  update user_profiles set banned_at = now() where id = p_user_id;
end;
$$;
grant execute on function app_ban_user(integer) to pawpi_app;
