-- 0067_legal_consents.sql
-- Phase "Legal consent at signup" — persist Terms of Service / Privacy Policy acceptance
-- server-side (App Store readiness / Guideline 1.2 follow-up). The signup form already gates
-- submit on a mandatory, unchecked-by-default checkbox; this records WHO accepted, WHEN, and
-- WHICH version — an append-only audit log.
--
-- Adds:
--   legal_consents     — append-only consent ledger keyed to auth_users.id (NOT user_profiles.id).
--                        user_profiles rows are created LAZILY (currentUser.ensureUserProfile /
--                        pets POST/PATCH), so at signup there is no user_profiles.id and
--                        app.current_user_id is unset — a normal FORCE-RLS owner INSERT would be
--                        DENIED. So the ONLY writer is the SECURITY DEFINER helper below, and
--                        reads are admin-only.
--   app_record_consent — SECURITY DEFINER insert helper (the 0044 app_notify / 0065 moderation
--                        pattern): pinned search_path, EXECUTE granted to pawpi_app. Inserts one
--                        row with no profile/RLS identity present while the table stays FORCE-RLS.
--                        Versions are passed BY THE SERVER (server-authoritative), never the client.
--
-- House rules: new table ENABLE+FORCE RLS, integer identity PK. No owner INSERT/UPDATE/DELETE
-- policy on purpose (DEFINER-only writer; append-only = never updated or deleted). An admin
-- SELECT policy (user_profiles.role='admin', reusing the 0065 app_is_admin() check) satisfies
-- the completeness guard (rls-gap-closure.integration.test.ts) WITHOUT an allowlist entry.
--
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in legal-consent.integration.test.ts;
-- hand-applied to Supabase AFTER merge via supabase/verify_0067.sql (test-backlog ACTION 1).
-- Idempotent (IF NOT EXISTS / CREATE OR REPLACE / drop-if-exists policy).

-- ── 1. legal_consents — append-only consent ledger ─────────────────────────────
create table if not exists legal_consents (
  id              integer generated by default as identity primary key,
  auth_user_id    integer not null references auth_users(id) on delete cascade,
  terms_version   text not null,
  privacy_version text not null,
  source          text,              -- 'web_signup' | 'mobile_signup'
  user_agent      text,
  accepted_at     timestamptz not null default now(),
  created_at      timestamptz not null default now()
);

create index if not exists idx_legal_consents_auth_user on legal_consents (auth_user_id);
create index if not exists idx_legal_consents_accepted on legal_consents (accepted_at desc);

-- ── 2. RLS — admin-only read; writes ONLY through the DEFINER helper ────────────
alter table legal_consents enable row level security;
alter table legal_consents force row level security;

-- Admin read (reuses the 0065 app_is_admin() check). No INSERT/UPDATE/DELETE policy on purpose:
-- under FORCE RLS a direct pawpi_app write is denied, leaving app_record_consent (DEFINER) the
-- only writer; append-only means there is never an update/delete path.
drop policy if exists legal_consents_select on legal_consents;
create policy legal_consents_select on legal_consents
  for select
  using (app_is_admin());

-- ── 3. DEFINER insert helper ───────────────────────────────────────────────────
-- Record one consent row. Keyed to auth_users.id because the user_profiles row may not exist
-- yet at signup (lazy creation). DEFINER so it writes under FORCE RLS with NO app.current_user_id
-- set. Returns the new row id. Versions are server-authoritative (passed in by the endpoint).
create or replace function app_record_consent(
  p_auth_user_id integer,
  p_terms_version text,
  p_privacy_version text,
  p_source text,
  p_user_agent text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id bigint;
begin
  insert into legal_consents (auth_user_id, terms_version, privacy_version, source, user_agent)
  values (p_auth_user_id, p_terms_version, p_privacy_version, p_source, p_user_agent)
  returning id into v_id;
  return v_id;
end;
$$;
grant execute on function app_record_consent(integer, text, text, text, text) to pawpi_app;
