-- 0069_password_reset_tokens.sql
-- App Store readiness: SELF-SERVICE PASSWORD RESET. `/account/forgot-password` was a
-- frontend-only stub — a reviewer could reach it and hit a dead end, and a locked-out owner had
-- no recovery path at all. This adds the server side of the flow.
--
-- Adds:
--   password_reset_tokens              — single-use, short-expiry reset tokens. Keyed to
--                                        auth_users.id (NOT user_profiles.id) for the same reason
--                                        0067's legal_consents is: user_profiles rows are created
--                                        LAZILY (currentUser.ensureUserProfile / pets POST), so a
--                                        user who never finished onboarding has no profile id, and
--                                        app.current_user_id is unset for the whole flow — the
--                                        requester is by definition NOT logged in. A normal
--                                        FORCE-RLS owner policy could never be satisfied here.
--   app_create_password_reset_token    — SECURITY DEFINER insert helper (+ built-in abuse throttle).
--   app_consume_password_reset_token   — SECURITY DEFINER consume helper: validates + burns the
--                                        token, writes the new password hash, invalidates the
--                                        account's other outstanding tokens and DB sessions.
--
-- Security shape (the 0067 / 0044 app_notify pattern):
--   • The table stores a SHA-256 HASH of the token, never the token itself. A DB dump does not
--     yield a usable reset link.
--   • ENABLE + FORCE RLS with NO owner read/write policy: every write and the only read happen
--     inside the two DEFINER helpers, which run with no identity in scope. A pawpi_app-authenticated
--     request can never SELECT a token row off a session, so a logged-in attacker cannot enumerate
--     or steal another account's pending reset. An admin SELECT policy (the 0065 app_is_admin()
--     check, same as 0067) satisfies the completeness guard — and only ever exposes hashes.
--   • Nothing here touches an existing table's RLS. auth_accounts / auth_sessions are RLS-EXEMPT
--     identity infra (0026), so the DEFINER consume helper can write them directly.
--
-- Password hashing stays in the app layer (argon2 in src/auth.js), NOT in Postgres: the consume
-- helper is handed an already-hashed password so the DB never sees a plaintext secret and the
-- hashing parameters stay in one place.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in password-reset.integration.test.ts;
-- hand-applied to Supabase AFTER merge via supabase/verify_0069.sql (test-backlog ACTION 1).
-- Idempotent (IF NOT EXISTS / CREATE OR REPLACE / drop-if-exists policy).

-- ── 1. password_reset_tokens ───────────────────────────────────────────────────
create table if not exists password_reset_tokens (
  id             integer generated by default as identity primary key,
  auth_user_id   integer not null references auth_users(id) on delete cascade,
  token_hash     text not null,          -- sha256(raw token), hex. The raw token is emailed, never stored.
  expires_at     timestamptz not null,   -- short (the route uses 30 minutes)
  used_at        timestamptz,            -- non-null = burned; single-use is enforced on this column
  requested_ip   text,
  user_agent     text,
  created_at     timestamptz not null default now()
);

-- One row per token hash: a collision (or a replayed insert) must never create two live tokens.
create unique index if not exists idx_password_reset_tokens_hash
  on password_reset_tokens (token_hash);
create index if not exists idx_password_reset_tokens_auth_user
  on password_reset_tokens (auth_user_id);
-- Supports the "outstanding tokens for this account" sweep in the consume helper + the throttle.
create index if not exists idx_password_reset_tokens_live
  on password_reset_tokens (auth_user_id, expires_at desc)
  where used_at is null;

-- ── 2. RLS — no owner path at all; DEFINER-only reads and writes ────────────────
alter table password_reset_tokens enable row level security;
alter table password_reset_tokens force row level security;

-- Admin read only (hashes, so this leaks nothing usable) — present so the table is CLASSIFIED for
-- the completeness guard (rls-gap-closure.integration.test.ts) without an RLS_EXEMPT entry.
-- Deliberately NO insert/update/delete policy: under FORCE RLS that leaves the two DEFINER helpers
-- below as the only writers, and no policy at all can expose a token to an ordinary session.
drop policy if exists password_reset_tokens_select on password_reset_tokens;
create policy password_reset_tokens_select on password_reset_tokens
  for select
  using (app_is_admin());

-- ── 3. DEFINER create helper ───────────────────────────────────────────────────
-- Issue one reset token. Returns the new row id, or NULL when throttled.
--
-- Throttle: at most 5 tokens per account per hour. Returning NULL (rather than raising) lets the
-- route keep its uniform "if that email exists, we sent a link" response — a throttled request is
-- indistinguishable from an unknown address, so this cannot be used to probe for real accounts.
create or replace function app_create_password_reset_token(
  p_auth_user_id integer,
  p_token_hash   text,
  p_expires_at   timestamptz,
  p_ip           text,
  p_user_agent   text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_recent int;
  v_id     bigint;
begin
  if p_auth_user_id is null or p_token_hash is null or p_expires_at is null then
    return null;
  end if;

  select count(*) into v_recent
  from password_reset_tokens
  where auth_user_id = p_auth_user_id
    and created_at > now() - interval '1 hour';

  if v_recent >= 5 then
    return null;
  end if;

  insert into password_reset_tokens (auth_user_id, token_hash, expires_at, requested_ip, user_agent)
  values (p_auth_user_id, p_token_hash, p_expires_at, p_ip, p_user_agent)
  returning id into v_id;

  return v_id;
end;
$$;
grant execute on function app_create_password_reset_token(integer, text, timestamptz, text, text) to pawpi_app;

-- ── 4. DEFINER consume helper ──────────────────────────────────────────────────
-- Validate + burn a token and set the account's new password. Returns the auth_users.id on
-- success, or NULL when the token is unknown, already used, or expired (the route maps NULL to one
-- generic "invalid or expired link" message — it never says which).
--
-- p_password_hash is an ALREADY-HASHED password (argon2, from the route). Postgres never sees the
-- plaintext.
--
-- On success, in one transaction:
--   1. the presented token is burned (used_at = now()), so a replay finds used_at non-null;
--   2. every OTHER outstanding token for the account is burned too — if a reset was requested
--      twice, or an attacker had also requested one, those links die with this one;
--   3. the credentials account's password hash is replaced. If the account has no credentials row
--      (it was created via social sign-in, ticket 2.46), one is created — the user proved control
--      of the mailbox, which is exactly the trust level signup uses, and this is the only way an
--      OAuth-only user can ever gain an email/password login they asked for;
--   4. the account's DB sessions are deleted. (Auth.js runs the JWT session strategy here, so
--      already-issued JWTs stay valid until they expire — see docs/app-store-readiness.md. This is
--      still the right thing to do and is what a future switch to DB sessions would rely on.)
-- No other account is read or touched: every statement is filtered by the token's own auth_user_id.
create or replace function app_consume_password_reset_token(
  p_token_hash    text,
  p_password_hash text
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_id       bigint;
  v_auth     integer;
  v_accounts int;
begin
  if p_token_hash is null or p_password_hash is null or length(p_password_hash) = 0 then
    return null;
  end if;

  -- FOR UPDATE: two concurrent redemptions of the same link serialize here, so exactly one wins
  -- (the loser re-reads used_at as non-null and matches nothing).
  select id, auth_user_id into v_id, v_auth
  from password_reset_tokens
  where token_hash = p_token_hash
    and used_at is null
    and expires_at > now()
  for update;

  if v_id is null then
    return null;
  end if;

  -- 1 + 2: burn this token and every other outstanding one for the account.
  update password_reset_tokens
  set used_at = now()
  where auth_user_id = v_auth
    and used_at is null;

  -- 3: replace the credentials password hash (auth_accounts is RLS-exempt identity infra, 0026).
  update auth_accounts
  set password = p_password_hash
  where "userId" = v_auth
    and provider = 'credentials';
  get diagnostics v_accounts = row_count;

  if v_accounts = 0 then
    insert into auth_accounts ("userId", provider, type, "providerAccountId", password)
    values (v_auth, 'credentials', 'credentials', v_auth::text, p_password_hash);
  end if;

  -- 4: drop this account's DB sessions. Other users' sessions are untouched.
  delete from auth_sessions where "userId" = v_auth;

  return v_auth;
end;
$$;
grant execute on function app_consume_password_reset_token(text, text) to pawpi_app;
