-- 0074_place_reviews.sql
-- Pet-friendly PLACE reviews — a community-rating layer over the Google-sourced places
-- (keyed by the Google place_id). Places are NOT providers and are NOT persisted as their own
-- rows (see 0059: the Google Places data is fetched live by a key-gated proxy; the only owner
-- data we store is saved_places favorites). This adds ONE community table: a review a pet owner
-- leaves on a place, carrying an overall rating + a pet-welcome tier + amenity tags.
--
-- One editable review per owner per place: UNIQUE (owner_user_id, place_id). A repeat POST
-- upserts (ON CONFLICT DO UPDATE), so an owner edits their single review rather than stacking rows.
--
-- RLS — mirrors provider_reviews (0028): aggregates over a place's reviews are PUBLIC, so SELECT is
-- open to any AUTHENTICATED app user (current_app_user_id() is set), while INSERT/UPDATE/DELETE are
-- owner-only (owner_user_id = current_app_user_id()). Unlike provider_reviews there is no
-- "published provider" gate — a place is a public Google POI, not an owned entity — so the SELECT
-- predicate is simply "is there an authenticated identity", nothing narrower.
--
-- ADDITIVE + fully back-compatible: a brand-new table, no change to any existing table.
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness, NOT applied to
-- Supabase here. Hand-applied to Supabase at the operator's cutover (docs/rls-hardening.md), like
-- the rest of the R2 set. DML/sequence grants ride 0019's blanket grant + ALTER DEFAULT PRIVILEGES,
-- so no per-table re-grant is needed. Idempotent.

create table if not exists place_reviews (
  id                integer generated by default as identity primary key,
  owner_user_id     integer not null references user_profiles(id) on delete cascade,
  place_id          text not null,
  place_name        text not null,
  place_category    text,
  overall_rating    integer not null check (overall_rating between 1 and 5),
  pet_welcome_level text not null check (pet_welcome_level in
    ('royalty', 'very_welcoming', 'allowed', 'patio_only', 'not_for_pets')),
  amenities         text[] not null default '{}',
  comment           text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz,
  deleted_at        timestamptz,
  constraint place_reviews_owner_place_unique unique (owner_user_id, place_id)
);

-- Aggregate reads scan every review for one place_id (the ratings roll-up), so index it.
create index if not exists idx_place_reviews_place on place_reviews (place_id);

-- ── RLS — public read (authenticated), owner-only writes ──────────────────────
alter table place_reviews enable row level security;
alter table place_reviews force row level security;

-- SELECT: any authenticated app user (aggregates are public). No owner/entity narrowing.
drop policy if exists place_reviews_select on place_reviews;
create policy place_reviews_select on place_reviews
  for select
  using (current_app_user_id() is not null);

-- INSERT: owner-only — author AS yourself.
drop policy if exists place_reviews_insert on place_reviews;
create policy place_reviews_insert on place_reviews
  for insert
  with check (owner_user_id = current_app_user_id());

-- UPDATE: my own review only (edit / upsert / soft-delete).
drop policy if exists place_reviews_update on place_reviews;
create policy place_reviews_update on place_reviews
  for update
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- DELETE: my own review only.
drop policy if exists place_reviews_delete on place_reviews;
create policy place_reviews_delete on place_reviews
  for delete
  using (owner_user_id = current_app_user_id());
