-- 0082_provider_post_comments.sql
-- Phase C: guest-open + comment on provider STOREFRONT POSTS (provider_posts, 2.22). Adds a
-- comment ledger so any signed-in user can comment on a visible provider post and anyone
-- (incl. guests, via the app-layer public GET) can read comments.
--
-- Shape mirrors provider_posts (0042/0066): integer identity id, soft delete via deleted_at,
-- moderation via hidden_at. RLS is ENABLE + FORCE (R3-governed like the provider tables) and
-- keyed to the same GUC + helper the rest of the R3 policies use:
--   • current_app_user_id()          — the app.current_user_id GUC → user_profiles.id
--   • app_is_provider_admin(provider_id) — SECURITY DEFINER owner|admin-of-provider check
-- (NOTE: author_user_id references user_profiles(id), NOT a "users" table — there is no `users`
-- table in this schema; user_profiles.id is what current_app_user_id() returns, so the RLS
-- author check author_user_id = current_app_user_id() requires this reference.)
--
-- Policies:
--   • provider_post_comments_read   — the PUBLIC window is visible rows only (deleted_at IS NULL
--       AND hidden_at IS NULL); the author + a provider admin additionally retain visibility of
--       their own removed rows so the soft-delete UPDATE is possible (see the policy note below).
--   • provider_post_comments_insert — author_user_id = current user AND post_id/provider_id must
--       name a real, currently-visible post (non-deleted, non-hidden, published provider).
--   • provider_post_comments_update — the author (own row) OR a provider admin may UPDATE. All
--       take-downs are soft via UPDATE (author → deleted_at, admin → hidden_at), consistent with
--       provider_posts; the API sets the right column per caller.
--
-- HARNESS-ONLY THIS PR — proven as pawpi_app in the integration harness; hand-applied to
-- Supabase by Tats BEFORE the consumer code deploys. Idempotent. pawpi_app gets table
-- privileges automatically via 0019's blanket + default-privilege grants (like 0042/0077).

create table if not exists provider_post_comments (
  id             integer generated by default as identity primary key,
  post_id        integer not null references provider_posts(id) on delete cascade,
  provider_id    integer not null references providers(id),
  author_user_id integer not null references user_profiles(id) on delete cascade,
  body           text not null check (btrim(body) <> ''),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  deleted_at     timestamptz,
  hidden_at      timestamptz
);

create index if not exists idx_provider_post_comments_post_created
  on provider_post_comments (post_id, created_at);
create index if not exists idx_provider_post_comments_provider
  on provider_post_comments (provider_id);

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table provider_post_comments enable row level security;
alter table provider_post_comments force row level security;

-- SELECT: the PUBLIC window is "visible" comments only (deleted_at IS NULL AND hidden_at IS NULL)
-- — a caller with no identity (guest) sees exactly those. The author (own rows) and a provider
-- admin ALSO retain visibility of their own soft-deleted / hidden rows: this is required for the
-- soft-delete-via-UPDATE to work at all — Postgres rejects an UPDATE whose resulting row is no
-- longer SELECT-visible to the actor ("new row violates row-level security policy"), exactly the
-- reason provider_posts' read policy keeps staff able to see their own deleted posts (0042). The
-- public GET endpoint still filters deleted_at/hidden_at in its WHERE, so a signed-in author never
-- sees their own removed comment in the list either.
drop policy if exists provider_post_comments_read on provider_post_comments;
create policy provider_post_comments_read on provider_post_comments
  for select
  using (
    (deleted_at is null and hidden_at is null)
    or author_user_id = current_app_user_id()
    or app_is_provider_admin(provider_id)
  );

-- INSERT: the row's author must be the current user, and post_id/provider_id must name a real,
-- currently-visible post (the same public window the comment will live in).
drop policy if exists provider_post_comments_insert on provider_post_comments;
create policy provider_post_comments_insert on provider_post_comments
  for insert
  with check (
    author_user_id = current_app_user_id()
    and exists (
      select 1
      from provider_posts pp
      join providers p on p.id = pp.provider_id
      where pp.id = post_id
        and pp.provider_id = provider_id
        and pp.deleted_at is null
        and pp.hidden_at is null
        and p.status = 'published'
    )
  );

-- UPDATE: the author (own row → deleted_at) OR a provider admin (→ hidden_at). Row-level gate;
-- the API sets the correct column per caller.
drop policy if exists provider_post_comments_update on provider_post_comments;
create policy provider_post_comments_update on provider_post_comments
  for update
  using (
    author_user_id = current_app_user_id()
    or app_is_provider_admin(provider_id)
  )
  with check (
    author_user_id = current_app_user_id()
    or app_is_provider_admin(provider_id)
  );
