-- 0083_provider_follows.sql
-- Ticket 2.92 — pet owners FOLLOW a business/provider (the provider-side mirror of pet_follows,
-- 0012). A signed-in user follows a provider instantly; the provider's follower count and the
-- user's "businesses I follow" list derive from this table. FOLLOW ONLY — no daily-moments/video.
--
-- Shape mirrors pet_follows (0012) with the follower being a USER (not a pet):
--   • follower_user_id references user_profiles(id) — the app user; user_profiles.id is exactly
--     what current_app_user_id() returns (there is NO "users" table in this schema — see the note
--     in 0082_provider_post_comments.sql), so the RLS own-row check follower_user_id =
--     current_app_user_id() requires this reference.
--   • provider_id references providers(id).
-- unique(follower_user_id, provider_id) makes a repeat follow a no-op (the API uses ON CONFLICT).
--
-- RLS is ENABLE + FORCE (R3-governed like the rest of the provider/social tables) and mirrors
-- pet_follows' policy split exactly:
--   • provider_follows_authed_read  — SELECT for any authenticated caller (follower COUNTS,
--       is-following, and "who I follow" all need to read edges). The table holds only ids + a
--       timestamp — never provider-private data; the API projects ONLY public provider columns on
--       its joins, so a public-read edge table leaks nothing sensitive (same posture as
--       pet_follows_authed_read).
--   • provider_follows_owner_write  — FOR ALL, gated on follower_user_id = current_app_user_id():
--       a user may INSERT/DELETE ONLY their OWN follow rows; a cross-user write inserts/deletes
--       zero. No SECURITY DEFINER needed — the predicate reads only this table + the GUC.
--
-- HARNESS-ONLY THIS PR — proven as pawpi_app in the integration harness; hand-applied to Supabase
-- by Tats BEFORE... no: the consumer code merges/deploys FIRST (2.92), so the follow feature is
-- written to DEGRADE CLEANLY while the table is absent (the API catches undefined_table / 42P01 and
-- returns "not following / 0 followers / empty list"; the mobile button no-ops until the table
-- exists). Idempotent. pawpi_app gets table privileges automatically via 0019's blanket +
-- default-privilege grants (like 0042/0077/0082). FLAG in docs/test-backlog.md ACTION 1.

create table if not exists provider_follows (
  id               integer generated by default as identity primary key,
  follower_user_id integer not null references user_profiles(id) on delete cascade,
  provider_id      integer not null references providers(id) on delete cascade,
  created_at       timestamptz not null default now(),
  constraint provider_follows_user_provider_key unique (follower_user_id, provider_id)
);

create index if not exists idx_provider_follows_provider on provider_follows (provider_id);
create index if not exists idx_provider_follows_follower on provider_follows (follower_user_id);

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table provider_follows enable row level security;
alter table provider_follows force row level security;

-- SELECT: any authenticated caller (follower counts / is-following / who-I-follow). Edges only.
drop policy if exists provider_follows_authed_read on provider_follows;
create policy provider_follows_authed_read on provider_follows
  for select
  using (current_app_user_id() is not null);

-- INSERT/DELETE (FOR ALL): a user manages ONLY their own follow rows.
drop policy if exists provider_follows_owner_write on provider_follows;
create policy provider_follows_owner_write on provider_follows
  for all
  using (follower_user_id = current_app_user_id())
  with check (follower_user_id = current_app_user_id());
