-- 0085_provider_post_paws.sql
-- Ticket 2.94 — "Paws" (likes) on business STOREFRONT posts. provider_posts (0042) has comments
-- (0082) + moderation (0066) but no like primitive; this adds the paw edge. Mirrors post_paws
-- (0004, the pet feed) and provider_follows (0083, the user-edge RLS split).
--
--   • post_id references provider_posts(id) on delete cascade — the liked storefront post. The
--     public-profile stats query (providers/public/[slug]) already JOINs provider_post_paws pp ON
--     p.id = pp.post_id to compute pawsCount, so this column name is load-bearing.
--   • user_id references user_profiles(id) — the app user; user_profiles.id is exactly what
--     current_app_user_id() returns (there is NO "users" table — see 0082), so the RLS own-row
--     check user_id = current_app_user_id() requires this reference.
-- unique(post_id, user_id) makes a repeat paw a no-op (the API uses an existence check / idempotent
-- insert) and toggling off deletes that one row.
--
-- RLS is ENABLE + FORCE and mirrors post_paws / provider_follows exactly:
--   • provider_post_paws_authed_read — SELECT for any authenticated caller (paw COUNTS + is-pawed;
--     an edge table of ids + a timestamp, never private data).
--   • provider_post_paws_owner_write — FOR ALL, gated on user_id = current_app_user_id(): a user may
--     INSERT/DELETE ONLY their OWN paw rows; a cross-user write touches zero. No SECURITY DEFINER
--     needed — the predicate reads only this table + the GUC.
--
-- HARNESS-ONLY THIS PR — proven as pawpi_app in the integration harness; hand-applied to Supabase by
-- Tats after review. The consumer code merges/deploys FIRST, so the paw feature DEGRADES CLEANLY
-- while the table is absent: every provider_post_paws query catches undefined_table (42P01) and
-- returns 0 paws / not-pawed, and the paw action no-ops — never a 500. Idempotent. pawpi_app gets
-- table privileges automatically via 0019's blanket + default-privilege grants (like 0042/0082/0083).
-- FLAG in docs/test-backlog.md ACTION 1.

create table if not exists provider_post_paws (
  id         integer generated by default as identity primary key,
  post_id    integer not null references provider_posts(id) on delete cascade,
  user_id    integer not null references user_profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint provider_post_paws_post_id_user_id_key unique (post_id, user_id)
);

create index if not exists idx_provider_post_paws_post on provider_post_paws (post_id);
create index if not exists idx_provider_post_paws_user on provider_post_paws (user_id);

-- ── RLS ──────────────────────────────────────────────────────────────────────
alter table provider_post_paws enable row level security;
alter table provider_post_paws force row level security;

-- SELECT: any authenticated caller (paw counts / is-pawed). Edges only.
drop policy if exists provider_post_paws_authed_read on provider_post_paws;
create policy provider_post_paws_authed_read on provider_post_paws
  for select
  using (current_app_user_id() is not null);

-- INSERT/DELETE (FOR ALL): a user manages ONLY their own paw rows.
drop policy if exists provider_post_paws_owner_write on provider_post_paws;
create policy provider_post_paws_owner_write on provider_post_paws
  for all
  using (user_id = current_app_user_id())
  with check (user_id = current_app_user_id());
