-- 0089_walk_packages_and_credits.sql
-- Ticket B2 (docs/phase2-tickets/B2-walk-packages-and-credits.md) — prepaid WALK PACKAGES + a
-- per-owner↔provider CREDIT BALANCE. A walker sets packages (single / 10 / 20, each with a price);
-- an owner BUYS a pack → a prepaid balance of walks, usable across the owner's pets with that
-- provider (DECISION LOCK 3/4). Credits are SPENT AT PICKUP (B3), not here — this migration only
-- adds the offerings, the balance table, and the grant-on-paid helper.
--
-- THREE additive changes:
--   1. walk_packages   — the walker's offerings (provider-scoped). Public read of ACTIVE packages
--                        for a PUBLISHED provider (mirrors provider_services_read); admin write.
--   2. walk_credit_packs — the owner's purchased balance. Owner reads/uses their OWN; the provider's
--                        ACTIVE STAFF may READ their own provider's balances (so the walker sees a
--                        customer's remaining walks at pickup). NO owner INSERT/UPDATE policy: the
--                        pack is GRANTED by app_grant_walk_credits (DEFINER, below) on paid, and
--                        DECREMENTED by app_redeem_walk_credit (DEFINER, B3). Balance = SUM(
--                        walks_total - walks_used) over active packs.
--   3. orders.kind     — add the 'walk_package' value (additive; keeps existing kinds).
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as `pawpi_app` in the integration harness, NOT applied to
-- Supabase here. Hand-applied by Tats AFTER the Wave-B run (flagged in the PR body + test-backlog
-- ACTION 1). The consumer code DEGRADES CLEANLY while these are absent (packages read [], purchase
-- route no-ops/greys, balance reads 0 — never a 500). Idempotent. pawpi_app gets table privileges
-- via 0019's blanket + default-privilege grants; the DEFINER helper gets an explicit EXECUTE grant.

-- ── 1. walk_packages (the walker's offerings) ─────────────────────────────────
create table if not exists walk_packages (
  id          integer generated by default as identity primary key,
  provider_id integer not null references providers(id) on delete cascade,
  walks_count integer not null check (walks_count > 0),
  price_cents integer not null check (price_cents >= 0),
  currency    text not null default 'ARS',
  active      boolean not null default true,
  created_at  timestamptz not null default now()
);
create index if not exists idx_walk_packages_provider on walk_packages (provider_id);

alter table walk_packages enable row level security;
alter table walk_packages force row level security;

-- Writes (INSERT/UPDATE/DELETE) + staff read of ALL packages (incl. inactive): owner|admin.
drop policy if exists walk_packages_admin_all on walk_packages;
create policy walk_packages_admin_all on walk_packages
  for all
  using (app_is_provider_admin(provider_id))
  with check (app_is_provider_admin(provider_id));

-- SELECT: active staff (management list) OR an ACTIVE package of a PUBLISHED provider (public
-- storefront). Mirrors provider_services_read (0024). The providers EXISTS runs under providers'
-- own SELECT RLS (a published provider is visible to any authed user), so no DEFINER helper needed.
drop policy if exists walk_packages_read on walk_packages;
create policy walk_packages_read on walk_packages
  for select
  using (
    app_is_active_staff_of(provider_id)
    or (
      active = true
      and exists (
        select 1 from providers p
        where p.id = provider_id and p.status = 'published'
      )
    )
  );

-- ── 2. walk_credit_packs (the owner's purchased balance) ──────────────────────
create table if not exists walk_credit_packs (
  id            integer generated by default as identity primary key,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  provider_id   integer not null references providers(id) on delete cascade,
  walks_total   integer not null check (walks_total > 0),
  walks_used    integer not null default 0 check (walks_used >= 0),
  order_id      integer references orders(id) on delete set null,
  purchased_at  timestamptz not null default now(),
  active        boolean not null default true,
  constraint walk_credit_packs_used_le_total check (walks_used <= walks_total)
);
create index if not exists idx_walk_credit_packs_owner_provider
  on walk_credit_packs (owner_user_id, provider_id);
-- Idempotent grant: at most one credit pack per paid order (the grant guards on this too).
create unique index if not exists uq_walk_credit_packs_order
  on walk_credit_packs (order_id) where order_id is not null;

alter table walk_credit_packs enable row level security;
alter table walk_credit_packs force row level security;

-- SELECT: the owner sees their OWN balance; the provider's ACTIVE STAFF see their own provider's
-- balances (the walker checks remaining walks at pickup). NO write policy — the pack is granted by
-- app_grant_walk_credits (on paid) and decremented by app_redeem_walk_credit (B3), both SECURITY
-- DEFINER, so under FORCE RLS a raw owner INSERT/UPDATE is denied (credits can't be self-minted or
-- self-spent).
drop policy if exists walk_credit_packs_read on walk_credit_packs;
create policy walk_credit_packs_read on walk_credit_packs
  for select
  using (
    owner_user_id = current_app_user_id()
    or app_is_active_staff_of(provider_id)
  );

-- ── 3. orders.kind — add 'walk_package' (additive) ────────────────────────────
alter table orders drop constraint if exists orders_kind_check;
alter table orders add constraint orders_kind_check check (
  kind = any (array[
    'booking','product','adoption_fee','donation','subscription','walk_package'
  ]::text[])
);

-- ── grant-on-paid helper ──────────────────────────────────────────────────────
-- app_grant_walk_credits(order_id) — GRANTS a credit pack for a PAID walk_package order, exactly
-- once. Called from applyPaymentStatus on the first transition into paid. SECURITY DEFINER (the
-- payment actor — the owner or a webhook — is NOT provider staff and has no walk_credit_packs write
-- policy, mirroring app_adjust_order_stock's posture). Idempotent: guards on order_id (+ the unique
-- index is the last line). The package id rides in orders.source_ref as 'walk_package:<id>'; the
-- walks_total is read SERVER-SIDE from walk_packages (never the client). Returns the new pack id, or
-- NULL when nothing was granted (not a walk_package, already granted, or the package is gone).
create or replace function app_grant_walk_credits(p_order_id integer)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_order       orders%rowtype;
  v_package_id  integer;
  v_walks_count integer;
  v_new_id      integer;
begin
  select * into v_order from orders where id = p_order_id;
  if not found or v_order.kind <> 'walk_package' then
    return null;
  end if;

  -- Idempotent: never double-grant for the same order (a re-delivered webhook is a no-op).
  if exists (select 1 from walk_credit_packs where order_id = p_order_id) then
    return null;
  end if;

  -- The package id rides in source_ref as 'walk_package:<id>'. Defensive parse (only a well-formed
  -- ref yields an id — anything else grants nothing rather than erroring).
  if coalesce(v_order.source_ref, '') !~ '^walk_package:[0-9]+$' then
    return null;
  end if;
  v_package_id := split_part(v_order.source_ref, ':', 2)::integer;

  select walks_count into v_walks_count
  from walk_packages
  where id = v_package_id and provider_id = v_order.provider_id;
  if v_walks_count is null then
    return null;
  end if;

  insert into walk_credit_packs (owner_user_id, provider_id, walks_total, walks_used, order_id)
  values (v_order.owner_user_id, v_order.provider_id, v_walks_count, 0, p_order_id)
  on conflict (order_id) where order_id is not null do nothing
  returning id into v_new_id;

  return v_new_id;
end;
$$;

grant execute on function app_grant_walk_credits(integer) to pawpi_app;
