-- 0092_walk_requests.sql
-- Ticket C1 (docs/phase2-tickets/C1-direct-request-a-walk.md) — an owner picks a specific walker
-- and REQUESTS a walk; the walker is notified, ACCEPTS, and that atomically opens a chat + creates a
-- confirmed walker booking so both sides can coordinate. This introduces the shared walk_requests
-- model that C2 reuses for the "find a walker now" broadcast (target_provider_id NULL). DECISION
-- LOCKS 1, 2, 4.
--
-- THREE changes:
--   1. walk_requests — an owner's request for a walk. target_provider_id SET = direct/C1 (to one
--      chosen walker); NULL = broadcast/C2. Lifecycle open → accepted | cancelled | expired; a
--      request is LIVE iff status='open' AND expires_at > now() (expiry evaluated at read time).
--      RLS ENABLE+FORCE: the OWNER does select/insert/update on THEIR OWN rows (insert pinned to
--      status='open'; update limited to cancelling an open request); a TARGETED provider's ACTIVE
--      STAFF may READ rows aimed at their provider (the broadcast read policy comes in C2). The
--      accept transition is NEVER a raw owner/staff UPDATE — it is the DEFINER helper below.
--   2. notifications_type_check — WIDEN (0044, last widened in 0086) additively to carry the four
--      walk-request lifecycle types (targeted/broadcast/accepted/taken). All four now, so C2 needs
--      no notify migration. Reuses the whole 2.26 notification system verbatim.
--   3. app_accept_walk_request(request_id, provider_id) — the ONLY accept path. SECURITY DEFINER,
--      atomic (mirrors app_redeem_walk_credit / app_approve_adoption): authorizes the caller is
--      ACTIVE STAFF of the provider; row-locks the request (FOR UPDATE) so two concurrent accepts
--      can't both win; verifies it is still open, not expired, and eligible (targeted at this
--      provider OR a broadcast — target NULL, for C2); flips it to accepted + stamps
--      accepted_provider_id/accepted_at; and CREATES the confirmed walker booking (the walker is
--      active staff, and vet_appointments has NO provider-INSERT policy — so an owner-owned booking
--      can only be created here, in the DEFINER body, exactly like app_approve_adoption's cross-user
--      writes). A prepaid credit funds it when the owner holds a balance with this provider (spent at
--      pickup per B3, not now); otherwise a normal payable walker booking. RETURNS
--      jsonb {request, booking_id} (NULL when already taken / expired / unauthorized → the route maps
--      NULL to 409 "already taken"). First-to-accept wins. The chat thread + owner notification are
--      opened by the route (staff CAN insert a message_thread + safeNotify under existing RLS).
--
-- ⚠️ HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness, NOT applied to
-- Supabase here (hand-applied by Tats after the Wave-C/D run; flagged in the PR body + test-backlog
-- ACTION 1). The consumer code DEGRADES CLEANLY while these are absent (create/list no-op to empty,
-- accept returns a friendly 503, never a 500). Idempotent DDL. The DEFINER helper gets an EXECUTE grant.

-- ── 1. walk_requests ──────────────────────────────────────────────────────────
create table if not exists walk_requests (
  id                   integer generated by default as identity primary key,
  owner_user_id        integer not null references user_profiles(id) on delete cascade,
  pet_id               integer not null references pets(id) on delete cascade,
  target_provider_id   integer references providers(id) on delete cascade,
  pickup_lat           numeric(9,6),
  pickup_lng           numeric(9,6),
  note                 text,
  when_type            text not null default 'now' check (when_type in ('now','scheduled')),
  scheduled_at         timestamptz,
  status               text not null default 'open' check (status in ('open','accepted','cancelled','expired')),
  accepted_provider_id integer references providers(id),
  accepted_at          timestamptz,
  expires_at           timestamptz not null default (now() + interval '2 hours'),
  created_at           timestamptz not null default now()
);

create index if not exists idx_walk_requests_owner on walk_requests (owner_user_id);
create index if not exists idx_walk_requests_target_status on walk_requests (target_provider_id, status);
create index if not exists idx_walk_requests_status_expires on walk_requests (status, expires_at);

alter table walk_requests enable row level security;
alter table walk_requests force row level security;

-- Owner reads their own requests.
drop policy if exists walk_requests_owner_select on walk_requests;
create policy walk_requests_owner_select on walk_requests
  for select using (owner_user_id = current_app_user_id());

-- Owner creates their own request, pinned to status='open' (cannot self-accept).
drop policy if exists walk_requests_owner_insert on walk_requests;
create policy walk_requests_owner_insert on walk_requests
  for insert with check (owner_user_id = current_app_user_id() and status = 'open');

-- Owner may only transition their OWN OPEN request, and only to open/cancelled — never 'accepted'
-- (that path is the DEFINER helper). USING pins the pre-image to an open owned row; WITH CHECK pins
-- the post-image to open/cancelled, so the owner can cancel but not self-accept.
drop policy if exists walk_requests_owner_update on walk_requests;
create policy walk_requests_owner_update on walk_requests
  for update using (owner_user_id = current_app_user_id() and status = 'open')
  with check (owner_user_id = current_app_user_id() and status in ('open','cancelled'));

-- A TARGETED provider's active staff may READ requests aimed at their provider (so the walker sees
-- the incoming request). Broadcast rows (target_provider_id NULL) are added by C2.
drop policy if exists walk_requests_provider_read on walk_requests;
create policy walk_requests_provider_read on walk_requests
  for select using (
    target_provider_id is not null and app_is_active_staff_of(target_provider_id)
  );

-- ── 2. notifications type CHECK — widen additively (walk-request lifecycle) ────
alter table notifications drop constraint if exists notifications_type_check;
alter table notifications add constraint notifications_type_check
  check (type = any (array[
    'paw','bark','follow','lost_alert','emergency_contact','food_recall','report_received',
    'booking_requested','booking_confirmed','booking_declined','booking_cancelled',
    'adoption_under_review','adoption_approved','adoption_declined',
    'walk_request_targeted','walk_request_broadcast','walk_request_accepted','walk_request_taken'
  ]::text[]));

-- ── 3. app_accept_walk_request — the atomic, race-safe accept ─────────────────
create or replace function app_accept_walk_request(
  p_request_id  integer,
  p_provider_id integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_req        walk_requests;
  v_ts         timestamptz;
  v_credits    integer;
  v_pay_credit boolean := false;
  v_booking_id integer;
begin
  -- Defense-in-depth authorization: the ACTUAL caller (request identity GUC) must be ACTIVE STAFF of
  -- the accepting provider, even though we run as DEFINER. The route also gates (capability + role).
  if not app_is_active_staff_of(p_provider_id) then
    return null;
  end if;

  -- Row-lock the request so two concurrent accepts serialize: the second waits, then re-reads the
  -- now-accepted status below and bails. This lock (not the WHERE) is the race guard.
  select * into v_req from walk_requests where id = p_request_id for update;
  if not found then
    return null;
  end if;

  -- Must still be LIVE (open + not expired).
  if v_req.status <> 'open' or v_req.expires_at <= now() then
    return null;
  end if;

  -- Eligibility: targeted at THIS provider, or a broadcast (target NULL — C2 fans these out to
  -- eligible walkers; the broadcast read policy in C2 governs who can SEE it, this only claims it).
  if v_req.target_provider_id is not null and v_req.target_provider_id <> p_provider_id then
    return null;
  end if;

  update walk_requests
     set status = 'accepted',
         accepted_provider_id = p_provider_id,
         accepted_at = now()
   where id = p_request_id
   returning * into v_req;

  -- Fund the walk with a prepaid credit when the owner holds a balance with this provider (the credit
  -- is spent at PICKUP per B3, NOT now). Otherwise a normal payable walker booking.
  select coalesce(sum(walks_total - walks_used), 0) into v_credits
  from walk_credit_packs
  where owner_user_id = v_req.owner_user_id
    and provider_id = p_provider_id
    and active = true;
  v_pay_credit := coalesce(v_credits, 0) >= 1;

  -- A 'now' request books the near-term; a 'scheduled' request uses scheduled_at. vet_appointments
  -- keeps appointment_date/time (NOT NULL) for the reminder engine; start_at/end_at carry the slot.
  v_ts := coalesce(v_req.scheduled_at, now());

  insert into vet_appointments (
    pet_id, owner_user_id, title, appointment_date, appointment_time,
    reason_for_visit, provider_id, staff_user_id, capability,
    start_at, end_at, source, booking_status, status, pay_with_credit
  ) values (
    v_req.pet_id, v_req.owner_user_id, 'Walk', v_ts::date, v_ts::time,
    v_req.note, p_provider_id, current_app_user_id(), 'walker',
    v_ts, v_ts + interval '30 minutes', 'owner', 'confirmed', 'scheduled', v_pay_credit
  )
  returning id into v_booking_id;

  return jsonb_build_object('request', to_jsonb(v_req), 'booking_id', v_booking_id);
end;
$$;

grant execute on function app_accept_walk_request(integer, integer) to pawpi_app;
