-- 0094_engagement_care_ring_foundations.sql
-- Unit E0 of the "Pet Owner engagement" wave (docs/pet-owner-engagement.md). The small, shared
-- schema the Care Ring (E1), Streak+forgiveness (E2), Milestone moments (E3) and Share cards (E4)
-- all hang off — added ONCE here so later units don't each fight the DB.
--
-- THREE additive changes, no existing table's RLS touched:
--   0. pets."gotcha day" ALREADY EXISTS as pets.adoption_date (0003) and is ALREADY synced Dog
--      Profile <-> Pet Medical Profile (both /api/pets/[id] PATCH and /api/pet-medical-profiles
--      read+write the SAME pets.adoption_date column — one storage, no duplication). E3 reads it as
--      the "adopted_on / gotcha day". So E0 adds NO new adoption column — it reuses adoption_date.
--   1. user_profiles.timezone — the per-owner IANA tz the ring uses for its day boundary. NULLABLE
--      with NO default (honest: empty until the owner sets it; no fake value written). Consumers
--      resolve it as COALESCE(timezone, 'America/Buenos_Aires'). Purely additive column — it does
--      NOT change user_profiles' RLS (owner-private group, unchanged).
--   2. pet_care_days — one row per (pet, owner-tz day) holding the ring's derived segment state
--      (walk/moment/care) + ring_closed + a rest_day flag (E1 rest/vacation mode). Owner-scoped RLS.
--   3. pet_streaks — one row per pet: the ring-close streak summary + forgiveness state (freezes,
--      paused_until). Owner-scoped RLS.
--
-- Both new tables: ENABLE + FORCE RLS, own-row FOR ALL policy (owner_user_id = current_app_user_id())
-- — the exact pattern from 0048 training_progress_self / 0050 lost_reports. The app connects as the
-- locked-down pawpi_app role, which holds DML/sequence privileges via 0019's blanket + default grants.
--
-- DATA RULES honored: integer ids; owner_user_id = user_profiles.id (identity chain
-- auth_users.id -> user_profiles.auth_user_id -> user_profiles.id -> pets.owner_user_id); no fake /
-- seed data; owner-timezone day boundary. Everything degrades cleanly pre-migration (consumer code
-- reads [] / 0 rather than 500ing while these are absent).
--
-- Idempotent (create-if-not-exists / add-column-if-not-exists / drop-then-create policy).
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness, NOT applied to Supabase
-- here. Hand-applied by Tats AFTER merge (flagged in the PR body + test-backlog ACTION 1).
-- Verify: supabase/verify_0094.sql (every row PASS).

-- ── 1. user_profiles.timezone (per-owner day boundary; additive, no RLS change) ─
alter table user_profiles add column if not exists timezone text;

-- ── 2. pet_care_days (one row per pet per owner-tz day; the ring's derived state) ─
create table if not exists pet_care_days (
  id            integer generated by default as identity primary key,
  pet_id        integer not null references pets(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  day           date not null,
  walk_done     boolean not null default false,
  moment_done   boolean not null default false,
  care_done     boolean not null default false,
  ring_closed   boolean not null default false,
  -- E1 rest/vacation mode: a rest (or within-pause) day is marked here so E2 never counts it as a
  -- miss and the ring copy stays celebratory. Additive to the E0 spec column list.
  rest_day      boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint pet_care_days_unique unique (pet_id, day)
);
create index if not exists idx_pet_care_days_owner on pet_care_days (owner_user_id);
create index if not exists idx_pet_care_days_pet_day on pet_care_days (pet_id, day);

alter table pet_care_days enable row level security;
alter table pet_care_days force row level security;

drop policy if exists pet_care_days_owner_all on pet_care_days;
create policy pet_care_days_owner_all on pet_care_days
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- ── 3. pet_streaks (one row per pet; ring-close streak + forgiveness state) ─────
create table if not exists pet_streaks (
  pet_id            integer primary key references pets(id) on delete cascade,
  owner_user_id     integer not null references user_profiles(id) on delete cascade,
  current_count     integer not null default 0 check (current_count >= 0),
  longest_count     integer not null default 0 check (longest_count >= 0),
  last_closed_day   date,
  freezes_available integer not null default 1 check (freezes_available >= 0),
  paused_until      date,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index if not exists idx_pet_streaks_owner on pet_streaks (owner_user_id);

alter table pet_streaks enable row level security;
alter table pet_streaks force row level security;

drop policy if exists pet_streaks_owner_all on pet_streaks;
create policy pet_streaks_owner_all on pet_streaks
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());
