-- 0097_engagement_pack_streaks.sql
-- Pet Owner engagement wave — unit E7 (Pack / shared streaks, docs/pet-owner-engagement.md).
--
-- Two dog friends who BOTH close their Care Ring on the same owner-timezone day build a shared "pack
-- flame" with its own count. Opt-in (both accept), lower stakes than a personal streak, and the break
-- copy celebrates the run — it never blames one dog. Works as soon as one friend pair exists, so it is
-- safe pre-submission.
--
-- ONE new table + a small set of SECURITY DEFINER helpers (the 0044 app_notify / 0092 walk-request
-- pattern — pinned search_path, GRANT to pawpi_app). DEFINER is required because every interesting
-- action crosses the owner boundary: pets + pet_care_days are owner-scoped (0020/0094), so a caller
-- cannot read a friend's pet, see whether the friend closed their ring, or notify the friend directly.
--
-- Widens notifications_type_check with 'pack_invite' / 'pack_accepted' / 'boop'. ADDITIVE only — no
-- existing table's RLS is touched. Idempotent. Verify: supabase/verify_0097.sql.
-- HARNESS-ONLY THIS TICKET — hand-applied to Supabase after merge. Consumers DEGRADE CLEANLY while
-- absent (list -> empty, actions -> friendly 503, never a 500).

-- ── 1. pet_pack_streaks ────────────────────────────────────────────────────────
create table if not exists pet_pack_streaks (
  id                integer generated by default as identity primary key,
  requester_user_id integer not null references user_profiles(id) on delete cascade,
  receiver_user_id  integer not null references user_profiles(id) on delete cascade,
  requester_pet_id  integer not null references pets(id) on delete cascade,
  receiver_pet_id   integer not null references pets(id) on delete cascade,
  status            text not null default 'pending'
                      check (status = any (array['pending','active','ended']::text[])),
  current_count     integer not null default 0,
  longest_count     integer not null default 0,
  last_active_day   date,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

-- One pack per UNORDERED pair of pets (either direction).
create unique index if not exists idx_pet_pack_streaks_pair
  on pet_pack_streaks (least(requester_pet_id, receiver_pet_id), greatest(requester_pet_id, receiver_pet_id));
create index if not exists idx_pet_pack_streaks_requester on pet_pack_streaks (requester_pet_id);
create index if not exists idx_pet_pack_streaks_receiver on pet_pack_streaks (receiver_pet_id);

-- ── RLS: participant-scoped (either owner reads/acts) ──────────────────────────
alter table pet_pack_streaks enable row level security;
alter table pet_pack_streaks force row level security;

drop policy if exists pet_pack_streaks_participant on pet_pack_streaks;
create policy pet_pack_streaks_participant on pet_pack_streaks
  for all
  using (
    requester_user_id = current_app_user_id() or receiver_user_id = current_app_user_id()
  )
  with check (
    requester_user_id = current_app_user_id() or receiver_user_id = current_app_user_id()
  );

-- ── 2. notifications_type_check += pack types ──────────────────────────────────
alter table notifications drop constraint if exists notifications_type_check;
alter table notifications add constraint notifications_type_check
  check (type = any (array[
    'paw','bark','follow','lost_alert','emergency_contact','food_recall','report_received',
    'booking_requested','booking_confirmed','booking_declined','booking_cancelled',
    'adoption_under_review','adoption_approved','adoption_declined',
    'walk_request_targeted','walk_request_broadcast','walk_request_accepted','walk_request_taken',
    'welcome','pack_invite','pack_accepted','boop'
  ]::text[]));

-- ── 3. app_request_pack_streak — opt-in by partner @handle ─────────────────────
-- Resolves the partner pet by its public handle (DEFINER, since pets RLS hides other owners' pets),
-- creates a PENDING pack, and notifies the partner owner. Returns the new pack id, or NULL when the
-- handle is unknown, is the caller's own pet, or a pack for the pair already exists.
create or replace function app_request_pack_streak(p_pet integer, p_owner integer, p_partner_handle text)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_partner_pet   integer;
  v_partner_owner integer;
  v_id            integer;
begin
  if not exists (select 1 from pets where id = p_pet and owner_user_id = p_owner) then
    return null;
  end if;

  select id, owner_user_id into v_partner_pet, v_partner_owner
  from pets where lower(handle) = lower(btrim(p_partner_handle)) limit 1;

  if v_partner_pet is null or v_partner_pet = p_pet or v_partner_owner = p_owner then
    return null;  -- unknown handle / your own pet
  end if;

  if exists (
    select 1 from pet_pack_streaks
    where least(requester_pet_id, receiver_pet_id) = least(p_pet, v_partner_pet)
      and greatest(requester_pet_id, receiver_pet_id) = greatest(p_pet, v_partner_pet)
  ) then
    return null;  -- a pack for this pair already exists
  end if;

  insert into pet_pack_streaks
    (requester_user_id, receiver_user_id, requester_pet_id, receiver_pet_id, status)
  values (p_owner, v_partner_owner, p_pet, v_partner_pet, 'pending')
  returning id into v_id;

  perform app_notify(v_partner_owner, p_owner, 'pack_invite', v_id::text, 'invited you to a pack streak');
  return v_id;
end;
$$;

grant execute on function app_request_pack_streak(integer, integer, text) to pawpi_app;

-- ── 4. app_accept_pack_streak — the receiver opts in ───────────────────────────
create or replace function app_accept_pack_streak(p_pack_id integer, p_actor integer)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  r record;
begin
  select * into r from pet_pack_streaks where id = p_pack_id for update;
  if r is null or r.receiver_user_id <> p_actor or r.status <> 'pending' then
    return false;
  end if;
  update pet_pack_streaks set status = 'active', updated_at = now() where id = p_pack_id;
  perform app_notify(r.requester_user_id, p_actor, 'pack_accepted', p_pack_id::text, 'accepted your pack streak');
  return true;
end;
$$;

grant execute on function app_accept_pack_streak(integer, integer) to pawpi_app;

-- ── 5. app_advance_pack_streaks — called on ring close ─────────────────────────
-- For every ACTIVE pack this pet is in, if the PARTNER also closed their ring on p_day, advance the
-- shared flame (idempotent: same day = no-op; a consecutive mutual day = +1; a gap restarts at 1).
create or replace function app_advance_pack_streaks(p_pet integer, p_owner integer, p_day date)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  r record;
  v_partner_pet integer;
  v_partner_closed boolean;
begin
  for r in
    select * from pet_pack_streaks
    where status = 'active' and (requester_pet_id = p_pet or receiver_pet_id = p_pet)
  loop
    v_partner_pet := case when r.requester_pet_id = p_pet then r.receiver_pet_id else r.requester_pet_id end;
    select coalesce(bool_or(ring_closed), false) into v_partner_closed
    from pet_care_days where pet_id = v_partner_pet and day = p_day;

    -- p_pet is closed (advance is only called on close); both closed iff the partner is too.
    if v_partner_closed and (r.last_active_day is null or r.last_active_day < p_day) then
      if r.last_active_day = p_day - 1 then
        update pet_pack_streaks
          set current_count = r.current_count + 1,
              longest_count = greatest(r.longest_count, r.current_count + 1),
              last_active_day = p_day, updated_at = now()
          where id = r.id;
      else
        update pet_pack_streaks
          set current_count = 1,
              longest_count = greatest(r.longest_count, 1),
              last_active_day = p_day, updated_at = now()
          where id = r.id;
      end if;
    end if;
  end loop;
end;
$$;

grant execute on function app_advance_pack_streaks(integer, integer, date) to pawpi_app;

-- ── 6. app_pack_boop — a friendly nudge (rate-limited, only if the friend is open) ──
-- Returns 'sent' | 'already_closed' | 'already_booped' | 'not_active' | 'not_participant' | 'not_found'.
create or replace function app_pack_boop(p_pack_id integer, p_actor integer)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  r record;
  v_partner_owner integer;
  v_partner_pet   integer;
  v_partner_today date;
  v_partner_closed boolean;
begin
  select * into r from pet_pack_streaks where id = p_pack_id;
  if r is null then return 'not_found'; end if;
  if p_actor <> r.requester_user_id and p_actor <> r.receiver_user_id then return 'not_participant'; end if;
  if r.status <> 'active' then return 'not_active'; end if;

  if p_actor = r.requester_user_id then
    v_partner_owner := r.receiver_user_id; v_partner_pet := r.receiver_pet_id;
  else
    v_partner_owner := r.requester_user_id; v_partner_pet := r.requester_pet_id;
  end if;

  select (now() at time zone coalesce(timezone, 'America/Buenos_Aires'))::date
  into v_partner_today from user_profiles where id = v_partner_owner;

  select coalesce(bool_or(ring_closed), false) into v_partner_closed
  from pet_care_days where pet_id = v_partner_pet and day = v_partner_today;
  if v_partner_closed then return 'already_closed'; end if;

  -- One boop per pack per actor per UTC day (a gentle cap; E5's client toggles gate display).
  if exists (
    select 1 from notifications
    where type = 'boop' and actor_user_id = p_actor and subject_ref = p_pack_id::text
      and created_at >= (now() at time zone 'UTC')::date
  ) then
    return 'already_booped';
  end if;

  perform app_notify(v_partner_owner, p_actor, 'boop', p_pack_id::text, 'booped you — finish your ring!');
  return 'sent';
end;
$$;

grant execute on function app_pack_boop(integer, integer) to pawpi_app;

-- ── 7. app_pack_streaks_for_pet — the reader (partner display + boop availability) ──
-- Bypasses pets/pet_care_days owner RLS to expose ONLY the limited partner display fields + a derived
-- boop_available flag. Verifies the caller owns p_pet first.
create or replace function app_pack_streaks_for_pet(p_pet integer, p_owner integer)
returns table (
  id integer, status text, current_count integer, longest_count integer, last_active_day date,
  is_requester boolean, partner_pet_id integer, partner_pet_name text, partner_pet_handle text,
  partner_pet_avatar text, partner_owner_id integer, boop_available boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
#variable_conflict use_column
begin
  if not exists (select 1 from pets where id = p_pet and owner_user_id = p_owner) then
    return;
  end if;

  return query
  select
    ps.id, ps.status, ps.current_count, ps.longest_count, ps.last_active_day,
    (ps.requester_pet_id = p_pet) as is_requester,
    (case when ps.requester_pet_id = p_pet then ps.receiver_pet_id else ps.requester_pet_id end),
    pp.name::text, pp.handle::text, pp.avatar_url::text,
    (case when ps.requester_pet_id = p_pet then ps.receiver_user_id else ps.requester_user_id end),
    (
      ps.status = 'active'
      and not coalesce((
        select bool_or(cd.ring_closed) from pet_care_days cd
        where cd.pet_id = (case when ps.requester_pet_id = p_pet then ps.receiver_pet_id else ps.requester_pet_id end)
          and cd.day = (now() at time zone coalesce(po.timezone, 'America/Buenos_Aires'))::date
      ), false)
      and not exists (
        select 1 from notifications n
        where n.type = 'boop' and n.actor_user_id = p_owner and n.subject_ref = ps.id::text
          and n.created_at >= (now() at time zone 'UTC')::date
      )
    ) as boop_available
  from pet_pack_streaks ps
  join pets pp
    on pp.id = (case when ps.requester_pet_id = p_pet then ps.receiver_pet_id else ps.requester_pet_id end)
  join user_profiles po
    on po.id = (case when ps.requester_pet_id = p_pet then ps.receiver_user_id else ps.requester_user_id end)
  where ps.requester_pet_id = p_pet or ps.receiver_pet_id = p_pet
  order by ps.updated_at desc;
end;
$$;

grant execute on function app_pack_streaks_for_pet(integer, integer) to pawpi_app;
