-- 0098_engagement_leaderboards.sql
-- Pet Owner engagement wave — unit E8 (Neighborhood / breed leaderboards, docs/pet-owner-engagement.md).
--
-- Weekly leagues driven by CARE EFFORT — walk logged, ring closed, care action, paw GIVEN (reciprocity)
-- — NOT likes/paws RECEIVED, so the board rewards effort, not popularity, and doubles as a health
-- incentive. DENSITY-GATED: friends is always available; neighborhood/breed only render at/above a min
-- cohort size (config, passed by the route) — otherwise the caller falls back to friends or a clean
-- "not enough dogs near you yet" state. Location is COARSE + OPT-IN and never exposes a home address.
--
-- ADDITIVE. Two opt-in coarse-geo columns on pets, one snapshot table (for weekly promotion/relegation
-- movement), and SECURITY DEFINER helpers (the board must read OTHER owners' logs to rank them, which
-- owner-scoped RLS forbids — so ranking runs in DEFINER, like app_advance_care_streak). No existing
-- table's RLS is touched. Idempotent. Verify: supabase/verify_0098.sql.
-- HARNESS-ONLY THIS TICKET — hand-applied to Supabase after merge. Consumers DEGRADE CLEANLY while
-- absent (board -> empty-safe, opt-in -> 503).

-- ── 1. Opt-in coarse geo on pets (never lat/lng) ───────────────────────────────
alter table pets add column if not exists lb_opt_in boolean not null default false;
alter table pets add column if not exists lb_area text; -- a COARSE area label only (e.g. "Palermo, BA")

-- ── 2. Weekly snapshot table (for promotion/relegation movement) ───────────────
create table if not exists pet_leaderboard_weeks (
  id            integer generated by default as identity primary key,
  pet_id        integer not null references pets(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  flavor        text not null check (flavor = any (array['friends','breed','neighborhood']::text[])),
  week_start    date not null,
  xp            integer not null default 0,
  rank          integer,
  tier          text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  constraint pet_leaderboard_weeks_uniq unique (pet_id, flavor, week_start)
);
create index if not exists idx_pet_leaderboard_weeks_pet on pet_leaderboard_weeks (pet_id, flavor, week_start desc);

alter table pet_leaderboard_weeks enable row level security;
alter table pet_leaderboard_weeks force row level security;

drop policy if exists pet_leaderboard_weeks_owner on pet_leaderboard_weeks;
create policy pet_leaderboard_weeks_owner on pet_leaderboard_weeks
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- ── 3. app_pet_week_xp — weekly CARE-EFFORT XP for one pet ──────────────────────
-- XP = walks*10 + ring-closes*15 + care-actions*5 + paws GIVEN*2, over [week_start, week_start+7).
-- Paws GIVEN = post_paws the pet's OWNER created (reciprocity); paws/likes RECEIVED are never counted.
-- DEFINER so the ranker can score every cohort member regardless of owner.
create or replace function app_pet_week_xp(p_pet integer, p_week_start date)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_owner integer;
  v_tz    text;
  v_start timestamptz;
  v_end   timestamptz;
  v_walks integer := 0;
  v_rings integer := 0;
  v_care  integer := 0;
  v_paws  integer := 0;
begin
  select p.owner_user_id, coalesce(u.timezone, 'America/Buenos_Aires')
  into v_owner, v_tz
  from pets p join user_profiles u on u.id = p.owner_user_id
  where p.id = p_pet;
  if v_owner is null then return 0; end if;

  -- Interpret the week window in the pet owner's timezone.
  v_start := (p_week_start::timestamp) at time zone v_tz;
  v_end   := ((p_week_start + 7)::timestamp) at time zone v_tz;

  select count(*) into v_walks from health_walk_logs
   where pet_id = p_pet and start_time >= v_start and start_time < v_end;

  select count(*) into v_rings from pet_care_days
   where pet_id = p_pet and ring_closed = true and day >= p_week_start and day < p_week_start + 7;

  select
    (select count(*) from health_food_logs where pet_id = p_pet and logged_at >= v_start and logged_at < v_end)
  + (select count(*) from health_medical_care_logs where pet_id = p_pet and given_at >= v_start and given_at < v_end)
  + (select count(*) from health_wellness_logs where pet_id = p_pet and logged_at >= v_start and logged_at < v_end)
  + (select count(*) from health_photo_checks where pet_id = p_pet and created_at >= v_start and created_at < v_end)
  into v_care;

  -- Paws GIVEN by this pet's owner (reciprocity). NOT paws received.
  select count(*) into v_paws from post_paws
   where user_id = v_owner and created_at >= v_start and created_at < v_end;

  return v_walks * 10 + v_rings * 15 + coalesce(v_care, 0) * 5 + v_paws * 2;
end;
$$;

grant execute on function app_pet_week_xp(integer, date) to pawpi_app;

-- ── 4. app_leaderboard — the ranked cohort board (density-gated) ────────────────
-- Builds the cohort for the flavor, scores each member's weekly XP, and returns them ranked (highest
-- first), capped to p_limit (~league size). Returns NOTHING when the cohort is smaller than
-- p_min_cohort (the caller then falls back). Exposes ONLY coarse display fields — never a location.
create or replace function app_leaderboard(
  p_pet integer, p_owner integer, p_flavor text, p_week_start date,
  p_min_cohort integer, p_limit integer
)
returns table (
  pet_id integer, pet_name text, pet_handle text, pet_avatar text, xp integer, rank integer, is_me boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
#variable_conflict use_column
declare
  v_breed text;
  v_area  text;
  v_optin boolean;
  v_count integer;
begin
  if not exists (select 1 from pets where id = p_pet and owner_user_id = p_owner) then
    return;
  end if;
  select breed, lb_area, lb_opt_in into v_breed, v_area, v_optin from pets where id = p_pet;

  -- Resolve the cohort member set into a temp list. Drop first so the function is re-callable within
  -- one transaction (the route may call it twice — requested flavor, then the friends fallback).
  drop table if exists _cohort;
  create temporary table _cohort (pet_id integer primary key) on commit drop;

  if p_flavor = 'friends' then
    insert into _cohort (pet_id)
    select p_pet
    union
    select case when f.requester_pet_id = p_pet then f.receiver_pet_id else f.requester_pet_id end
    from pet_friendships f
    where f.status = 'accepted' and (f.requester_pet_id = p_pet or f.receiver_pet_id = p_pet)
    on conflict do nothing;

  elsif p_flavor = 'breed' then
    if v_breed is null or btrim(v_breed) = '' then return; end if;
    insert into _cohort (pet_id)
    select id from pets where lower(breed) = lower(v_breed)
    on conflict do nothing;

  elsif p_flavor = 'neighborhood' then
    if not v_optin or v_area is null or btrim(v_area) = '' then return; end if;
    insert into _cohort (pet_id)
    select id from pets where lb_opt_in = true and lower(lb_area) = lower(v_area)
    on conflict do nothing;

  else
    return;
  end if;

  select count(*) into v_count from _cohort;
  if v_count < greatest(p_min_cohort, 1) then
    return;  -- density gate — caller falls back
  end if;

  return query
  with scored as (
    select c.pet_id as pid, app_pet_week_xp(c.pet_id, p_week_start) as xp
    from _cohort c
  ), ranked as (
    select s.pid, s.xp,
           rank() over (order by s.xp desc, s.pid asc) as rnk
    from scored s
  )
  select r.pid, pp.name::text, pp.handle::text, pp.avatar_url::text, r.xp, r.rnk::integer,
         (r.pid = p_pet) as is_me
  from ranked r
  join pets pp on pp.id = r.pid
  order by r.rnk asc
  limit greatest(p_limit, 1);
end;
$$;

grant execute on function app_leaderboard(integer, integer, text, date, integer, integer) to pawpi_app;
