-- 0100_engagement_weekly_digest.sql
-- Pet Owner engagement WAVE 2 — unit E11 ("Rex's Week" weekly digest, docs/pet-owner-engagement.md).
--
-- A weekly moment of pride delivered on a fixed weekly beat (default Sunday evening, owner timezone) via
-- push AND optional email. The digest READS existing logs (walks / daily moments / paws / care logs /
-- streaks) for the owner-tz week — it stores NO new activity. This migration adds only the plumbing:
--   1. weekly_digest_prefs   — per-owner channel toggles (push default ON, email default OFF).
--   2. weekly_digest_state   — per (pet, week) idempotency so a week is NEVER double-sent.
--   3. notifications_type_check += 'weekly_digest' (the push category).
--   4. app_weekly_digest_due()— DEFINER cross-owner enumerator of pets DUE for a send right now
--      (Sunday >= 18:00 local, week not yet sent). The weekly job connects as pawpi_app with NO user
--      identity, so — like app_due_subscriptions (0039) — it can only see the due set through a DEFINER.
--
-- Both new tables ENABLE + FORCE RLS with a single own-row (owner_user_id = current_app_user_id())
-- FOR ALL policy (the 0094/0097 pattern); the app connects as pawpi_app (NOBYPASSRLS). ADDITIVE — no
-- existing table's RLS is touched. Idempotent. Verify: supabase/verify_0100.sql. HARNESS-ONLY THIS
-- TICKET — hand-applied to Supabase after merge. The routes DEGRADE CLEANLY while absent (42P01/42883 →
-- feature absent, never 500).

-- ── 1. weekly_digest_prefs — per-owner channel toggles ─────────────────────────
create table if not exists weekly_digest_prefs (
  owner_user_id integer primary key references user_profiles(id) on delete cascade,
  push_enabled  boolean not null default true,
  email_enabled boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

alter table weekly_digest_prefs enable row level security;
alter table weekly_digest_prefs force row level security;

drop policy if exists weekly_digest_prefs_all on weekly_digest_prefs;
create policy weekly_digest_prefs_all on weekly_digest_prefs
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- ── 2. weekly_digest_state — per (pet, week) idempotency ───────────────────────
-- week_start is the Monday (owner-tz) of the digested week. UNIQUE(pet_id, week_start) makes a re-run
-- for the same week a no-op (ON CONFLICT DO NOTHING). channels records which channels actually went out.
create table if not exists weekly_digest_state (
  id            integer generated by default as identity primary key,
  pet_id        integer not null references pets(id) on delete cascade,
  owner_user_id integer not null references user_profiles(id) on delete cascade,
  week_start    date not null,
  channels      text[] not null default '{}',
  sent_at       timestamptz not null default now(),
  created_at    timestamptz not null default now(),
  constraint weekly_digest_state_unique unique (pet_id, week_start)
);

create index if not exists idx_weekly_digest_state_owner
  on weekly_digest_state (owner_user_id, week_start desc);

alter table weekly_digest_state enable row level security;
alter table weekly_digest_state force row level security;

drop policy if exists weekly_digest_state_all on weekly_digest_state;
create policy weekly_digest_state_all on weekly_digest_state
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- ── 3. notifications_type_check += 'weekly_digest' ─────────────────────────────
alter table notifications drop constraint if exists notifications_type_check;
alter table notifications add constraint notifications_type_check
  check (type = any (array[
    'paw','bark','follow','lost_alert','emergency_contact','food_recall','report_received',
    'booking_requested','booking_confirmed','booking_declined','booking_cancelled',
    'adoption_under_review','adoption_approved','adoption_declined',
    'walk_request_targeted','walk_request_broadcast','walk_request_accepted','walk_request_taken',
    'welcome','pack_invite','pack_accepted','boop','weekly_digest'
  ]::text[]));

-- ── 4. app_weekly_digest_due — cross-owner DEFINER enumeration of the due set ───
-- Returns the pets whose owner-tz local time is Sunday (dow=0) at/after 18:00 AND whose current
-- owner-tz week (Monday..Sunday) has NOT already been sent (no weekly_digest_state row for that week).
-- One row per due pet, carrying the owner's channel prefs (defaulted) + email so the job never re-reads
-- owner-scoped tables across owners. p_now is passed in for deterministic testing; p_limit caps a run.
create or replace function app_weekly_digest_due(p_now timestamptz, p_limit integer)
returns table (
  owner_user_id integer,
  pet_id integer,
  pet_name text,
  tz text,
  week_start date,
  email text,
  push_enabled boolean,
  email_enabled boolean
)
language sql
security definer
set search_path = public, pg_temp
as $$
  select
    p.owner_user_id,
    p.id as pet_id,
    p.name as pet_name,
    coalesce(u.timezone, 'America/Buenos_Aires') as tz,
    -- Monday of the owner-tz week that contains "now" (date_trunc('week') → Monday).
    (date_trunc('week', (p_now at time zone coalesce(u.timezone, 'America/Buenos_Aires'))))::date as week_start,
    au.email,
    coalesce(pr.push_enabled, true) as push_enabled,
    coalesce(pr.email_enabled, false) as email_enabled
  from pets p
  join user_profiles u on u.id = p.owner_user_id
  join auth_users au on au.id = u.auth_user_id
  left join weekly_digest_prefs pr on pr.owner_user_id = p.owner_user_id
  -- Sunday evening in the owner's timezone (dow: 0 = Sunday).
  where extract(dow  from (p_now at time zone coalesce(u.timezone, 'America/Buenos_Aires'))) = 0
    and extract(hour from (p_now at time zone coalesce(u.timezone, 'America/Buenos_Aires'))) >= 18
    -- Not already sent for this owner-tz week.
    and not exists (
      select 1 from weekly_digest_state s
      where s.pet_id = p.id
        and s.week_start = (date_trunc('week', (p_now at time zone coalesce(u.timezone, 'America/Buenos_Aires'))))::date
    )
  order by p.owner_user_id, p.id
  limit greatest(coalesce(p_limit, 500), 1);
$$;

grant execute on function app_weekly_digest_due(timestamptz, integer) to pawpi_app;
