-- 0108_notification_prefs.sql
-- BX4 (business notification settings) — server-side, per-user notification
-- preferences that TRULY GATE delivery of BUSINESS-category notifications.
--
-- BACKGROUND: real in-app notifications are inserted exclusively through the
-- app_notify() SECURITY DEFINER helper (0044). The pet-owner categories
-- (social / milestone / streak / care) are muted CLIENT-SIDE via E5's
-- AsyncStorage policy and are intentionally NOT touched here. This ticket adds a
-- SERVER-SIDE store + gate for BUSINESS categories only, so a business that turns
-- a category off actually stops receiving those rows (no fake toggle).
--
-- AUDIT (which notification types actually reach a BUSINESS recipient today):
--   • walk_request_targeted  — a direct walk request lands on the target WALKER's
--     active staff (walk-requests/route.js).
--   • walk_request_broadcast — a "find a walker now" broadcast lands on every
--     live-available walker's active staff (same route).
--   Every OTHER notify (paw/bark/follow, booking_* lifecycle, walk_request_accepted,
--   adoption_*, engagement) is addressed to an OWNER, not a business. Regular
--   provider bookings do NOT notify the provider today, and chat messages /
--   reviews / payouts fire NO notification at all — so this ticket ships exactly
--   ONE business category, `walk_requests`, and adds none it can't back with a real
--   send. Future business events get a new (type → category) arm below + a row here.
--
-- MECHANISM: one small own-row table (category text, not JSONB, so the sender's
-- lookup is a trivial equality join) + a gate baked into app_notify(): before an
-- insert, the recipient's pref for the type's BUSINESS category is consulted, and
-- a disabled pref no-ops the send (returns null, inserts nothing). FAIL-OPEN — an
-- absent row (or an unknown/owner-only type) is treated as enabled, so nothing that
-- fires today goes silent by default. app_notify keeps its never-throw /
-- never-self-notify contract.
--
-- notification_prefs is ENABLE + FORCE RLS with a single own-row FOR ALL policy;
-- the app connects as pawpi_app (GET/PUT /api/notification-prefs reads + writes the
-- caller's own rows). app_notify runs as its owner (DEFINER) so its pref lookup
-- bypasses RLS — exactly like its existing cross-user insert into notifications.
-- ADDITIVE — no existing table's RLS is touched. Idempotent (re-runnable DDL +
-- CREATE OR REPLACE fn). Verify: supabase/verify_0108.sql.
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness;
-- hand-applied to Supabase AFTER merge. Routes DEGRADE CLEANLY while absent
-- (safeNotify swallows a missing-table error; the old app_notify keeps sending).

-- ── 1. notification_prefs — per-user, per-category on/off ─────────────────────
create table if not exists notification_prefs (
  id         integer generated by default as identity primary key,
  user_id    integer not null references user_profiles(id) on delete cascade,
  category   text    not null,
  enabled    boolean not null default true,
  updated_at timestamptz not null default now(),
  constraint notification_prefs_user_category_key unique (user_id, category)
);

create index if not exists idx_notification_prefs_user
  on notification_prefs (user_id);

-- ── RLS (owner = the pref's user) ─────────────────────────────────────────────
alter table notification_prefs enable row level security;
alter table notification_prefs force row level security;

drop policy if exists notification_prefs_all on notification_prefs;
create policy notification_prefs_all on notification_prefs
  for all
  using (user_id = current_app_user_id())
  with check (user_id = current_app_user_id());

-- ── 2. app_notify() — same contract, now gates BUSINESS categories ────────────
-- Adds ONE step ahead of the insert: map the notification type to its business
-- gating category; if the recipient has a pref row for that category set to false,
-- no-op (return null). Owner-only types map to no category and are never gated
-- here (their muting stays client-side, E5). Unchanged: null/self recipient no-op,
-- the cross-user insert, the returned id.
create or replace function app_notify(
  p_recipient integer,
  p_actor integer,
  p_type text,
  p_subject_ref text,
  p_body text
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  new_id     integer;
  v_category text;
  v_enabled  boolean;
begin
  if p_recipient is null or p_recipient = p_actor then
    return null;  -- never notify yourself for your own action
  end if;

  -- Map a notification type to the BUSINESS category that gates it. Only types that
  -- can reach a business recipient are listed; everything else stays null (ungated).
  v_category := case p_type
    when 'walk_request_targeted'  then 'walk_requests'
    when 'walk_request_broadcast' then 'walk_requests'
    else null
  end;

  if v_category is not null then
    select enabled into v_enabled
      from notification_prefs
      where user_id = p_recipient and category = v_category;
    -- Absent row => v_enabled is NULL => not FALSE => fail-open (send).
    if v_enabled is false then
      return null;  -- recipient disabled this business category
    end if;
  end if;

  insert into notifications (recipient_user_id, actor_user_id, type, subject_ref, body)
  values (p_recipient, p_actor, p_type, p_subject_ref, p_body)
  returning id into new_id;
  return new_id;
end;
$$;

grant execute on function app_notify(integer, integer, text, text, text) to pawpi_app;
