-- 0109_device_push_tokens.sql
-- BN2 PR1 (remote-push foundation) — the device-side of server→phone push.
--
-- BACKGROUND: PawPi has had NO server→phone push. The mobile app only schedules
-- LOCAL reminders (expo-notifications) and server events write the in-app bell via
-- app_notify() (0044/0108). This ticket adds the missing piece: a per-device Expo
-- push-token registry so the web push-SEND layer (expo-server-sdk) can ring the
-- phone for the notifications that matter. Delivery to iOS stays dark until APNs
-- credentials are configured in EAS/Apple (see docs/night-run-log.md) — the send
-- layer log-and-no-ops, never crashes, when tokens/creds are absent.
--
-- MECHANISM:
--   • device_push_tokens — one row per (user, device token). Own-row RLS so a
--     user only ever reads/writes their OWN tokens (POST /api/push-tokens).
--   • Three SECURITY DEFINER readers so the WEB push-send hook — which runs in the
--     ACTOR's request identity, not the recipient's — can resolve a DIFFERENT
--     recipient's tokens / pref / locale without loosening the own-row RLS. Same
--     pattern as 0093's app_provider_active_staff_ids (the notify fan-out reader)
--     and app_notify itself (0044, a DEFINER cross-user insert).
--
-- ADDITIVE — no existing table's RLS is touched. Idempotent (re-runnable DDL +
-- CREATE OR REPLACE fns). Verify: supabase/verify_0109.sql. HARNESS-ONLY THIS
-- TICKET — proven as pawpi_app in the integration harness; hand-applied to Supabase
-- AFTER merge. Routes DEGRADE CLEANLY while absent (the token route + send layer
-- swallow 42P01 / undefined_function; the in-app bell keeps working regardless).

-- ── 1. device_push_tokens — per-user Expo push-token registry ─────────────────
create table if not exists device_push_tokens (
  id         integer generated by default as identity primary key,
  user_id    integer not null references user_profiles(id) on delete cascade,
  token      text    not null,
  platform   text    not null default 'ios'
             constraint device_push_tokens_platform_check
             check (platform in ('ios', 'android')),
  updated_at timestamptz not null default now(),
  constraint device_push_tokens_user_token_key unique (user_id, token)
);

create index if not exists idx_device_push_tokens_user
  on device_push_tokens (user_id);

-- ── RLS (owner = the token's user) ────────────────────────────────────────────
alter table device_push_tokens enable row level security;
alter table device_push_tokens force row level security;

drop policy if exists device_push_tokens_all on device_push_tokens;
create policy device_push_tokens_all on device_push_tokens
  for all
  using (user_id = current_app_user_id())
  with check (user_id = current_app_user_id());

-- ── 2. app_recipient_push_tokens — DEFINER reader for the send fan-out ────────
-- The push-send hook runs as the ACTOR (who fired the underlying action); the
-- actor's own-row RLS cannot see the RECIPIENT's device_push_tokens, so resolving
-- a recipient's tokens needs a DEFINER reader (mirrors 0093).
create or replace function app_recipient_push_tokens(p_user_id integer)
returns table (token text, platform text)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select token, platform
  from device_push_tokens
  where user_id = p_user_id;
$$;

grant execute on function app_recipient_push_tokens(integer) to pawpi_app;

-- ── 3. app_notification_pref_enabled — DEFINER pref reader for the push gate ───
-- The push rule needs the RECIPIENT's per-category pref (notification_prefs,
-- 0108) — again unreadable under the actor's own-row RLS. Returns the stored
-- boolean, or NULL when no row exists (the caller applies the catalog default:
-- PUSH → absent=ON, OPTIONAL_PUSH → absent=OFF).
create or replace function app_notification_pref_enabled(
  p_user_id integer,
  p_category text
)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select enabled
  from notification_prefs
  where user_id = p_user_id and category = p_category;
$$;

grant execute on function app_notification_pref_enabled(integer, text) to pawpi_app;

-- ── 4. app_recipient_locale — DEFINER reader so push text renders in-locale ───
-- Push title/body are a SERVER-rendered surface, so they must honor the
-- recipient's stored language (user_profiles.preferred_locale, 0107). That column
-- lives under owner-private RLS the actor can't read, so a DEFINER reader again.
-- Returns 'en' / 'es' / NULL (NULL = es-AR fallback, the app-wide default).
create or replace function app_recipient_locale(p_user_id integer)
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select preferred_locale
  from user_profiles
  where id = p_user_id;
$$;

grant execute on function app_recipient_locale(integer) to pawpi_app;
