-- 0117_pet_medications_and_preventives.sql
-- NR4 (docs/night-run-2026-08-18.md) — make "Medications & Care" REAL. The mobile modal was an
-- in-memory mock seeded with fake meds; it now persists per pet, owner-scoped.
--
-- Three additive changes, no existing table's RLS is loosened:
--   1. pet_vaccinations (0016) gains three ADDITIVE columns so the owner-side Vaccines tab keeps a
--      full form: clinic_name, notes, reminder_enabled. Purely additive (nullable / defaulted); the
--      table's existing RLS (0022 owner-private) is untouched and provider writes are unaffected.
--   2. pet_medications — one row per pet medication (current OR past). Owner-scoped RLS.
--   3. pet_preventive_treatments — one row per preventive product (flea/tick/heartworm/supplement/…).
--      Owner-scoped RLS.
--
-- Both new tables: ENABLE + FORCE RLS, own-row FOR ALL policy (owner_user_id = current_app_user_id())
-- — the exact pattern from 0048 training_progress_self / 0050 lost_reports / 0094 pet_care_days. The
-- app connects as the locked-down pawpi_app role (DML/sequence privileges via 0019's blanket grants).
--
-- DATA RULES honored: integer ids; owner_user_id = user_profiles.id (identity chain
-- auth_users.id -> user_profiles.auth_user_id -> user_profiles.id -> pets.owner_user_id); NO seed /
-- fake data; scoped by pet_id + owner_user_id. Soft-delete (deleted_at) so history is durable.
-- Degrades cleanly pre-migration (consumer routes read [] / the modal shows empty states).
--
-- Idempotent (create-if-not-exists / add-column-if-not-exists / drop-then-create policy).
-- HARNESS-ONLY THIS TICKET — proven as pawpi_app in the integration harness. Hand-applied to Supabase
-- AFTER merge. Verify: supabase/verify_0117.sql (every row PASS).

-- ── 1. pet_vaccinations additive columns (owner-side form parity; no RLS change) ─
alter table pet_vaccinations add column if not exists clinic_name      text;
alter table pet_vaccinations add column if not exists notes            text;
alter table pet_vaccinations add column if not exists reminder_enabled boolean not null default false;

-- ── 2. pet_medications (one row per medication; current when end/completed is null) ─
create table if not exists pet_medications (
  id               integer generated by default as identity primary key,
  pet_id           integer not null references pets(id) on delete cascade,
  owner_user_id    integer not null references user_profiles(id) on delete cascade,
  name             text not null,
  dose             text,
  frequency        text,
  prescribed_by    text,
  notes            text,
  start_date       date,
  end_date         date,
  status           text not null default 'active' check (status in ('active','completed')),
  reminder_enabled boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  deleted_at       timestamptz
);
create index if not exists idx_pet_medications_owner on pet_medications (owner_user_id);
create index if not exists idx_pet_medications_pet on pet_medications (pet_id);

alter table pet_medications enable row level security;
alter table pet_medications force row level security;

drop policy if exists pet_medications_owner_all on pet_medications;
create policy pet_medications_owner_all on pet_medications
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- ── 3. pet_preventive_treatments (flea/tick/heartworm/supplement/…) ──────────────
create table if not exists pet_preventive_treatments (
  id               integer generated by default as identity primary key,
  pet_id           integer not null references pets(id) on delete cascade,
  owner_user_id    integer not null references user_profiles(id) on delete cascade,
  product_name     text not null,
  treatment_type   text,
  frequency        text,
  last_given       date,
  next_due         date,
  notes            text,
  reminder_enabled boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  deleted_at       timestamptz
);
create index if not exists idx_pet_preventive_treatments_owner on pet_preventive_treatments (owner_user_id);
create index if not exists idx_pet_preventive_treatments_pet on pet_preventive_treatments (pet_id);

alter table pet_preventive_treatments enable row level security;
alter table pet_preventive_treatments force row level security;

drop policy if exists pet_preventive_treatments_owner_all on pet_preventive_treatments;
create policy pet_preventive_treatments_owner_all on pet_preventive_treatments
  for all
  using (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());
