-- 0125_provider_claims.sql
-- Ledger + verification pipeline behind the mobile "¿Es tu negocio? Reclamalo" flow.
-- Depends on 0124_provider_claimable (adds claim_status + system directory owner).
--
-- MVP shape (per the seed-and-claim spec):
--   • claimant taps "This is my business" on an unclaimed listing → POST /providers/:id/claim
--     writes a `pending` row here (with method + optional note/evidence).
--   • admin approves or rejects from an admin console → POST /admin/provider-claims/:id/decision.
--   • Approval is a SECURITY DEFINER function (`app_claim_provider`) so ownership can transfer
--     out of the system directory user without a separate service-role DB path (matches the
--     0024/0114 house pattern: bypass RLS through DEFINER, not through a second connection).
--
-- Automated phone/email verification is NOT built here — the spec captures method + evidence
-- and leaves auto-verify as a documented follow-up.
--
-- ⚠️ HARNESS-ONLY THIS MIGRATION — proven under pawpi_app + FORCE RLS in the integration
-- harness. Hand-apply to Supabase at cutover (docs/rls-hardening.md), same as 0124.
-- Additive + idempotent.

begin;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1) provider_claims — one row per (business, claimant). Re-claim after a rejection
--    updates the existing row back to 'pending' (the UNIQUE constraint prevents duplicates).
create table if not exists provider_claims (
  id                       integer generated by default as identity primary key,
  provider_id              integer not null references providers(id) on delete cascade,
  claimant_user_profile_id integer not null references user_profiles(id) on delete cascade,
  status                   text not null default 'pending'
                             check (status = any (array['pending','approved','rejected','withdrawn']::text[])),
  method                   text
                             check (method is null or method = any (array['phone','email','document','other']::text[])),
  evidence                 jsonb,
  note                     text,
  created_at               timestamptz not null default now(),
  decided_at               timestamptz,
  decided_by               integer references user_profiles(id),
  constraint provider_claims_provider_claimant_key unique (provider_id, claimant_user_profile_id)
);

create index if not exists idx_provider_claims_provider  on provider_claims (provider_id);
create index if not exists idx_provider_claims_claimant on provider_claims (claimant_user_profile_id);
create index if not exists idx_provider_claims_status   on provider_claims (status);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2) RLS — mirrors the 0024 style (current_app_user_id() = the acting user).
alter table provider_claims enable row level security;
alter table provider_claims force row level security;

-- SELECT: my own claims (the claim-status page) OR platform admin (the review queue).
drop policy if exists provider_claims_select on provider_claims;
create policy provider_claims_select on provider_claims
  for select using (
    claimant_user_profile_id = current_app_user_id()
    or app_is_admin()
  );

-- INSERT: I can only open a claim as myself, and only against a listing that is currently
-- UNCLAIMED. The providers EXISTS runs under providers' own SELECT RLS — a published
-- unclaimed listing is visible to any authed caller (0024), so no DEFINER helper is needed.
drop policy if exists provider_claims_insert on provider_claims;
create policy provider_claims_insert on provider_claims
  for insert with check (
    claimant_user_profile_id = current_app_user_id()
    and exists (select 1 from providers p
                where p.id = provider_id and p.claim_status = 'unclaimed')
  );

-- UPDATE: claimant may withdraw their own claim; admin may decide (approve/reject) — but the
-- ownership-transfer side of approval runs through app_claim_provider (below), NOT here.
drop policy if exists provider_claims_update on provider_claims;
create policy provider_claims_update on provider_claims
  for update using (
    claimant_user_profile_id = current_app_user_id()
    or app_is_admin()
  );

-- No DELETE policy — withdrawals go through status='withdrawn' (soft-close), never row delete.

-- ─────────────────────────────────────────────────────────────────────────────
-- 3) app_claim_provider — the ONE approval transaction that reassigns ownership.
--    SECURITY DEFINER so it bypasses providers/provider_staff FORCE RLS (the caller
--    is not yet the owner and cannot pass 0024's WITH CHECK). The route around it
--    still enforces "caller is admin" in the app layer AND we re-check inside the fn
--    (defense in depth — a mistakenly EXECUTE-granted path still can't wield this).
--
--    Steps, in one tx (the function body is one implicit txn):
--      a) provider must currently be 'unclaimed' or 'pending' → set owner = claimant,
--         claim_status = 'claimed', claimed_at = now(). Raises if the row is already
--         claimed (idempotency of the caller is the caller's problem, not this fn's).
--      b) provider_staff (provider, claimant, 'owner', 'active') — upsert on the
--         (provider, user) UNIQUE. Handles the "claimant was already staff of the
--         seeded row" edge case; in the normal case the system directory has NO
--         staff row so this is a plain insert.
--      c) mark this claim approved (decided_at, decided_by).
--      d) reject every OTHER pending claim on the same provider.
create or replace function app_claim_provider(
  p_claim_id integer,
  p_admin_user_profile_id integer
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_provider_id integer;
  v_claimant    integer;
  v_claim_status text;
  v_prov_claim_status text;
  v_admin_is_admin boolean;
begin
  -- Admin gate — re-check inside the fn (defense in depth). Uses app_is_admin() under
  -- the CALLER identity swapped to the passed admin id.
  select (up.role = 'admin' or coalesce(up.is_admin, false))
    into v_admin_is_admin
    from user_profiles up where up.id = p_admin_user_profile_id;
  if v_admin_is_admin is not true then
    raise exception 'app_claim_provider: caller % is not an admin', p_admin_user_profile_id
      using errcode = '42501';
  end if;

  select provider_id, claimant_user_profile_id, status
    into v_provider_id, v_claimant, v_claim_status
    from provider_claims where id = p_claim_id;
  if v_provider_id is null then
    raise exception 'app_claim_provider: claim % not found', p_claim_id
      using errcode = 'P0002';
  end if;
  if v_claim_status <> 'pending' then
    raise exception 'app_claim_provider: claim % is % (must be pending)', p_claim_id, v_claim_status
      using errcode = '22023';
  end if;

  select claim_status into v_prov_claim_status from providers where id = v_provider_id;
  if v_prov_claim_status = 'claimed' then
    raise exception 'app_claim_provider: provider % is already claimed', v_provider_id
      using errcode = '22023';
  end if;

  update providers
     set owner_user_profile_id = v_claimant,
         claim_status = 'claimed',
         claimed_at = now(),
         updated_at = now()
   where id = v_provider_id
     and claim_status in ('unclaimed','pending');

  insert into provider_staff (provider_id, user_profile_id, role, status)
    values (v_provider_id, v_claimant, 'owner', 'active')
    on conflict (provider_id, user_profile_id)
      do update set role = 'owner', status = 'active', updated_at = now();

  update provider_claims
     set status = 'approved',
         decided_at = now(),
         decided_by = p_admin_user_profile_id
   where id = p_claim_id;

  -- Auto-reject every OTHER pending claim on this provider (only one owner wins).
  update provider_claims
     set status = 'rejected',
         decided_at = now(),
         decided_by = p_admin_user_profile_id
   where provider_id = v_provider_id
     and id <> p_claim_id
     and status = 'pending';
end $$;

grant execute on function app_claim_provider(integer, integer) to pawpi_app;

commit;
