-- TEMPLATE.sql — the secure pattern every PawPi migration must follow.
--
-- ⚠️ This file is NOT a migration. It is never applied: the integration harness
-- (anything/apps/web/test/integration/migrate.ts) only runs files matching
-- NNNN_*.sql, and Supabase applies whatever you paste into the SQL editor. Copy
-- this file to supabase/migrations/NNNN_short_name.sql (NNNN = the next free
-- number; today's highest is 0127) and delete the parts you don't need.
--
-- The rules below are enforced or checked in CI:
--   • RLS completeness  — test/integration/rls-gap-closure.integration.test.ts
--       FAILS if a NEW public base table is not ENABLE+FORCE RLS with >=1 policy,
--       or is not in the documented RLS_EXEMPT allowlist.
--   • DEFINER search_path — test/integration/security-hardening.integration.test.ts
--       FAILS if a SECURITY DEFINER function in schema public does not pin search_path.
--   • Route identity — src/app/api/rls-rollout-completeness.test.js
--       every DB-touching route runs inside withRequestContext (sets app.current_user_id).
-- See docs/rls-hardening.md for the full model and CLAUDE.md → "Database migration
-- conventions" for the short rules.

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. NEW TABLE. Every table created in schema `public` MUST enable + force RLS and
--    carry owner-scoped policies. `current_app_user_id()` (0019) returns the
--    caller's user_profiles.id, or NULL when no identity is in scope → the int
--    comparison is NULL/false → DENY BY DEFAULT.
--
--    Do NOT `GRANT ... TO anon` / `authenticated` / `PUBLIC` on app tables. The app
--    connects as pawpi_app, never via the Supabase Data API (PostgREST). pawpi_app
--    already holds table/sequence DML on all objects (0019 blanket grant + its
--    ALTER DEFAULT PRIVILEGES for future objects), so a new table needs no re-grant.

create table if not exists example_widgets (
  id             integer generated by default as identity primary key,
  owner_user_id  integer not null references user_profiles(id),
  label          text not null,
  created_at     timestamptz not null default now()
);

alter table example_widgets enable row level security;
alter table example_widgets force  row level security;

-- Owner-only: read + write your own rows. (For a social/public-read table use a
-- FOR SELECT `current_app_user_id() IS NOT NULL` policy + a FOR ALL owner policy;
-- for provider-accessible medical data split per command and reuse
-- app_provider_has_grant(pet_id, scope). See docs/rls-hardening.md R2b/R2c/R2d.)
create policy example_widgets_owner_all on example_widgets
  for all
  using      (owner_user_id = current_app_user_id())
  with check (owner_user_id = current_app_user_id());

-- Index the foreign key you filter/join on (avoids seq scans + the advisor warning).
create index if not exists idx_example_widgets_owner on example_widgets(owner_user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. NEW SECURITY DEFINER FUNCTION. Only use DEFINER when the function must read a
--    table the CALLER's RLS would hide (e.g. another owner's grant row). It MUST
--    pin search_path (closes the DEFINER search-path-hijack hole) and grant EXECUTE
--    explicitly to pawpi_app (so a future REVOKE ... FROM PUBLIC can't break it).
--    Plain lookups that only read the GUC or the caller's own rows should stay
--    SECURITY INVOKER (the default) — do not reach for DEFINER by habit.

create or replace function app_example_helper(p_pet_id integer)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp   -- REQUIRED for every SECURITY DEFINER function
as $$
  select exists (
    select 1 from example_widgets w where w.id = p_pet_id
  )
$$;

grant execute on function app_example_helper(integer) to pawpi_app;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Ship a supabase/verify_NNNN.sql alongside anything hand-applied (role/grant/
--    RLS/auth/storage), shaped so every row reads PASS. See verify_0126.sql /
--    verify_0127.sql for the pattern.
