import React, { useState } from "react";
import { View, Text, ScrollView, Image } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import {
  X,
  Bell,
  PawPrint,
  Megaphone,
  MapPin,
  Utensils,
  Target,
  ChevronRight,
  ShieldCheck,
} from "lucide-react-native";
import { useRouter } from "expo-router";
import { COLORS } from "@/constants/colors";
import { TYPE, RADIUS, SPACING, MATERIALS, BLUR } from "@/constants/theme";
import { Card, PressableScale, GlassSurface } from "@/components/ui";
import useSocialPetStore from "@/store/socialPetStore";
import {
  handleNotificationTap,
  getNotificationDisplayInfo,
} from "@/utils/handleNotificationTap";
import {
  useNotifications,
  useMarkNotificationsRead,
} from "@/hooks/useNotifications";
import { useAllCareAccessGrants } from "@/hooks/useCareAccessGrants";

const FILTER_OPTIONS = [
  "All",
  "Requests",
  "Walks",
  "Feeding",
  "Paws",
  "Barks",
  "Training",
];

// Map a pending care-access grant (a vet/business asking to see a pet's record)
// into the screen's item shape. Tagged _source:"access" so a tap routes to the
// Data Access trust screen where the owner can approve/deny. Owner-scoped by the
// route, reactive via React Query, so it survives restart and clears on decision.
function mapAccessGrant(g) {
  return {
    id: `access-${g.id}`,
    _source: "access",
    type: "access",
    title: g.provider_name || "A care provider",
    message: `wants access to ${g.pet_name || "your pet"}'s records`,
    timestamp: g.created_at,
    read: false, // a pending request is always unread until acted on
  };
}

// Map a DB social notification (ticket 2.26) into the screen's item shape, tagged
// _source:"db" so tap-through + mark-read use the API path (reminders use the store).
const TYPE_LABEL = { paw: "New paw", bark: "New bark", follow: "New follower" };
function mapDbNotification(n) {
  return {
    id: `db-${n.id}`,
    _source: "db",
    _dbId: n.id,
    type: n.type,
    title: n.actor_username ? `@${n.actor_username}` : "Someone",
    message: n.body || TYPE_LABEL[n.type] || "New activity",
    timestamp: n.created_at,
    read: !!n.read_at,
    avatar: n.actor_avatar || null,
    // follow taps to the pet; paw/bark relate to a post (returns to the feed).
    relatedPetId: n.type === "follow" ? n.subject_ref : null,
    relatedPostId: n.type === "follow" ? null : n.subject_ref,
  };
}

const NotificationIcon = ({ type }) => {
  switch (type) {
    case "walk":
      return <MapPin size={18} color={COLORS.sage} />;
    case "feeding":
      return <Utensils size={18} color={COLORS.coral} />;
    case "paw":
      return <PawPrint size={18} color={COLORS.coral} fill={COLORS.coral} />;
    case "bark":
      return <Megaphone size={18} color={COLORS.terracotta} />;
    case "training":
      return <Target size={18} color={COLORS.sageDark} />;
    case "access":
      return <ShieldCheck size={18} color={COLORS.sageDark} />;
    default:
      return <Bell size={18} color={COLORS.mutedBrown} />;
  }
};

const formatTimestamp = (timestamp) => {
  const now = new Date();
  const then = new Date(timestamp);
  const diffMs = now - then;
  const diffMins = Math.floor(diffMs / 60000);
  const diffHours = Math.floor(diffMs / 3600000);
  const diffDays = Math.floor(diffMs / 86400000);

  if (diffMins < 60) return `${diffMins}m ago`;
  if (diffHours < 24) return `${diffHours}h ago`;
  if (diffDays === 1) return "Yesterday";
  if (diffDays < 7) return `${diffDays}d ago`;
  return then.toLocaleDateString();
};

export default function NotificationsScreen() {
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const [selectedFilter, setSelectedFilter] = useState("All");

  // Reminder notifications live in the local store (generated by the reminder engine);
  // social notifications come from the API. The bell merges BOTH (ticket 2.26).
  const storeNotifications = useSocialPetStore((state) => state.notifications);
  const markNotificationRead = useSocialPetStore(
    (state) => state.markNotificationRead,
  );
  const markAllNotificationsRead = useSocialPetStore(
    (state) => state.markAllNotificationsRead,
  );

  const { data: dbNotifications } = useNotifications();
  const markRead = useMarkNotificationsRead();

  // Pending care-access requests (a vet/business asking to see a pet's records)
  // are owner-scoped grants, not social notifications — they'd otherwise only be
  // visible if the owner manually opened More → Data Access. Surface them in the
  // bell so a request the owner would want to approve/deny is impossible to miss.
  const { data: careGrants } = useAllCareAccessGrants();

  // Merge: local reminder notifications (those with a reminderId) + the real social
  // notifications from the API + pending care-access requests, newest first. No mock data.
  const reminderNotifs = (storeNotifications || []).filter((n) => n.reminderId);
  const socialNotifs = (dbNotifications || []).map(mapDbNotification);
  const accessNotifs = (careGrants || [])
    .filter((g) => g.status === "pending")
    .map(mapAccessGrant);
  const merged = [...accessNotifs, ...socialNotifs, ...reminderNotifs].sort(
    (a, b) => new Date(b.timestamp) - new Date(a.timestamp),
  );

  // Filter notifications
  const filteredNotifications = merged.filter((notif) => {
    if (selectedFilter === "All") return true;
    const typeMap = {
      Requests: "access",
      Walks: "walk",
      Feeding: "feeding",
      Paws: "paw",
      Barks: "bark",
      Training: "training",
    };
    return notif.type === typeMap[selectedFilter];
  });

  const handleNotifTap = (notif) => {
    if (notif._source === "access") {
      // Take the owner to the trust screen to approve/deny the request.
      router.push("/(tabs)/more/data-access");
      return;
    }

    if (notif._source === "db") {
      if (!notif.read) markRead.mutate({ ids: [notif._dbId] });
      if (notif.relatedPetId) {
        router.push({
          pathname: "/pet-profile",
          params: { petId: String(notif.relatedPetId) },
        });
      } else {
        router.back(); // paw/bark → back to the feed where the post lives
      }
      return;
    }

    // Reminder notification (local store).
    if (!notif.read) {
      markNotificationRead(notif.id);
    }
    if (notif.reminderId) {
      handleNotificationTap(notif);
    } else if (notif.relatedWalkId) {
      router.back();
    }
  };

  const handleMarkAllRead = () => {
    markAllNotificationsRead(); // local reminder notifications
    markRead.mutate({ all: true }); // real social notifications
  };

  return (
    <View style={{ flex: 1, backgroundColor: COLORS.cream }}>
      {/* Header */}
      <GlassSurface
        intensity={BLUR.thick}
        style={{ borderBottomWidth: 1, borderColor: MATERIALS.glassBorder }}
        contentStyle={{
          paddingTop: insets.top + 6,
          paddingHorizontal: SPACING.xl,
          paddingBottom: SPACING.md,
        }}
      >
        <View
          style={{
            flexDirection: "row",
            alignItems: "center",
            justifyContent: "space-between",
          }}
        >
          <PressableScale onPress={() => router.back()} accessibilityRole="button">
            <X size={22} color={COLORS.mutedBrown} />
          </PressableScale>
          <Text style={[TYPE.headline, { color: COLORS.warmBrown }]}>
            Notifications
          </Text>
          <PressableScale onPress={handleMarkAllRead} accessibilityRole="button">
            <Text style={[TYPE.subhead, { fontWeight: "700", color: COLORS.coral }]}>
              Mark all read
            </Text>
          </PressableScale>
        </View>
      </GlassSurface>

      {/* Filter chips */}
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        contentContainerStyle={{
          alignItems: "center",
          paddingHorizontal: SPACING.xl,
          paddingVertical: SPACING.lg,
          gap: SPACING.sm,
        }}
        style={{
          flexGrow: 0,
          borderBottomWidth: 1,
          borderBottomColor: MATERIALS.hairline,
          backgroundColor: COLORS.card,
        }}
      >
        {FILTER_OPTIONS.map((filter) => {
          const isSelected = selectedFilter === filter;
          return (
            <PressableScale
              key={filter}
              onPress={() => setSelectedFilter(filter)}
              accessibilityRole="button"
              style={{
                paddingHorizontal: SPACING.lg,
                paddingVertical: SPACING.sm,
                borderRadius: RADIUS.chip,
                backgroundColor: isSelected ? COLORS.coral : MATERIALS.surfaceSunken,
                borderWidth: 1,
                borderColor: isSelected ? COLORS.coral : MATERIALS.hairline,
              }}
            >
              <Text
                style={[
                  TYPE.subhead,
                  { fontWeight: "700", color: isSelected ? "#FFF" : COLORS.mutedBrown },
                ]}
              >
                {filter}
              </Text>
            </PressableScale>
          );
        })}
      </ScrollView>

      {/* Notifications list */}
      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={{ paddingBottom: insets.bottom + 20 }}
      >
        {filteredNotifications.length === 0 ? (
          <View style={{ alignItems: "center", paddingVertical: 80 }}>
            <Text style={{ fontSize: 48 }}>🐾</Text>
            <Text
              style={[
                TYPE.headline,
                { fontWeight: "700", color: COLORS.warmBrown, marginTop: SPACING.lg },
              ]}
            >
              No new notifications yet
            </Text>
            <Text
              style={[
                TYPE.callout,
                {
                  color: COLORS.mutedBrown,
                  marginTop: SPACING.sm,
                  textAlign: "center",
                  paddingHorizontal: SPACING.huge,
                },
              ]}
            >
              It's quiet here for now.
            </Text>
          </View>
        ) : (
          filteredNotifications.map((notif) => {
            const isReminder = !!notif.reminderId;
            const displayInfo = isReminder
              ? getNotificationDisplayInfo(notif)
              : null;

            return (
              <PressableScale
                key={notif.id}
                onPress={() => handleNotifTap(notif)}
                accessibilityRole="button"
                style={{ marginHorizontal: SPACING.lg, marginTop: SPACING.md }}
              >
                <Card
                  level={notif.read ? "none" : "sm"}
                  radius={RADIUS.card}
                  color={notif.read ? COLORS.card : COLORS.sand}
                  borderColor={notif.read ? MATERIALS.hairline : COLORS.coral}
                  style={{
                    padding: SPACING.lg,
                    shadowColor: notif.read ? "transparent" : COLORS.coral,
                    shadowOffset: { width: 0, height: 2 },
                    shadowOpacity: notif.read ? 0 : 0.1,
                    shadowRadius: 8,
                    elevation: notif.read ? 0 : 2,
                  }}
                >
                  <View style={{ flexDirection: "row", gap: SPACING.md }}>
                  {notif.avatar ? (
                    <Image
                      source={{ uri: notif.avatar }}
                      style={{
                        width: 44,
                        height: 44,
                        borderRadius: 22,
                        borderWidth: 2,
                        borderColor: COLORS.coral,
                      }}
                    />
                  ) : (
                    <View
                      style={{
                        width: 44,
                        height: 44,
                        borderRadius: 22,
                        backgroundColor: displayInfo
                          ? displayInfo.color + "20"
                          : COLORS.peach,
                        justifyContent: "center",
                        alignItems: "center",
                      }}
                    >
                      <Text style={{ fontSize: 20 }}>
                        {displayInfo ? (
                          displayInfo.icon
                        ) : (
                          <NotificationIcon type={notif.type} />
                        )}
                      </Text>
                    </View>
                  )}

                  <View style={{ flex: 1 }}>
                    <View
                      style={{
                        flexDirection: "row",
                        justifyContent: "space-between",
                        alignItems: "flex-start",
                        marginBottom: SPACING.xs,
                      }}
                    >
                      <Text
                        style={[
                          TYPE.callout,
                          {
                            fontWeight: "800",
                            color: COLORS.warmBrown,
                            flex: 1,
                            marginRight: SPACING.sm,
                          },
                        ]}
                      >
                        {notif.title}
                      </Text>
                      <Text
                        style={[
                          TYPE.caption,
                          { letterSpacing: 0, fontWeight: "500", color: COLORS.mutedBrown },
                        ]}
                      >
                        {formatTimestamp(notif.timestamp)}
                      </Text>
                    </View>
                    <Text
                      style={[
                        TYPE.subhead,
                        {
                          fontWeight: "500",
                          color: COLORS.mutedBrown,
                          lineHeight: 19,
                          marginBottom: isReminder && notif.actionLabel ? SPACING.sm : 0,
                        },
                      ]}
                    >
                      {notif.message}
                    </Text>

                    {/* Action button for reminder notifications */}
                    {isReminder && notif.actionLabel && (
                      <View
                        style={{
                          flexDirection: "row",
                          alignItems: "center",
                          backgroundColor: displayInfo?.color || COLORS.sage,
                          borderRadius: RADIUS.control,
                          paddingHorizontal: SPACING.md,
                          paddingVertical: SPACING.sm,
                          alignSelf: "flex-start",
                        }}
                      >
                        <Text
                          style={[
                            TYPE.footnote,
                            { fontWeight: "700", color: "#FFF", marginRight: SPACING.xs },
                          ]}
                        >
                          {notif.actionLabel}
                        </Text>
                        <ChevronRight size={14} color="#FFF" />
                      </View>
                    )}
                  </View>

                  {!notif.read && (
                    <View
                      style={{
                        width: 8,
                        height: 8,
                        borderRadius: 4,
                        backgroundColor: COLORS.coral,
                        position: "absolute",
                        top: 16,
                        right: 16,
                      }}
                    />
                  )}
                  </View>
                </Card>
              </PressableScale>
            );
          })
        )}
      </ScrollView>
    </View>
  );
}
